const {
  withDangerousMod,
  withInfoPlist,
  createRunOncePlugin,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Expo config plugin for certificate pinning.
 *
 * Android: Generates network_security_config.xml with SHA-256 SPKI pin hashes
 * for api.mizanly.app and e2e.mizanly.app. Android 7+ enforces these pins
 * at the OkHttp level — a MITM with a rogue CA cert is rejected.
 *
 * iOS: Adds App Transport Security (ATS) configuration with pinned domains.
 * For full pinning on iOS, TrustKit or a native module is needed (Phase 2).
 *
 * Pin rotation: Always include 2 pins per domain (primary + backup).
 * When rotating certs, update the backup pin first, deploy, then swap primary.
 *
 * To get your pin hashes:
 *   openssl s_client -connect api.mizanly.app:443 -showcerts 2>/dev/null | \
 *     openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | \
 *     openssl dgst -sha256 -binary | base64
 *
 * Usage: add "./plugins/certificate-pinning/app.plugin" to plugins array in app.json
 */

const PLUGIN_NAME = 'mizanly-certificate-pinning';

// ============================================================
// PIN CONFIGURATION
// ============================================================

// SHA-256 SPKI hashes for certificate pinning.
// Generated 2026-03-28 from live production certs using:
//   openssl s_client -connect api.mizanly.app:443 -showcerts | openssl x509 -pubkey -noout | \
//     openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | base64
//
// Each domain needs 2 pins: primary (leaf cert) + backup (intermediate CA).
// The backup pin allows certificate rotation without app updates.
const PINNED_DOMAINS = [
  {
    domain: 'api.mizanly.app',
    pins: [
      // Primary: leaf certificate SPKI hash (Railway/Cloudflare)
      'cRZwLNgQoGbIG0UAYZun62UeVxrduZabom9awhuYWew=',
      // Backup: intermediate CA SPKI hash (survives leaf cert rotation)
      'iFvwVyJSxnQdyaUvUERIf+8qk7gRze3612JMwoO3zdU=',
    ],
    includeSubdomains: true,
  },
  {
    domain: 'e2e.mizanly.app',
    pins: [
      // Same CA chain (both behind Cloudflare)
      'cRZwLNgQoGbIG0UAYZun62UeVxrduZabom9awhuYWew=',
      'iFvwVyJSxnQdyaUvUERIf+8qk7gRze3612JMwoO3zdU=',
    ],
    includeSubdomains: false,
  },
];

// ============================================================
// ANDROID: network_security_config.xml
// ============================================================

function withAndroidCertPinning(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const resDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );

      // Create xml directory if it doesn't exist
      if (!fs.existsSync(resDir)) {
        fs.mkdirSync(resDir, { recursive: true });
      }

      // Generate network_security_config.xml
      const pinEntries = PINNED_DOMAINS.map((d) => {
        const pins = d.pins.map((p) => `            <pin digest="SHA-256">${p}</pin>`).join('\n');
        return `
        <domain-config>
            <domain includeSubdomains="${d.includeSubdomains}">${d.domain}</domain>
            <pin-set expiration="2027-06-01">
${pins}
            </pin-set>
        </domain-config>`;
      }).join('\n');

      const xml = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Certificate pinning configuration for Mizanly.
  Generated by plugins/certificate-pinning/app.plugin.js

  Android 7+ (API 24) enforces these pins at the network level.
  A MITM attacker with a rogue CA certificate is rejected.

  Pin expiration: 2027-06-01 (Android falls back to system CAs after expiry,
  preventing bricked apps if pins are not updated).
-->
<network-security-config>
    <!-- Base config: trust system CAs for non-pinned domains -->
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
${pinEntries}
</network-security-config>
`;

      fs.writeFileSync(path.join(resDir, 'network_security_config.xml'), xml);

      // Update AndroidManifest.xml to reference the config
      const manifestPath = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'AndroidManifest.xml',
      );
      if (fs.existsSync(manifestPath)) {
        let manifest = fs.readFileSync(manifestPath, 'utf-8');
        if (!manifest.includes('networkSecurityConfig')) {
          manifest = manifest.replace(
            '<application',
            '<application android:networkSecurityConfig="@xml/network_security_config"',
          );
          fs.writeFileSync(manifestPath, manifest);
        }
      }

      return cfg;
    },
  ]);
}

// ============================================================
// iOS: Info.plist ATS configuration
// ============================================================

function withIOSCertPinning(config) {
  return withInfoPlist(config, (cfg) => {
    // App Transport Security — enforce HTTPS + forward secrecy
    cfg.modResults.NSAppTransportSecurity = {
      NSAllowsArbitraryLoads: false,
      NSExceptionDomains: {
        'mizanly.app': {
          NSIncludesSubdomains: true,
          NSExceptionRequiresForwardSecrecy: true,
          NSExceptionMinimumTLSVersion: 'TLSv1.2',
        },
      },
    };

    // TrustKit configuration for iOS certificate pinning (C12).
    // TrustKit is a native iOS library that enforces SPKI pinning at the
    // NSURLSession level. When installed via `npx expo install react-native-trustkit`,
    // it reads this config from Info.plist and rejects connections to pinned domains
    // if the certificate doesn't match any pin.
    //
    // Until TrustKit is installed, this config is harmless (just plist entries).
    // Once installed, it activates automatically.
    cfg.modResults.TSKConfiguration = {
      TSKSwizzleNetworkDelegates: true,
      TSKPinnedDomains: {},
    };

    // Add each pinned domain to TrustKit config
    for (const domain of PINNED_DOMAINS) {
      cfg.modResults.TSKConfiguration.TSKPinnedDomains[domain.domain] = {
        TSKEnforcePinning: true,
        TSKIncludesSubdomains: domain.includeSubdomains,
        TSKPublicKeyHashes: domain.pins,
        // Report URI for pin violation monitoring (optional)
        // TSKReportUris: ['https://api.mizanly.app/api/v1/internal/pin-violation'],
      };
    }

    return cfg;
  });
}

// ============================================================
// PLUGIN ENTRY POINT
// ============================================================

function withCertificatePinning(config) {
  config = withAndroidCertPinning(config);
  config = withIOSCertPinning(config);
  return config;
}

module.exports = createRunOncePlugin(withCertificatePinning, PLUGIN_NAME, '1.0.0');
