import { Test, TestingModule } from '@nestjs/testing';
import { TwoFactorService } from './two-factor.service';
import { PrismaService } from '../../config/prisma.service';
import { NotFoundException, BadRequestException } from '@nestjs/common';

// Mock external modules
jest.mock('otplib', () => ({
  authenticator: {
    generateSecret: jest.fn(),
    keyuri: jest.fn(),
    verify: jest.fn(),
  },
}));

jest.mock('qrcode', () => ({
  toDataURL: jest.fn(),
}));

describe('TwoFactorService', () => {
  let service: TwoFactorService;
  let prisma: PrismaService;

  // Mock data
  const mockUserId = 'user-123';
  const mockUser = {
    id: mockUserId,
    email: 'test@example.com',
    displayName: 'Test User',
  };
  const mockSecret = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  const mockBackupCodes = ['BACKUP001', 'BACKUP002', 'BACKUP003'];
  const mockBackupCodesHashed = [
    'hash1',
    'hash2',
    'hash3',
  ];
  const mockQrDataUri = 'data:image/png;base64,QRCODE';

  // Mock PrismaService
  const mockPrismaService = {
    user: {
      findUnique: jest.fn(),
    },
    twoFactorSecret: {
      findUnique: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
    },
  };

  // Mock authenticator and qrcode
  const mockAuthenticator = require('otplib').authenticator;
  const mockQrcode = require('qrcode');

  beforeEach(async () => {
    // Clear all mocks
    jest.clearAllMocks();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        TwoFactorService,
        { provide: PrismaService, useValue: mockPrismaService },
      ],
    }).compile();

    service = module.get<TwoFactorService>(TwoFactorService);
    prisma = module.get<PrismaService>(PrismaService);

    // Default mock implementations
    mockPrismaService.user.findUnique.mockResolvedValue(mockUser);
    mockAuthenticator.generateSecret.mockReturnValue(mockSecret);
    mockAuthenticator.keyuri.mockReturnValue('otpauth://totp/Mizanly:test@example.com?secret=ABCDEFGHIJKLMNOPQRSTUVWXYZ234567&issuer=Mizanly');
    mockAuthenticator.verify.mockReturnValue(true);
    mockQrcode.toDataURL.mockResolvedValue(mockQrDataUri);
  });

  describe('setup', () => {
    it('should generate secret, QR code, and backup codes for new user', async () => {
      // No existing secret record
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(null);
      mockPrismaService.twoFactorSecret.create.mockResolvedValue({
        userId: mockUserId,
        secret: mockSecret,
        backupCodes: mockBackupCodesHashed,
        isEnabled: false,
        verifiedAt: null,
      });

      const result = await service.setup(mockUserId);

      expect(mockPrismaService.user.findUnique).toHaveBeenCalledWith({
        where: { id: mockUserId },
      });
      expect(mockPrismaService.twoFactorSecret.findUnique).toHaveBeenCalledWith({
        where: { userId: mockUserId },
      });
      expect(mockAuthenticator.generateSecret).toHaveBeenCalledWith(32);
      expect(mockAuthenticator.keyuri).toHaveBeenCalledWith(mockUser.email, 'Mizanly', mockSecret);
      expect(mockQrcode.toDataURL).toHaveBeenCalledWith('otpauth://totp/Mizanly:test@example.com?secret=ABCDEFGHIJKLMNOPQRSTUVWXYZ234567&issuer=Mizanly');
      expect(mockPrismaService.twoFactorSecret.create).toHaveBeenCalledWith({
        data: {
          userId: mockUserId,
          secret: mockSecret,
          backupCodes: mockBackupCodesHashed,
          isEnabled: false,
        },
      });

      expect(result).toEqual({
        secret: mockSecret,
        qrDataUri: mockQrDataUri,
        backupCodes: expect.any(Array), // generated by service
      });
      expect(result.backupCodes).toHaveLength(8);
    });

    it('should update existing secret record if not enabled', async () => {
      const existingRecord = {
        userId: mockUserId,
        secret: 'oldsecret',
        backupCodes: ['oldhash'],
        isEnabled: false,
        verifiedAt: null,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(existingRecord);
      mockPrismaService.twoFactorSecret.update.mockResolvedValue({
        ...existingRecord,
        secret: mockSecret,
        backupCodes: mockBackupCodesHashed,
      });

      await service.setup(mockUserId);

      expect(mockPrismaService.twoFactorSecret.update).toHaveBeenCalledWith({
        where: { userId: mockUserId },
        data: {
          secret: mockSecret,
          backupCodes: mockBackupCodesHashed,
          isEnabled: false,
          verifiedAt: null,
        },
      });
      expect(mockPrismaService.twoFactorSecret.create).not.toHaveBeenCalled();
    });

    it('should throw NotFoundException if user does not exist', async () => {
      mockPrismaService.user.findUnique.mockResolvedValue(null);

      await expect(service.setup(mockUserId)).rejects.toThrow(NotFoundException);
      expect(mockPrismaService.twoFactorSecret.findUnique).not.toHaveBeenCalled();
    });

    it('should throw BadRequestException if 2FA already enabled', async () => {
      const existingRecord = {
        userId: mockUserId,
        secret: 'oldsecret',
        backupCodes: ['oldhash'],
        isEnabled: true,
        verifiedAt: new Date(),
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(existingRecord);

      await expect(service.setup(mockUserId)).rejects.toThrow(BadRequestException);
      expect(mockPrismaService.twoFactorSecret.update).not.toHaveBeenCalled();
      expect(mockPrismaService.twoFactorSecret.create).not.toHaveBeenCalled();
    });
  });

  describe('verify', () => {
    it('should enable 2FA with valid code', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: false,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockPrismaService.twoFactorSecret.update.mockResolvedValue({
        ...secretRecord,
        isEnabled: true,
        verifiedAt: new Date(),
      });

      const result = await service.verify(mockUserId, '123456');

      expect(mockPrismaService.twoFactorSecret.findUnique).toHaveBeenCalledWith({
        where: { userId: mockUserId },
      });
      expect(mockAuthenticator.verify).toHaveBeenCalledWith({
        token: '123456',
        secret: mockSecret,
      });
      expect(mockPrismaService.twoFactorSecret.update).toHaveBeenCalledWith({
        where: { userId: mockUserId },
        data: {
          isEnabled: true,
          verifiedAt: expect.any(Date),
        },
      });
      expect(result).toBe(true);
    });

    it('should return false for invalid code', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: false,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockAuthenticator.verify.mockReturnValue(false);

      const result = await service.verify(mockUserId, 'wrongcode');

      expect(result).toBe(false);
      expect(mockPrismaService.twoFactorSecret.update).not.toHaveBeenCalled();
    });

    it('should throw BadRequestException if 2FA not set up', async () => {
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(null);

      await expect(service.verify(mockUserId, '123456')).rejects.toThrow(BadRequestException);
      expect(mockAuthenticator.verify).not.toHaveBeenCalled();
    });

    it('should throw BadRequestException if already enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      await expect(service.verify(mockUserId, '123456')).rejects.toThrow(BadRequestException);
      expect(mockAuthenticator.verify).not.toHaveBeenCalled();
    });
  });

  describe('validate', () => {
    it('should return true for valid code when 2FA enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockAuthenticator.verify.mockReturnValue(true);

      const result = await service.validate(mockUserId, '123456');

      expect(mockPrismaService.twoFactorSecret.findUnique).toHaveBeenCalledWith({
        where: { userId: mockUserId },
      });
      expect(mockAuthenticator.verify).toHaveBeenCalledWith({
        token: '123456',
        secret: mockSecret,
      });
      expect(result).toBe(true);
    });

    it('should return false for invalid code when 2FA enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockAuthenticator.verify.mockReturnValue(false);

      const result = await service.validate(mockUserId, 'wrongcode');

      expect(result).toBe(false);
    });

    it('should return true if 2FA not set up', async () => {
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(null);

      const result = await service.validate(mockUserId, 'anycode');

      expect(result).toBe(true);
    });

    it('should return true if 2FA not enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: false,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      const result = await service.validate(mockUserId, 'anycode');

      expect(result).toBe(true);
    });
  });

  describe('disable', () => {
    it('should disable 2FA with valid verification code', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockAuthenticator.verify.mockReturnValue(true);
      mockPrismaService.twoFactorSecret.update.mockResolvedValue({
        ...secretRecord,
        isEnabled: false,
        verifiedAt: null,
      });

      await service.disable(mockUserId, '123456');

      expect(mockPrismaService.twoFactorSecret.findUnique).toHaveBeenCalledTimes(2); // once in disable, once in verifyToken
      expect(mockAuthenticator.verify).toHaveBeenCalledWith({
        token: '123456',
        secret: mockSecret,
      });
      expect(mockPrismaService.twoFactorSecret.update).toHaveBeenCalledWith({
        where: { userId: mockUserId },
        data: {
          isEnabled: false,
          verifiedAt: null,
        },
      });
    });

    it('should throw BadRequestException if 2FA not set up', async () => {
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(null);

      await expect(service.disable(mockUserId, '123456')).rejects.toThrow(BadRequestException);
      expect(mockAuthenticator.verify).not.toHaveBeenCalled();
    });

    it('should throw BadRequestException if 2FA not enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: false,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      await expect(service.disable(mockUserId, '123456')).rejects.toThrow(BadRequestException);
      expect(mockAuthenticator.verify).not.toHaveBeenCalled();
    });

    it('should throw BadRequestException for invalid verification code', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockAuthenticator.verify.mockReturnValue(false);

      await expect(service.disable(mockUserId, 'wrongcode')).rejects.toThrow(BadRequestException);
      expect(mockPrismaService.twoFactorSecret.update).not.toHaveBeenCalled();
    });
  });

  describe('getStatus', () => {
    it('should return true if 2FA enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      const result = await service.getStatus(mockUserId);

      expect(mockPrismaService.twoFactorSecret.findUnique).toHaveBeenCalledWith({
        where: { userId: mockUserId },
      });
      expect(result).toBe(true);
    });

    it('should return false if 2FA not enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: false,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      const result = await service.getStatus(mockUserId);

      expect(result).toBe(false);
    });

    it('should return false if no secret record', async () => {
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(null);

      const result = await service.getStatus(mockUserId);

      expect(result).toBe(false);
    });
  });

  describe('useBackupCode', () => {
    it('should accept valid backup code and remove it', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
        backupCodes: mockBackupCodesHashed,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);
      mockPrismaService.twoFactorSecret.update.mockResolvedValue({
        ...secretRecord,
        backupCodes: mockBackupCodesHashed.slice(1),
      });

      // Mock hashBackupCode (private method) by spying on service instance
      const hashSpy = jest.spyOn(service as any, 'hashBackupCode');
      hashSpy.mockReturnValue(mockBackupCodesHashed[0]);

      const result = await service.useBackupCode(mockUserId, 'BACKUP001');

      expect(mockPrismaService.twoFactorSecret.findUnique).toHaveBeenCalledWith({
        where: { userId: mockUserId },
      });
      expect(hashSpy).toHaveBeenCalledWith('BACKUP001');
      expect(mockPrismaService.twoFactorSecret.update).toHaveBeenCalledWith({
        where: { userId: mockUserId },
        data: {
          backupCodes: mockBackupCodesHashed.slice(1),
        },
      });
      expect(result).toBe(true);
      hashSpy.mockRestore();
    });

    it('should return false for invalid backup code', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: true,
        backupCodes: mockBackupCodesHashed,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      const hashSpy = jest.spyOn(service as any, 'hashBackupCode');
      hashSpy.mockReturnValue('wronghash');

      const result = await service.useBackupCode(mockUserId, 'INVALID');

      expect(result).toBe(false);
      expect(mockPrismaService.twoFactorSecret.update).not.toHaveBeenCalled();
      hashSpy.mockRestore();
    });

    it('should throw BadRequestException if 2FA not enabled', async () => {
      const secretRecord = {
        userId: mockUserId,
        secret: mockSecret,
        isEnabled: false,
        backupCodes: mockBackupCodesHashed,
      };
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(secretRecord);

      await expect(service.useBackupCode(mockUserId, 'BACKUP001')).rejects.toThrow(BadRequestException);
      expect(mockPrismaService.twoFactorSecret.update).not.toHaveBeenCalled();
    });

    it('should throw BadRequestException if no secret record', async () => {
      mockPrismaService.twoFactorSecret.findUnique.mockResolvedValue(null);

      await expect(service.useBackupCode(mockUserId, 'BACKUP001')).rejects.toThrow(BadRequestException);
    });
  });

  // Edge cases and private method tests (optional)
  describe('private methods', () => {
    describe('generateBackupCodes', () => {
      it('should generate correct number of codes', () => {
        const codes = (service as any).generateBackupCodes(5);
        expect(codes).toHaveLength(5);
        codes.forEach(code => {
          expect(code).toMatch(/^[A-Z0-9]{10}$/);
        });
      });
    });

    describe('hashBackupCode', () => {
      it('should produce consistent SHA-256 hash', () => {
        const hash = (service as any).hashBackupCode('BACKUP001');
        expect(hash).toMatch(/^[a-f0-9]{64}$/); // SHA-256 hex length
      });
    });
  });
});