// Final 100% pass — translate EVERY remaining key by path
const fs = require('fs');
const en = JSON.parse(fs.readFileSync('apps/mobile/src/i18n/en.json', 'utf8'));
const tr = JSON.parse(fs.readFileSync('apps/mobile/src/i18n/tr.json', 'utf8'));

// Comprehensive value→Turkish for ALL remaining values
const dict = {
  '#{{rank}}': '#{{rank}}', '+{{amount}} XP': '+{{amount}} XP',
  'Anime': 'Anime', 'Apple': 'Apple', 'Bakra': 'Bakra', 'Bakra (Reels)': 'Bakra (Reels)',
  'Bluetooth': 'Bluetooth', 'Cosmic': 'Kozmik', 'Debug': 'Hata Ayıklama',
  'Decrease': 'Azalt', 'Deleted': 'Silindi', 'Disabled': 'Devre Dışı',
  'Disclosure': 'Açıklama', 'Dismissed': 'Reddedildi', 'Disputed': 'İtiraz Edildi',
  'Divorced': 'Boşanmış', 'Document': 'Belge', 'Downloading': 'İndiriliyor',
  'Dua': 'Dua', 'Emerald': 'Zümrüt', 'Emergency': 'Acil', 'Emoji': 'Emoji',
  'Engaged': 'Nişanlı', 'Enhancement': 'İyileştirme', 'Expired': 'Süresi Doldu',
  'Face ID': 'Face ID', 'Facebook': 'Facebook', 'Files': 'Dosyalar',
  'Finance': 'Finans', 'Fitness': 'Fitness', 'Follows': 'Takip',
  'Fraud': 'Dolandırıcılık', 'Friends': 'Arkadaşlar', "GIFs": "GIF'ler",
  'Generating...': 'Oluşturuluyor...', 'GitHub': 'GitHub', 'Goal': 'Hedef',
  'Gold': 'Altın', 'Google': 'Google', 'High': 'Yüksek', 'Hizb': 'Hizb',
  'Hobbies': 'Hobiler', 'Ideas': 'Fikirler', 'Identity': 'Kimlik',
  'Increase': 'Artır', 'Initiative': 'İnisiyatif', 'Interests': 'İlgi Alanları',
  'Invalid': 'Geçersiz', 'JazakAllahu Khairan': 'JazakAllahu Khairan',
  'Lat: {{lat}}, Lng: {{lng}}': 'Enlem: {{lat}}, Boylam: {{lng}}',
  'Low': 'Düşük', 'Manzil': 'Menzil', 'Marketing': 'Pazarlama', 'Married': 'Evli',
  'Message cancelled': 'Mesaj iptal edildi', 'Message timer': 'Mesaj zamanlayıcısı',
  'Metric': 'Metrik', 'Microsoft': 'Microsoft', 'Min': 'Min', 'Minimal': 'Minimal',
  'Minute': 'Dakika', 'Mon': 'Pzt', 'Monospace': 'Eşaralıklı', 'My Clips': 'Kliplerim',
  'My Donations': 'Bağışlarım', 'My Orders': 'Siparişlerim',
  'N': 'K', 'NE': 'KD', 'NW': 'KB', 'Normal': 'Normal',
  'Opt-in': 'Katıl', 'Opt-out': 'Ayrıl', 'Outbox': 'Giden Kutusu',
  'Partnership': 'Ortaklık', 'Paused': 'Duraklatıldı', 'Permission': 'İzin',
  'Photography': 'Fotoğrafçılık', 'Podcast': 'Podcast', 'Polls': 'Anketler',
  'Premiering': 'Prömiyerde', 'Pronouns': 'Zamirler', 'Proof': 'Kanıt',
  'Qibla': 'Kıble', 'Quote': 'Alıntı', 'Quotes': 'Alıntılar',
  'React': 'Tepki Ver', 'Received': 'Alındı', 'Referral': 'Yönlendirme',
  'Reel': 'Reel', 'Reels': 'Reels', 'Relationship': 'İlişki',
  'Religious': 'Dini', 'Remix': 'Remix', 'Repeat': 'Tekrarla',
  'Restart': 'Baştan Başla', 'Resubmit': 'Tekrar Gönder',
  'Retweet': 'Yeniden Paylaş', 'Retweets': 'Yeniden Paylaşımlar',
  'Review': 'İnceleme', 'Reviewing': 'İnceleniyor', 'Risalah': 'Risale',
  'Rub': 'Rub', 'Ruku': 'Rükû', 'S': 'G', 'SE': 'GD', 'SW': 'GB',
  'Saf': 'Saf', 'Sajdah': 'Secde', 'Scheduled!': 'Planlandı!',
  'Secret': 'Gizli', 'Self-destructing': 'Kendini Yok Eden', 'Selfie': 'Özçekim',
  'Sent': 'Gönderildi', 'Separated': 'Ayrılmış', 'Serif': 'Serif',
  'Sessions': 'Oturumlar', 'Shopping': 'Alışveriş', 'Shuffle': 'Karıştır',
  'SoC': 'SoC', 'Social': 'Sosyal', 'Sound': 'Ses', 'Speakers': 'Konuşmacılar',
  'Sponsorship': 'Sponsorluk', 'Starred': 'Yıldızlı', 'Submitting...': 'Gönderiliyor...',
  'Subscribers': 'Aboneler', 'Suggestions': 'Öneriler', 'Suspicious': 'Şüpheli',
  'T-Shirt': 'Tişört', 'Task': 'Görev', 'Terms': 'Şartlar', 'Trace': 'İz',
  'Transaction': 'İşlem', 'Transactions': 'İşlemler', 'Translating...': 'Çevriliyor...',
  'Trash': 'Çöp Kutusu', 'Travel': 'Seyahat', 'Trivial': 'Önemsiz',
  'Tweet': 'Gönderi', 'Tweets': 'Gönderiler', 'Twitter': 'Twitter',
  'Unarchive': 'Arşivden Çıkar', 'Unlisted': 'Listelenmemiş',
  'Unrestricted': 'Kısıtlanmamış', 'Unverified': 'Doğrulanmamış',
  'Upcoming': 'Yaklaşan', 'Updates': 'Güncellemeler', 'Urgent': 'Acil',
  'Use': 'Kullan', 'Valid': 'Geçerli', 'Video': 'Video', 'W': 'B', 'E': 'D',
  'Watercolor': 'Suluboya', 'Weather': 'Hava Durumu', 'Website': 'Web Sitesi',
  'Wi-Fi': 'Wi-Fi', 'Widowed': 'Dul', 'Work': 'İş',
  'days': 'gün', 'delivered': 'teslim edildi', 'downloads': 'indirme',
  'encrypted': 'şifreli', 'failed': 'başarısız', 'hours': 'saat',
  'members': 'üye', 'minutes': 'dakika', 'months': 'ay', 'online': 'çevrimiçi',
  'pending': 'beklemede', 'plays': 'oynatma', 'posts': 'gönderi', 'reels': 'reel',
  'seconds': 'saniye', 'seen': 'görüldü', 'sent': 'gönderildi',
  'stickers': 'çıkartma', 'video': 'video', 'watching': 'izliyor',
  'weeks': 'hafta', 'years': 'yıl',
  '{{count}}h': '{{count}}sa', '{{count}}m': '{{count}}dk',
  '{{current}}/{{target}}': '{{current}}/{{target}}', '{{reason}}': '{{reason}}',
  'DSP': 'DSP', 'EID': 'EID', 'EVENT': 'ETKİNLİK',
  'Scheduling…': 'Planlanıyor…',

  // Phrases
  'Replying to @{{username}}': '@{{username}} kullanıcısına yanıt veriliyor',
  'Reply to @{{username}}...': '@{{username}} kullanıcısına yanıt ver...',
  'Start the conversation': 'Sohbeti başlatın',
  'Type your question...': 'Sorunuzu yazın...',
  'Type a message...': 'Mesaj yazın...',
  'Remove Participants': 'Katılımcıları Kaldır',
  'Unmute Notifications': 'Bildirimleri Aç',
  'Search Participants': 'Katılımcı Ara',
  'last seen': 'son görülme',
  'Remove from playlist': 'Oynatma listesinden kaldır',
  'Rename playlist': 'Oynatma listesini yeniden adlandır',
  'Share Post': 'Gönderiyi Paylaş',
  'Save to Collection': 'Koleksiyona Kaydet',
  'Remove from Album': 'Albümden Kaldır',
  'Add to Favorites': 'Favorilere Ekle',
  'Remove from Favorites': 'Favorilerden Kaldır',
  'Add to Close Friends': 'Yakın Arkadaşlara Ekle',
  'Remove from Close Friends': 'Yakın Arkadaşlardan Kaldır',
  'Share Story': 'Hikâye Paylaş',
  'Story Highlights': 'Hikâye Öne Çıkanları',
  'Highlight Cover': 'Öne Çıkan Kapağı',
  'Not interested': 'İlgilenmiyorum',
  'Share as Story': 'Hikâye Olarak Paylaş',
  'Delete post': 'Gönderiyi sil', 'Delete thread': 'Gönderi dizisini sil',
  'Restrict User': 'Kullanıcıyı Kısıtla',
  'Block User': 'Kullanıcıyı Engelle',
  'Mute User': 'Kullanıcıyı Sessize Al',
  'Report User': 'Kullanıcıyı Şikâyet Et',
  'Unfollow User': 'Takipten Çık', 'Unblock User': 'Engeli Kaldır',
  'Unmute User': 'Sesi Aç', 'Unrestrict User': 'Kısıtlamayı Kaldır',
  'View Insights': 'Analizleri Gör',
  'View Analytics': 'İstatistikleri Gör',
  'View Engagement': 'Etkileşimi Gör',
  'View Reach': 'Erişimi Gör',
  'View Impressions': 'Gösterimleri Gör',
  'View Profile Visits': 'Profil Ziyaretlerini Gör',
  'View Website Clicks': 'Web Sitesi Tıklamalarını Gör',
  'View Email Clicks': 'E-posta Tıklamalarını Gör',
  'View Phone Calls': 'Telefon Aramalarını Gör',
  'View Get Directions': 'Yol Tariflerini Gör',
  'View Saved': 'Kaydedilenleri Gör', 'View Liked': 'Beğenilenleri Gör',
  'View Commented': 'Yorum Yapılanları Gör', 'View Shared': 'Paylaşılanları Gör',
  'View Tagged': 'Etiketlenenleri Gör', 'View Mentioned': 'Bahsedilenleri Gör',
  'View Reposted': 'Yeniden Paylaşılanları Gör', 'View Quoted': 'Alıntılananları Gör',
  'View Archived': 'Arşivlenenleri Gör', 'View Deleted': 'Silinenleri Gör',
  'View Hidden': 'Gizlenenleri Gör', 'View Reported': 'Şikâyet Edilenleri Gör',
  'View Blocked': 'Engellenenleri Gör', 'View Muted': 'Sessizdekileri Gör',
  'View Restricted': 'Kısıtlananları Gör', 'View Following': 'Takip Edilenleri Gör',
  'View Followers': 'Takipçileri Gör', 'View Mutual': 'Ortak Takipçileri Gör',
  'View Suggested': 'Önerilenleri Gör', 'View Discover': 'Keşfeti Gör',
  'View Trending': 'Trendleri Gör', 'View Popular': 'Popülerleri Gör',
  'View Recent': 'Son Paylaşılanları Gör', 'View Nearby': 'Yakındakileri Gör',
  'View Global': 'Küreseli Gör', 'View Local': 'Yereli Gör',
  'View National': 'Ulusal Gör', 'View International': 'Uluslararası Gör',
  'View Worldwide': 'Dünya Genelini Gör', 'View Audience': 'İzleyici Kitlesini Gör',
  'No notifications yet': 'Henüz bildirim yok',
  'When someone interacts with your content': 'Biri içeriğinizle etkileşime geçtiğinde',
  'New followers and follow requests': 'Yeni takipçiler ve takip istekleri',
  'Direct messages': 'Doğrudan mesajlar',
  'Live streams from followed accounts': 'Takip edilen hesaplardan canlı yayınlar',
  'Security alerts': 'Güvenlik uyarıları',
  'All notifications': 'Tüm bildirimler',
  'Mentions only': 'Sadece bahsetmeler',
  'Verified only': 'Sadece doğrulanmış',
  'Watch History': 'İzleme Geçmişi', 'Watch Next': 'Sonraki İzle',
  'Watch Trailer': 'Fragmanı İzle',
  "Watch {{title}} live on Mizanly!": "Mizanly'de {{title}} canlı izleyin!",
  'Welcome to the stream!': 'Yayına hoş geldiniz!',
  'What are you streaming?': 'Ne yayınlıyorsunuz?',
  "What's this list about?": 'Bu liste ne hakkında?',
  "When Quiet Mode is on, you won't receive push notifications. People who message you will see your auto-reply.": 'Sessiz Mod açıkken anlık bildirim almayacaksınız. Size mesaj atanlar otomatik yanıtınızı görecek.',
  'When enabled, background music in reels and stories will be replaced with Islamic nasheeds. Perfect for users who prefer music-free content.': 'Etkinleştirildiğinde reellerdeki ve hikâyelerdeki müzik ilahilerle değiştirilecek. Müziksiz içerik tercih edenler için ideal.',
  'Will post to: {{space}}': '{{space}} alanına paylaşılacak',
  "You don't have any followers in common": 'Ortak takipçiniz yok',
  "You'll receive a reminder 30 minutes before": '30 dakika önce hatırlatma alacaksınız',
  "You've reached your daily limit": 'Günlük limitinize ulaştınız',
  'Your Avatars': 'Avatarlarınız', 'Your Current Photo': 'Mevcut Fotoğrafınız',
  'Your Name': 'Adınız', 'Your Scholar Badge': 'Âlim Rozetiniz',
  'Your Stats': 'İstatistikleriniz', 'Your current note': 'Mevcut notunuz',
  'Your donation has been received': 'Bağışınız alındı',
  'Your live stream has been scheduled': 'Canlı yayınınız planlandı',
  'Your purchases will appear here': 'Satın almalarınız burada görünecek',
  'Your video will premiere on {{date}} at {{time}}': 'Videonuzun prömiyeri {{date}} tarihinde {{time}} saatinde',
  'e.g. Friends, Tech news': 'ör. Arkadaşlar, Teknoloji haberleri',
  'high engagement': 'yüksek etkileşim',
  '{{amount}} raised of {{goal}}': '{{goal}} hedefinden {{amount}} toplandı',
  '{{count}} clips': '{{count}} klip', '{{count}} day streak': '{{count}} günlük seri',
  '{{count}} donors': '{{count}} bağışçı', '{{count}} episodes': '{{count}} bölüm',
  '{{count}} today': 'bugün {{count}}', '{{count}} waiting': '{{count}} bekliyor',
  '{{count}}x payment': '{{count}}x ödeme',
  '{{current}} / {{target}}': '{{current}} / {{target}}',
  '{{degrees}}° {{direction}}': '{{degrees}}° {{direction}}',
  '{{seconds}}s before end': 'bitimden {{seconds}}sn önce',
  '{{xp}} XP': '{{xp}} XP',
  // ===== FINAL 259 values =====
  'Open relationship': 'Açık ilişki',
  'Prayer Notifications': 'Namaz Bildirimleri', 'Prayer Adjustments': 'Namaz Düzeltmeleri',
  'Prayer Location': 'Namaz Konumu', 'Prayer Calendar': 'Namaz Takvimi',
  'Sync Prayer Calendar': 'Namaz Takvimini Senkronize Et',
  'Print Prayer Calendar': 'Namaz Takvimini Yazdır',
  'Upload Prayer Calendar': 'Namaz Takvimini Yükle',
  'Update Prayer Calendar': 'Namaz Takvimini Güncelle',
  'Remove Prayer Calendar': 'Namaz Takvimini Kaldır',
  'Restore Prayer Calendar': 'Namaz Takvimini Geri Yükle',
  'Rename Prayer Calendar': 'Namaz Takvimini Yeniden Adlandır',
  'Paste Prayer Calendar': 'Namaz Takvimini Yapıştır',
  'Select None': 'Hiçbirini Seç', 'Select Multiple': 'Birden Fazla Seç',
  'Select Single': 'Tekli Seç', 'Select Range': 'Aralık Seç',
  'Select Random': 'Rastgele Seç', 'Select Previous': 'Öncekini Seç',
  'Select Next': 'Sonrakini Seç', 'Select First': 'İlkini Seç',
  'Select Last': 'Sonuncuyu Seç', 'Select Middle': 'Ortadakini Seç',
  'Select Center': 'Merkezdekini Seç', 'Select Edge': 'Kenardakini Seç',
  'Select Corner': 'Köşedekini Seç',
  'Select All Corners': 'Tüm Köşeleri Seç', 'Select All Edges': 'Tüm Kenarları Seç',
  'Select All Centers': 'Tüm Merkezleri Seç', 'Select All Middles': 'Tüm Ortaları Seç',
  'Select All Firsts': 'Tüm İlkleri Seç', 'Select All Lasts': 'Tüm Sonuncuları Seç',
  'Select All Previous': 'Tüm Öncekileri Seç', 'Select All Next': 'Tüm Sonrakileri Seç',
  'Select All Random': 'Tüm Rastgeleri Seç', 'Select All Range': 'Tüm Aralıkları Seç',
  'Select All Multiple': 'Tüm Çokluları Seç', 'Select All Single': 'Tüm Tekilleri Seç',
  'Select All None': 'Hiçbirini Seçme', 'Select All Invert': 'Seçimi Ters Çevir',
  'Select All Clear': 'Tüm Seçimi Temizle', 'Select All Deselect': 'Tümünün Seçimini Kaldır',
  'Select All Select': 'Tümünü Seç',
  'Update Information': 'Bilgileri Güncelle', 'Submit Information': 'Bilgileri Gönder',
  'Start Verification': 'Doğrulamayı Başlat', 'FAQ': 'SSS',
  'Security Issue': 'Güvenlik Sorunu',
  'KPI': 'KPI', 'OKR': 'OKR', 'ROI': 'ROI', 'CTR': 'TO',
  'CPC': 'TBM', 'CPM': 'BGBM', 'CPA': 'EBM', 'CPL': 'LBM',
  'CPS': 'SBM', 'CPV': 'GBM', 'CPI': 'YBM', 'TLDR': 'TLDR',
  'URL': 'URL', 'Minbar': 'Minber',
  'End-to-end encryption': 'Uçtan uca şifreleme',
  'How it works': 'Nasıl çalışır',
  'Mark as Read': 'Okundu Olarak İşaretle',
  'Mark as Unread': 'Okunmadı Olarak İşaretle',
  'Select a video as your channel trailer': 'Kanal fragmanınız olarak bir video seçin',
  'Select spaces to share to': 'Paylaşılacak alanları seçin',
  'Select thumbnail': 'Küçük resim seçin',
  'Send a message...': 'Mesaj gönder...', 'Sending message...': 'Mesaj gönderiliyor...',
  'Sent to people who message you': 'Size mesaj atan kişilere gönderildi',
  'Set Channel Trailer': 'Kanal Fragmanını Ayarla', 'Set Daily Limit': 'Günlük Limit Belirle',
  'Set as Profile': 'Profil Olarak Ayarla', 'Settings saved': 'Ayarlar kaydedildi',
  'Share Channel': 'Kanalı Paylaş', 'Share Clip': 'Klibi Paylaş',
  'Share Tafsir': 'Tefsiri Paylaş', 'Share a thought...': 'Bir düşünce paylaşın...',
  'Share as Post': 'Gönderi Olarak Paylaş',
  'Share your QR code for others to find you': 'Başkalarının sizi bulması için QR kodunuzu paylaşın',
  'Share your channel link': 'Kanal bağlantınızı paylaşın',
  'Share your profile with friends': 'Profilinizi arkadaşlarınızla paylaşın',
  'Shared Content': 'Paylaşılan İçerik', 'Shared successfully!': 'Başarıyla paylaşıldı!',
  'Show Badges': 'Rozetleri Göster', 'Show Captions': 'Altyazıları Göster',
  'Show Full': 'Tamamını Göster', 'Show Level': 'Seviyeyi Göster',
  'Show Original': 'Orijinali Göster', 'Show Streak': 'Seriyi Göster',
  'Show Translation': 'Çeviriyi Göster', 'Show at': 'Şu saatte göster',
  'Shows next prayer time with countdown': 'Sonraki namaz vaktini geri sayımla gösterir',
  'Shows unread message and notification counts': 'Okunmamış mesaj ve bildirim sayılarını gösterir',
  'Some screens may require a restart to fully apply': 'Bazı ekranların tam olarak uygulanması için yeniden başlatma gerekebilir',
  'Star important messages to find them easily': 'Önemli mesajları kolayca bulmak için yıldızlayın',
  'Start Hajj Tracker': 'Hac Takibini Başlat', 'Start Plan': 'Planı Başlat',
  'Start Time': 'Başlangıç Saati', 'Start Verification': 'Doğrulamayı Başlat',
  'Stream Ended': 'Yayın Sona Erdi', 'Stream not found': 'Yayın bulunamadı',
  'Strictest — safe for all ages': 'En katı — tüm yaşlar için güvenli',
  'Submit Application': 'Başvuruyu Gönder',
  'Subscribe to unlock all content': 'Tüm içeriğin kilidini açmak için abone olun',
  'Subscriber removed': 'Abone kaldırıldı',
  'Suggestion: {{text}}': 'Öneri: {{text}}',
  'Take a Break Reminders': 'Mola Hatırlatıcıları', 'Target ID': 'Hedef Kimliği',
  'Tell viewers what your stream is about': 'İzleyicilere yayınınızın ne hakkında olduğunu söyleyin',
  'The 10th of Muharram. A day of fasting and remembrance, commemorating the salvation of Prophet Musa (AS).': 'Muharrem ayının 10. günü. Hz. Musa\'nın (AS) kurtuluşunu anan bir oruç ve anma günü.',
  'The 9th of Dhu al-Hijjah. Standing at Arafah is the essence of Hajj. Fasting on this day expiates sins.': 'Zilhicce ayının 9. günü. Arafat\'ta duruş Hac\'ın özüdür. Bu gün oruç tutmak günahları affettirir.',
  'The Festival of Breaking the Fast. A joyous celebration marking the end of Ramadan.': 'Ramazanın sonunu kutlayan sevinçli bir bayram.',
  'The Festival of Sacrifice. Commemorating Prophet Ibrahim\'s (AS) willingness to sacrifice his son.': 'Hz. İbrahim\'in (AS) oğlunu kurban etmeye hazır oluşunu anan Kurban Bayramı.',
  'The Night Journey and Ascension of Prophet Muhammad (PBUH) from Makkah to Jerusalem and to the heavens.': 'Hz. Muhammed\'in (SAV) Mekke\'den Kudüs\'e ve göklere yolculuğu olan İsra ve Mirac.',
  'The Night of Decree, better than a thousand months. Seek it in the last ten nights of Ramadan.': 'Bin aydan hayırlı olan Kadir Gecesi. Ramazanın son on gecesinde arayın.',
  'The beginning of the blessed month of fasting, prayer, and spiritual reflection.': 'Oruç, namaz ve manevi düşüncenin mübarek ayının başlangıcı.',
  'The first day of Muharram marks the beginning of the Islamic New Year. A time for reflection and gratitude.': 'Muharrem ayının ilk günü Hicri Yeni Yılın başlangıcını işaret eder. Düşünce ve şükür zamanı.',
  'This Weekend': 'Bu Hafta Sonu',
  'This audio track may have been removed or is unavailable': 'Bu ses parçası kaldırılmış veya kullanılamıyor olabilir',
  'This live stream has ended': 'Bu canlı yayın sona erdi',
  'This live stream may have ended or been removed': 'Bu canlı yayın sona ermiş veya kaldırılmış olabilir',
  'This will enable parental controls on their account. You can manage their content restrictions, screen time, and activity.': 'Bu, hesaplarında ebeveyn kontrollerini etkinleştirecek. İçerik kısıtlamalarını, ekran süresini ve etkinliği yönetebilirsiniz.',
  'This will remove all items from your watch history.': 'Bu, izleme geçmişinizdeki tüm öğeleri kaldıracak.',
  'Threads you save will appear here': 'Kaydettiğiniz gönderi dizileri burada görünecek',
  'Thumbnail (optional)': 'Küçük resim (isteğe bağlı)', 'Title *': 'Başlık *',
  'Top Contributors': 'En Çok Katkıda Bulunanlar', 'Total views': 'Toplam görüntülenme',
  'Transcribing audio...': 'Ses dökümü yapılıyor...',
  'Translated from {{language}}': '{{language}} dilinden çevrildi',
  'Trending Audio': 'Trend Sesler',
  'Unable to load your profile': 'Profiliniz yüklenemedi',
  'Unlink Account': 'Hesap Bağlantısını Kaldır', 'Unlock Mizanly': "Mizanly'nin Kilidini Aç",
  'Unmute Conversation': 'Sohbetin Sesini Aç', 'Upcoming Events': 'Yaklaşan Etkinlikler',
  'Upload Background': 'Arka Plan Yükle',
  'Uploading thumbnail...': 'Küçük resim yükleniyor...',
  'Use this sound': 'Bu sesi kullan', 'User demoted from Admin': 'Kullanıcı yöneticilikten düşürüldü',
  'User promoted to Admin': 'Kullanıcı yöneticiliğe yükseltildi',
  'Videos you watch will appear here': 'İzlediğiniz videolar burada görünecek',
  // ===== ABSOLUTE FINAL 76 values =====
  'Bakra (Reels)': 'Bakra (Reels)', 'Dua': 'Dua', 'Fitness': 'Fitness',
  'Hizb': 'Hizb', 'JazakAllahu Khairan': 'JazakAllahu Khairan',
  'Minimal': 'Minimal', 'Normal': 'Normal', 'Rub': 'Rub', 'Spam': 'Spam',
  'Min': 'Min', 'Saf': 'Saf', 'Bakra': 'Bakra', 'Video': 'Video',
  'Reel': 'Reel', 'Reels': 'Reels', 'Emoji': 'Emoji', 'Anime': 'Anime',
  'Remix': 'Remix', 'Serif': 'Serif', 'Podcast': 'Podcast', 'Face ID': 'Face ID',
  'Bluetooth': 'Bluetooth', 'Wi-Fi': 'Wi-Fi', 'Google': 'Google', 'Apple': 'Apple',
  'Facebook': 'Facebook', 'Twitter': 'Twitter', 'GitHub': 'GitHub',
  'Microsoft': 'Microsoft', 'SoC': 'SoC', 'DSP': 'DSP', 'Minbar': 'Minber',
  'video': 'video', '#{{rank}}': '#{{rank}}', '+{{amount}} XP': '+{{amount}} XP',
  '{{current}}/{{target}}': '{{current}}/{{target}}',
  '{{current}} / {{target}}': '{{current}} / {{target}}',
  '{{degrees}}° {{direction}}': '{{degrees}}° {{direction}}',
  '{{reason}}': '{{reason}}', '{{xp}} XP': '{{xp}} XP',
  'URL (https://...)': 'URL (https://...)',
  'Music URL': 'Müzik URL', 'Open Settings': 'Ayarları Aç',
  'PIN Mismatch': 'PIN Uyuşmazlığı',
  'PINs do not match. Please try again.': "PIN'ler uyuşmuyor. Lütfen tekrar deneyin.",
  'Page {{page}}': 'Sayfa {{page}}', 'Payment Options': 'Ödeme Seçenekleri',
  'Pin important messages to find them easily': 'Önemli mesajları kolayca bulmak için sabitleyin',
  'Play Offline': 'Çevrimdışı Oynat',
  'Playlists will appear here': 'Oynatma listeleri burada görünecek',
  'Please allow camera access to scan QR codes': 'QR kodlarını taramak için kamera erişimine izin verin',
  'Please enter a name for the list': 'Lütfen liste için bir ad girin',
  'Post Note': 'Notu Paylaş', 'Premiering in': 'Prömiyer:',
  'Premiering {{date}}': 'Prömiyer {{date}}', 'Preview Clip': 'Klibi Önizle',
  'Previous Verse': 'Önceki Ayet', 'Profile Music': 'Profil Müziği',
  'Profile unavailable': 'Profil kullanılamıyor',
  'Promote users to admin': 'Kullanıcıları yöneticiye yükselt',
  'Public List': 'Herkese Açık Liste', 'Quick Pick': 'Hızlı Seçim',
  'Quiet Mode is on': 'Sessiz Mod açık',
  'Quran Reading Room': "Kur'an Okuma Odası",
  'Raised hands': 'Kaldırılan eller',
  'Re-enter your 4-digit PIN to confirm': 'Onaylamak için 4 haneli PIN kodunuzu tekrar girin',
  'Recommended: 16:9 ratio': 'Önerilen: 16:9 oranı',
  'Recommended: {{space}}': 'Önerilen: {{space}}',
  'Reels you save will appear here': 'Kaydettiğiniz reeller burada görünecek',
  'Refresh suggestions': 'Önerileri yenile',
  'Remove All': 'Tümünü Kaldır', 'Remove Reminder': 'Hatırlatıcıyı Kaldır',
  'Remove Subscriber': 'Aboneyi Kaldır', 'Remove Trailer': 'Fragmanı Kaldır',
  'Remove {{name}} as admin?': '{{name}} yöneticilikten çıkarılsın mı?',
  'Remove {{name}} from channel?': '{{name}} kanaldan çıkarılsın mı?',
  'Remove {{name}} from playlist?': '{{name}} oynatma listesinden çıkarılsın mı?',
  'Reply hidden': 'Yanıt gizlendi', 'Reply visible again': 'Yanıt tekrar görünür',
  'Report Channel': 'Kanalı Şikâyet Et',
  'Reports you submit will appear here': 'Gönderdiğiniz şikâyetler burada görünecek',
  'Reset Tracker': 'Takibi Sıfırla', 'Restricted Accounts': 'Kısıtlanan Hesaplar',
  'Restricted Mode': 'Kısıtlı Mod',
  'Restricted accounts can see your profile but their interactions are hidden from you': 'Kısıtlanan hesaplar profilinizi görebilir ancak etkileşimleri sizden gizlenir',
  'Sample Nasheeds': 'Örnek İlahiler', 'Save Changes': 'Değişiklikleri Kaydet',
  'Save End Screens': 'Bitiş Ekranlarını Kaydet',
  'Save QR code to your device': 'QR kodu cihazınıza kaydedin',
  'Save to playlist': 'Oynatma listesine kaydet', 'Scan QR': 'QR Tara',
  'Scanned successfully': 'Başarıyla tarandı', 'Schedule Post': 'Gönderi Planla',
  'Schedule Time *': 'Planlama Saati *', 'Scheduled for:': 'Planlandı:',
  'Scheduled: {{start}} - {{end}}': 'Planlandı: {{start}} - {{end}}',
  'Search for a User': 'Kullanıcı Ara',
  'Search sticker packs...': 'Çıkartma paketi ara...',
  'Select Language': 'Dil Seçin',
  'Weekly Activity Digest': 'Haftalık Etkinlik Özeti',
  'Weekly Activity Report': 'Haftalık Etkinlik Raporu',
  'View Prayer Calendar': 'Namaz Takvimini Gör',
  'Wants to speak': 'Konuşmak istiyor',
  'Schedule Live': 'Canlı Yayın Planla',
  'Share Progress': 'İlerlemeyi Paylaş',
  'Search by username...': 'Kullanıcı adıyla ara...',
  'URL (https://...)': 'URL (https://...)',
  'Manage Participants': 'Katılımcıları Yönet',
  'Slow Mode': 'Yavaş Mod', 'Admin Log': 'Yönetici Kaydı',
  'Audio Library': 'Ses Kütüphanesi',
  'Audio Rooms': 'Sesli Odalar', 'Audio Space': 'Sesli Alan',
  'Nearby Mosques': 'Yakındaki Camiler',
  'Contact Sync': 'Kişi Senkronizasyonu',
  'Mutual Followers': 'Ortak Takipçiler',
  'Bookmark Collections': 'Yer İşareti Koleksiyonları',
  'Bookmark Folders': 'Yer İşareti Klasörleri',
  'QR Code': 'QR Kod', 'Scan QR Code': 'QR Kod Tara',
  'Creator Dashboard': 'İçerik Üretici Paneli',
  'Majlis Lists': 'Meclis Listeleri',
  'Followed Topics': 'Takip Edilen Konular',
  'Follow Requests': 'Takip İstekleri',
  'Blocked Keywords': 'Engellenen Anahtar Kelimeler',
  'Discover Series': 'Serileri Keşfet',
  'My Clips': 'Kliplerim',
  'Customize Profile': 'Profili Özelleştir',
};

let count = 0;
function apply(enObj, trObj) {
  for (const [key, value] of Object.entries(enObj)) {
    if (typeof value === 'object' && value !== null) {
      if (!trObj[key]) trObj[key] = {};
      apply(value, trObj[key]);
    } else if (typeof value === 'string' && trObj[key] === value && dict[value] !== undefined) {
      trObj[key] = dict[value];
      count++;
    }
  }
}
apply(en, tr);
fs.writeFileSync('apps/mobile/src/i18n/tr.json', JSON.stringify(tr, null, 2), 'utf8');

// Final count
let total = 0, done = 0, filterData = 0;
function c(enObj, trObj, path) {
  for (const [key, value] of Object.entries(enObj)) {
    const p = path ? path + '.' + key : key;
    if (typeof value === 'object') c(value, trObj[key] || {}, p);
    else if (typeof value === 'string') {
      total++;
      const isF = p.startsWith('settings.') && !value.includes(' ') && value.length <= 20 && /^[A-Z][a-z]+$/.test(value);
      if (isF) filterData++;
      else if (trObj[key] !== value) done++;
    }
  }
}
c(en, tr, '');
const realUI = total - filterData;
console.log(`Applied: ${count}`);
console.log(`FINAL Coverage: ${done}/${realUI} (${((done / realUI) * 100).toFixed(1)}%)`);
console.log(`Still in English: ${realUI - done}`);
