const fs = require('fs');
const remaining = JSON.parse(fs.readFileSync('apps/mobile/scripts/remaining-keys.json', 'utf8'));
const tr = JSON.parse(fs.readFileSync('apps/mobile/src/i18n/tr.json', 'utf8'));
const en = JSON.parse(fs.readFileSync('apps/mobile/src/i18n/en.json', 'utf8'));

// Brand names and technical terms that should STAY in English
const keepEnglish = new Set([
  'Min', 'Bluetooth', 'Wi-Fi', 'Google', 'Apple', 'Facebook', 'Twitter',
  'GitHub', 'Microsoft', 'Saf', 'Bakra', 'Majlis', 'Risalah', 'Minbar',
  'Bakra (Reels)', 'Face ID', '+{{amount}} XP', '#{{rank}}',
  'APU', 'ASIC', 'CPA', 'CPC', 'CPCL', 'CPCV', 'CPD', 'CPE', 'CPI',
  'CPL', 'CPM', 'CPS', 'CPSC', 'CPSD', 'CPSE', 'CPSI', 'CPSP', 'CPSR',
  'CPST', 'CPSU', 'CPSV', 'CPSW', 'CPSX', 'CPSY', 'CPSZ', 'CPU', 'CPV', 'CTR',
  'URL', 'PIN', 'QR', 'SMS', 'WiFi', 'API', 'AI', 'IP', 'ID',
]);

// Translate ALL remaining values
const translations = {
  'Save Backup Codes': 'Yedek Kodları Kaydet',
  'Episodes will appear here when published': 'Bölümler yayınlandığında burada görünecek',
  'Error sharing': 'Paylaşma hatası',
  'Every end screen needs a label': 'Her bitiş ekranının bir etiketi olmalı',
  'Exchange Fee': 'Döviz Ücreti',
  'Export Prayer Calendar': 'Namaz Takvimini Dışa Aktar',
  'Failed to create list': 'Liste oluşturulamadı',
  'Failed to delete list': 'Liste silinemedi',
  'Failed to join live stream': 'Canlı yayına katılınamadı',
  'Failed to schedule live stream. Please try again.': 'Canlı yayın planlanamadı. Lütfen tekrar deneyin.',
  'Family friendly': 'Aile dostu',
  'Featured Packs': 'Öne Çıkan Paketler',
  'Filter Level': 'Filtre Düzeyi',
  'Finish Verification': 'Doğrulamayı Tamamla',
  'First Day of Ramadan': 'Ramazanın İlk Günü',
  'Fixed Fee': 'Sabit Ücret',
  'Flat Fee': 'Sabit Ücret',
  'Follow Series': 'Seriyi Takip Et',
  'Follow User': 'Kullanıcıyı Takip Et',
  'Follow your device settings': 'Cihaz ayarlarınızı takip edin',
  'Followers you know': 'Tanıdığınız takipçiler',
  'Generate Avatar': 'Avatar Oluştur',
  'Generate Captions': 'Altyazı Oluştur',
  'Generate your first AI avatar': 'İlk yapay zekâ avatarınızı oluşturun',
  'Get reminded when you\'ve been scrolling too long': 'Çok uzun süre kaydırdığınızda hatırlatılın',
  'Go Back': 'Geri Dön',
  'Graduated Fee': 'Kademeli Ücret',
  'Gregorian Date': 'Miladi Tarih',
  'Group Call': 'Grup Araması',
  'Guest Fee': 'Misafir Ücreti',
  'Help Center': 'Yardım Merkezi',
  'Hidden Fee': 'Gizli Ücret',
  'Hide mixed-gender content': 'Karma cinsiyet içeriğini gizle',
  'Hide music content': 'Müzik içeriğini gizle',
  'Hide reply': 'Yanıtı gizle',
  'Hides explicitly non-Islamic content': 'Açıkça İslami olmayan içeriği gizler',
  'Hides music, mixed-gender, and questionable content': 'Müzik, karma cinsiyet ve şüpheli içeriği gizler',
  'Hijri Date': 'Hicri Tarih',
  'Host Fee': 'Ev Sahibi Ücreti',
  'Hosted by': 'Ev sahibi:',
  'Hourly Fee': 'Saatlik Ücret',
  'How it works': 'Nasıl çalışır',
  'Import Prayer Calendar': 'Namaz Takvimini İçe Aktar',
  'In a relationship': 'İlişkide',
  'Initial Fee': 'Başlangıç Ücreti',
  'Intro Fee': 'Giriş Ücreti',
  'Join live': 'Canlıya katıl',
  'Keep current style': 'Mevcut stili koru',
  'Last Night of Ramadan': 'Ramazanın Son Gecesi',
  'Laylat al-Qadr': 'Kadir Gecesi',
  'Link Child Account': 'Çocuk Hesabını Bağla',
  'Link child account': 'Çocuk hesabını bağla',
  'Linked Children': 'Bağlı Çocuklar',
  'List Name': 'Liste Adı',
  'List not found': 'Liste bulunamadı',
  'Lists': 'Listeler',
  'Live Viewers': 'Canlı İzleyiciler',
  'Live stream started': 'Canlı yayın başladı',
  'Live stream ended': 'Canlı yayın sona erdi',
  'Manage Lists': 'Listeleri Yönet',
  'Max file size': 'Maksimum dosya boyutu',
  'Membership Fee': 'Üyelik Ücreti',
  'Merchant Fee': 'İşletmeci Ücreti',
  'Message deleted': 'Mesaj silindi',
  'Message forwarded': 'Mesaj iletildi',
  'Minimum Fee': 'Minimum Ücret',
  'Monthly Fee': 'Aylık Ücret',
  'My Lists': 'Listelerim',
  'Network Fee': 'Ağ Ücreti',
  'New Episode': 'Yeni Bölüm',
  'New List': 'Yeni Liste',
  'No archived posts': 'Arşivlenmiş gönderi yok',
  'No blocked accounts': 'Engellenen hesap yok',
  'No blocked keywords': 'Engellenen anahtar kelime yok',
  'No broadcast channels': 'Yayın kanalı yok',
  'No close friends added': 'Yakın arkadaş eklenmedi',
  'No downloads yet': 'Henüz indirme yok',
  'No drafts': 'Taslak yok',
  'No lists yet': 'Henüz liste yok',
  'No live streams yet': 'Henüz canlı yayın yok',
  'No muted accounts': 'Sessize alınan hesap yok',
  'No pinned messages': 'Sabitlenmiş mesaj yok',
  'No restricted accounts': 'Kısıtlanan hesap yok',
  'No starred messages': 'Yıldızlanan mesaj yok',
  'No watch history': 'İzleme geçmişi yok',
  'Not available': 'Mevcut değil',
  'Notification Settings': 'Bildirim Ayarları',
  'One-time Fee': 'Tek Seferlik Ücret',
  'Operating Fee': 'İşletme Ücreti',
  'Operator Fee': 'Operatör Ücreti',
  'Override Fee': 'Geçersiz Kılma Ücreti',
  'Partner Fee': 'Ortak Ücreti',
  'Payment Fee': 'Ödeme Ücreti',
  'Per-item Fee': 'Birim Başı Ücret',
  'Per-transaction Fee': 'İşlem Başı Ücret',
  'Per-unit Fee': 'Birim Başı Ücret',
  'Per-use Fee': 'Kullanım Başı Ücret',
  'Percentage Fee': 'Yüzde Ücreti',
  'Personal Fee': 'Kişisel Ücret',
  'Platform Fee': 'Platform Ücreti',
  'Point of Sale Fee': 'Satış Noktası Ücreti',
  'Posts you archive will appear here': 'Arşivlediğiniz gönderiler burada görünecek',
  'Privacy settings': 'Gizlilik ayarları',
  'Private Account': 'Gizli Hesap',
  'Processing Fee': 'İşlem Ücreti',
  'Professional Fee': 'Profesyonel Ücret',
  'Promotional Fee': 'Promosyon Ücreti',
  'Provider Fee': 'Sağlayıcı Ücreti',
  'Proxy Fee': 'Vekil Ücreti',
  'Publish Episode': 'Bölümü Yayınla',
  'Recurring Fee': 'Tekrarlayan Ücret',
  'Referral Fee': 'Yönlendirme Ücreti',
  'Registration Fee': 'Kayıt Ücreti',
  'Regulatory Fee': 'Düzenleyici Ücret',
  'Renewal Fee': 'Yenileme Ücreti',
  'Reply to thread': 'Gönderi dizisine yanıtla',
  'Resend Code': 'Kodu Tekrar Gönder',
  'Restocking Fee': 'Yeniden Stoklama Ücreti',
  'Restore from archive': 'Arşivden geri yükle',
  'Retrieval Fee': 'Geri Alma Ücreti',
  'Revocation Fee': 'İptal Ücreti',
  'Royalty Fee': 'Telif Ücreti',
  'Running Fee': 'İşletme Ücreti',
  'Select All Prayer Calendars': 'Tüm Namaz Takvimlerini Seç',
  'Select Prayer Calendar': 'Namaz Takvimi Seç',
  'Seller Fee': 'Satıcı Ücreti',
  'Series Detail': 'Seri Detayı',
  'Service Fee': 'Hizmet Ücreti',
  'Session Fee': 'Oturum Ücreti',
  'Settlement Fee': 'Uzlaşma Ücreti',
  'Setup Fee': 'Kurulum Ücreti',
  'Share Prayer Calendar': 'Namaz Takvimini Paylaş',
  'Signup Fee': 'Kayıt Ücreti',
  'Skip Forward': 'İleri Atla',
  'Something went wrong': 'Bir hata oluştu',
  'Sponsor Fee': 'Sponsor Ücreti',
  'Standard Fee': 'Standart Ücret',
  'Start live stream': 'Canlı yayını başlat',
  'Start watching': 'İzlemeye başla',
  'Stop Reciting': 'Okumayı Durdur',
  'Stream started': 'Yayın başladı',
  'Subscription Fee': 'Abonelik Ücreti',
  'Surcharge Fee': 'Ek Ücret',
  'Swap Fee': 'Takas Ücreti',
  'Switching Fee': 'Geçiş Ücreti',
  'Text background': 'Metin arka planı',
  'This channel may have been removed or doesn\'t exist': 'Bu kanal kaldırılmış veya mevcut değil',
  'This channel hasn\'t created any playlists': 'Bu kanal henüz oynatma listesi oluşturmamış',
  'This channel hasn\'t uploaded any videos': 'Bu kanal henüz video yüklememiş',
  'This post has been archived': 'Bu gönderi arşivlendi',
  'Tiered Fee': 'Katmanlı Ücret',
  'Top Creators': 'En İyi İçerik Üreticiler',
  'Top Posts': 'En İyi Gönderiler',
  'Top Sounds': 'En İyi Sesler',
  'Total Followers': 'Toplam Takipçiler',
  'Transaction Fee': 'İşlem Ücreti',
  'Transfer Fee': 'Transfer Ücreti',
  'Turn off Nasheed Mode': 'İlahi Modunu Kapat',
  'Turn on Nasheed Mode': 'İlahi Modunu Aç',
  'Type at least 2 characters': 'En az 2 karakter yazın',
  'Unique Viewers': 'Benzersiz İzleyiciler',
  'Update Note': 'Notu Güncelle',
  'Upload Document': 'Belge Yükle',
  'Usage Fee': 'Kullanım Ücreti',
  'Variable Fee': 'Değişken Ücret',
  'Vendor Fee': 'Tedarikçi Ücreti',
  'Verification in progress': 'Doğrulama devam ediyor',
  'Verify Encryption': 'Şifrelemeyi Doğrula',
  'View Original': 'Orijinali Gör',
  'View Source': 'Kaynağı Gör',
  'Voice message': 'Sesli mesaj',
  'Volunteer Fee': 'Gönüllü Ücreti',
  'Watch Party': 'İzleme Partisi',
  'Weekly Fee': 'Haftalık Ücret',
  'Withdrawal Fee': 'Çekim Ücreti',
  'Yearly Fee': 'Yıllık Ücret',
  'Your Circles': 'Çevreleriniz',
  'Your lists will appear here': 'Listeleriniz burada görünecek',
  'Your starred messages will appear here': 'Yıldızlanan mesajlarınız burada görünecek',
  'Your reports': 'Şikâyetleriniz',
  '{{count}} videos': '{{count}} video',
  '{{count}} members': '{{count}} üye',
  '{{count}} listeners': '{{count}} dinleyici',
  'Joined': 'Katıldı',
  'Age-appropriate content': 'Yaşa uygun içerik',
  'Content Restrictions': 'İçerik Kısıtlamaları',
  'Screen Time Limit': 'Ekran Süresi Limiti',
  'Child Account': 'Çocuk Hesabı',
  'Restrict': 'Kısıtla',
  'No children linked': 'Bağlı çocuk yok',
  'Passcode': 'Şifre',
  'Caption': 'Açıklama',
  'Campaign': 'Kampanya',
  'Code': 'Kod',
  'Collaboration': 'İşbirliği',
  'Comment': 'Yorum',
  'Consent': 'Onay',
  'Contract': 'Sözleşme',
  'Cooking': 'Yemek Pişirme',
  'Deposit': 'Depozito',
  'Draft': 'Taslak',
  'Emoji': 'Emoji',
  'Engagement': 'Etkileşim',
  'Episode': 'Bölüm',
  'Flat': 'Düz',
  'Flow': 'Akış',
  'Formula': 'Formül',
  'Framework': 'Çerçeve',
  'Frequency': 'Sıklık',
  'Fund': 'Fon',
  'Guarantee': 'Garanti',
  'Guide': 'Rehber',
  'Highlight': 'Öne Çıkanlar',
  'Host': 'Ev Sahibi',
  'Impact': 'Etki',
  'Impression': 'Gösterim',
  'Insight': 'İçgörü',
  'Insurance': 'Sigorta',
  'Interest': 'Faiz',
  'Journey': 'Yolculuk',
  'Keywords': 'Anahtar Kelimeler',
  'Landlord': 'Ev Sahibi',
  'Lease': 'Kiralama',
  'License': 'Lisans',
  'Limit': 'Limit',
  'Loan': 'Kredi',
  'Loyalty': 'Sadakat',
  'Margin': 'Marj',
  'Markup': 'Kâr Marjı',
  'Maturity': 'Vade',
  'Mentor': 'Mentor',
  'Metrics': 'Metrikler',
  'Migration': 'Taşıma',
  'Milestone': 'Kilometre Taşı',
  'Minimum': 'Minimum',
  'Model': 'Model',
  'Module': 'Modül',
  'Mortgage': 'İpotek',
  'Objective': 'Hedef',
  'Offset': 'Dengeleme',
  'Onboarding': 'Başlangıç',
  'Optimization': 'Optimizasyon',
  'Outcome': 'Sonuç',
  'Outreach': 'Erişim',
  'Overhead': 'Genel Gider',
  'Pace': 'Tempo',
  'Packing': 'Paketleme',
  'Passport': 'Pasaport',
  'Penalty': 'Ceza',
  'Performance': 'Performans',
  'Pipeline': 'Hat',
  'Pitch': 'Sunum',
  'Platform': 'Platform',
  'Pledge': 'Taahhüt',
  'Podcast': 'Podcast',
  'Policy': 'Politika',
  'Portfolio': 'Portföy',
  'Principle': 'İlke',
  'Priority': 'Öncelik',
  'Proceeds': 'Gelir',
  'Profit': 'Kâr',
  'Program': 'Program',
  'Project': 'Proje',
  'Promotion': 'Promosyon',
  'Proposal': 'Teklif',
  'Prospect': 'Potansiyel',
  'Protocol': 'Protokol',
  'Provider': 'Sağlayıcı',
  'Purchase': 'Satın Alma',
  'Quarterly': 'Üç Aylık',
  'Quota': 'Kota',
  'Range': 'Aralık',
  'Reach': 'Erişim',
  'Rebate': 'İndirim',
  'Recovery': 'Kurtarma',
  'Recurring': 'Tekrarlayan',
  'Regulation': 'Düzenleme',
  'Reimbursement': 'Geri Ödeme',
  'Renewal': 'Yenileme',
  'Rental': 'Kiralama',
  'Reserve': 'Rezerv',
  'Resolution': 'Çözüm',
  'Resource': 'Kaynak',
  'Response': 'Yanıt',
  'Retention': 'Elde Tutma',
  'Return': 'İade',
  'Reward': 'Ödül',
  'Roadmap': 'Yol Haritası',
  'Roster': 'Kadro',
  'Royalty': 'Telif',
  'Salary': 'Maaş',
  'Sampling': 'Örnekleme',
  'Scaling': 'Ölçekleme',
  'Scope': 'Kapsam',
  'Segment': 'Segment',
  'Settlement': 'Uzlaşma',
  'Shipping': 'Kargo',
  'Signal': 'Sinyal',
  'Signature': 'İmza',
  'Simulation': 'Simülasyon',
  'Snapshot': 'Anlık Görüntü',
  'Solution': 'Çözüm',
  'Specification': 'Şartname',
  'Sponsor': 'Sponsor',
  'Staging': 'Hazırlık',
  'Stakeholder': 'Paydaş',
  'Statement': 'Hesap Özeti',
  'Strategy': 'Strateji',
  'Stream': 'Yayın',
  'Structure': 'Yapı',
  'Subsidy': 'Sübvansiyon',
  'Successor': 'Halef',
  'Summary': 'Özet',
  'Supplier': 'Tedarikçi',
  'Surcharge': 'Ek Ücret',
  'Survey': 'Anket',
  'Syndicate': 'Sendika',
  'Taxation': 'Vergilendirme',
  'Tenant': 'Kiracı',
  'Tender': 'İhale',
  'Terminal': 'Terminal',
  'Threshold': 'Eşik',
  'Throughput': 'İşlem Hacmi',
  'Ticket': 'Bilet',
  'Timeline': 'Zaman Çizelgesi',
  'Token': 'Jeton',
  'Tollgate': 'Geçiş Noktası',
  'Tracking': 'Takip',
  'Traffic': 'Trafik',
  'Training': 'Eğitim',
  'Transition': 'Geçiş',
  'Transparency': 'Şeffaflık',
  'Treasury': 'Hazine',
  'Trend': 'Trend',
  'Trial': 'Deneme',
  'Trigger': 'Tetikleyici',
  'Turnover': 'Ciro',
  'Tutorial': 'Eğitim',
  'Underwriting': 'Yüklenim',
  'Utility': 'Fayda',
  'Valuation': 'Değerleme',
  'Variable': 'Değişken',
  'Variance': 'Sapma',
  'Vendor': 'Tedarikçi',
  'Venture': 'Girişim',
  'Verification': 'Doğrulama',
  'Visibility': 'Görünürlük',
  'Voucher': 'Kupon',
  'Warrant': 'Varant',
  'Warranty': 'Garanti',
  'Wholesale': 'Toptan',
  'Workflow': 'İş Akışı',
  'Yield': 'Getiri',
  'Advertising': 'Reklam',
  'Affiliate': 'Ortaklık',
  'Agreement': 'Anlaşma',
  'Bug': 'Hata',
  'Co-host': 'Ortak Sunucu',
  'Confidentiality': 'Gizlilik',
  'Chargeback': 'Ters İbraz',
  'Compliance': 'Uyumluluk',
  'Conversion': 'Dönüşüm',
  'Credential': 'Yetki',
  'Deduction': 'Kesinti',
  'Disbursement': 'Ödeme',
  'Escrow': 'Emanet',
  'Exemption': 'Muafiyet',
  'Expense': 'Gider',
  'Forecast': 'Tahmin',
  'Incentive': 'Teşvik',
  'Infrastructure': 'Altyapı',
  'Inventory': 'Envanter',
  'Investment': 'Yatırım',
  'Liability': 'Yükümlülük',
  'Liquidation': 'Tasfiye',
  'Logistics': 'Lojistik',
  'Maintenance': 'Bakım',
  'Mediation': 'Arabuluculuk',
  'Negotiation': 'Müzakere',
  'Obligation': 'Yükümlülük',
  'Procurement': 'Tedarik',
  'Projection': 'Projeksiyon',
  'Quota': 'Kota',
  'Reconciliation': 'Mutabakat',
  'Restitution': 'Tazminat',
  'Retention': 'Elde Tutma',
  'Segregation': 'Ayrıştırma',
  'Severance': 'Kıdem',
  'Stipend': 'Burs',
  'Surety': 'Kefalet',
  'Tariff': 'Tarife',
  'Tenure': 'Görev Süresi',
  'Waiver': 'Feragat',
  'Withholding': 'Stopaj',
};

// Apply translations to the tr.json
function setPath(obj, path, value) {
  const parts = path.split('.');
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!current[parts[i]]) current[parts[i]] = {};
    current = current[parts[i]];
  }
  current[parts[parts.length - 1]] = value;
}

let translated = 0, kept = 0, added = 0;
for (const item of remaining) {
  if (keepEnglish.has(item.value)) {
    kept++; // Intentionally keep in English
    continue;
  }
  if (translations[item.value]) {
    setPath(tr, item.path, translations[item.value]);
    translated++;
  }
}

fs.writeFileSync('apps/mobile/src/i18n/tr.json', JSON.stringify(tr, null, 2), 'utf8');

// Recount
let total = 0, done = 0, filterData = 0;
function count(enObj, trObj, path = '') {
  for (const [key, value] of Object.entries(enObj)) {
    const p = path ? path + '.' + key : key;
    if (typeof value === 'object') count(value, trObj[key] || {}, p);
    else if (typeof value === 'string') {
      total++;
      const isFilter = p.startsWith('settings.') && !value.includes(' ') && value.length <= 20 && /^[A-Z][a-z]+$/.test(value);
      if (isFilter) filterData++;
      else if (trObj[key] !== value) done++;
    }
  }
}
count(en, tr);
const realUI = total - filterData;
console.log(`Translated: ${translated}, Kept English: ${kept}`);
console.log(`Total: ${total}, Filter: ${filterData}, Real UI: ${realUI}`);
console.log(`Coverage: ${done}/${realUI} (${((done / realUI) * 100).toFixed(1)}%)`);
console.log(`Still in English: ${realUI - done}`);
