const fs = require('fs');
const en = JSON.parse(fs.readFileSync('apps/mobile/src/i18n/en.json', 'utf8'));

// Path-based translations for ALL remaining untranslated keys
// Format: 'section.key': 'Turkish translation'
const pathTranslations = {
  // ===== TABS =====
  'tabs.profile': 'Profil',
  'tabs.events': 'Etkinlikler',
  'tabs.communities': 'Topluluklar',
  'tabs.create': 'Oluştur',
  'tabs.notifications': 'Bildirimler',
  'tabs.explore': 'Keşfet',
  'tabs.trending': 'Trend',

  // ===== SAF =====
  'saf.feed': 'Akış',
  'saf.stories': 'Hikâyeler',
  'saf.story': 'Hikâye',
  'saf.photo': 'Fotoğraf',
  'saf.video': 'Video',
  'saf.newPost': 'Yeni Gönderi',
  'saf.carousel': 'Galeri',
  'saf.gallery': 'Galeri',
  'saf.text': 'Metin',
  'saf.comments': 'Yorumlar',
  'saf.likes': 'Beğeniler',
  'saf.shares': 'Paylaşımlar',
  'saf.saves': 'Kaydedilenler',
  'saf.views': 'Görüntülenmeler',
  'saf.replyingTo': '@{{username}} kullanıcısına yanıt veriliyor',
  'saf.replyToUser': '@{{username}} kullanıcısına yanıt ver…',
  'saf.addComment': 'Yorum ekle…',
  'saf.startConversation': 'Sohbeti başlatın',
  'saf.firstToShare': 'Düşüncelerinizi ilk paylaşan siz olun',
  'saf.noComments': 'Henüz yorum yok',
  'saf.beFirstToComment': 'İlk yorumu yapan siz olun',
  'saf.questionPlaceholder': 'Sorunuzu yazın...',
  'saf.post': 'Gönderi',
  'saf.deleteCommentTitle': 'Yorum silinsin mi?',
  'saf.deleteCommentMessage': 'Bu yorum kalıcı olarak silinecek.',
  'saf.couldNotLoadContent': 'Bu içerik yüklenemedi',
  'saf.goBack': 'Geri Dön',
  'saf.emptyFeed.title': 'Akışınız boş',
  'saf.emptyFeed.subtitle': 'İçerik görmek için kişileri takip edin',
  'saf.following': 'Takip Edilenler',
  'saf.forYou': 'Senin İçin',

  // ===== BAKRA =====
  'bakra.hashtags': 'Hashtagler',
  'bakra.sounds': 'Sesler',
  'bakra.effects': 'Efektler',
  'bakra.filters': 'Filtreler',
  'bakra.duet': 'Düet',
  'bakra.stitch': 'Birleştir',
  'bakra.trending': 'Trend',
  'bakra.originalAudio': 'Orijinal ses',
  'bakra.unknown': 'Bilinmiyor',
  'bakra.notInterested': 'İlgilenmiyorum',
  'bakra.notInterestedAlert.title': 'Anladık',
  'bakra.notInterestedAlert.message': 'Benzer içerikleri daha az gösterecğiz',
  'bakra.linkCopiedAlert.title': 'Kopyalandı',
  'bakra.linkCopiedAlert.message': 'Bağlantı panoya kopyalandı',
  'bakra.saveToCollection': 'Koleksiyona Kaydet',
  'bakra.reel': 'Reel',
  'bakra.emptyFeed.title': 'Henüz reel yok',
  'bakra.emptyFeed.subtitle': 'İlk reeli oluşturun!',
  'bakra.emptyFeed.actionLabel': 'Reel Oluştur',

  // ===== MAJLIS =====
  'majlis.politics': 'Siyaset',
  'majlis.replies': '{{count}} Yanıt',
  'majlis.thread': 'Gönderi Dizisi',
  'majlis.newThread': 'Yeni Gönderi Dizisi',
  'majlis.joinConversation': 'Sohbete katılın',
  'majlis.beFirstToShare': 'Bakış açınızı ilk paylaşan siz olun',
  'majlis.writeReply': 'Yanıt yazın…',
  'majlis.loadContentError': 'Bu gönderi dizisi yüklenemedi',
  'majlis.deleteReplyTitle': 'Yanıt silinsin mi?',
  'majlis.deleteReplyMessage': 'Bu yanıt kalıcı olarak silinecek.',
  'majlis.caughtUp': 'Hepsini gördünüz',
  'majlis.forYou': 'Senin İçin',
  'majlis.following': 'Takip Edilenler',
  'majlis.trending': 'Trend',
  'majlis.emptyFeed.title': 'Henüz gönderi dizisi yok',
  'majlis.emptyFeed.subtitle': 'İlk gönderi dizisini oluşturun',
  'majlis.emptyFeed.actionLabel': 'Gönderi Dizisi Oluştur',
  'majlis.viewEngagement': 'Etkileşimi Gör',
  'majlis.viewReach': 'Erişimi Gör',
  'majlis.viewImpressions': 'Gösterimleri Gör',
  'majlis.viewProfileVisits': 'Profil Ziyaretlerini Gör',
  'majlis.viewWebsiteClicks': 'Web Sitesi Tıklamalarını Gör',
  'majlis.viewEmailClicks': 'E-posta Tıklamalarını Gör',
  'majlis.viewPhoneCalls': 'Telefon Aramalarını Gör',
  'majlis.viewGetDirections': 'Yol Tariflerini Gör',
  'majlis.viewSaved': 'Kaydedilenleri Gör',
  'majlis.viewLiked': 'Beğenilenleri Gör',
  'majlis.viewCommented': 'Yorum Yapılanları Gör',
  'majlis.viewShared': 'Paylaşılanları Gör',
  'majlis.viewTagged': 'Etiketlenenleri Gör',
  'majlis.viewMentioned': 'Bahsedilenleri Gör',
  'majlis.viewReposted': 'Yeniden Paylaşılanları Gör',
  'majlis.viewQuoted': 'Alıntılananları Gör',
  'majlis.viewArchived': 'Arşivlenenleri Gör',
  'majlis.viewDeleted': 'Silinenleri Gör',
  'majlis.viewHidden': 'Gizlenenleri Gör',
  'majlis.viewReported': 'Şikâyet Edilenleri Gör',
  'majlis.viewBlocked': 'Engellenenleri Gör',
  'majlis.viewMuted': 'Sessizdekileri Gör',
  'majlis.viewRestricted': 'Kısıtlananları Gör',
  'majlis.viewFollowing': 'Takip Edilenleri Gör',
  'majlis.viewFollowers': 'Takipçileri Gör',
  'majlis.viewMutual': 'Ortak Takipçileri Gör',
  'majlis.viewSuggested': 'Önerilenleri Gör',
  'majlis.viewDiscover': 'Keşfeti Gör',
  'majlis.viewTrending': 'Trendleri Gör',
  'majlis.viewPopular': 'Popülerleri Gör',
  'majlis.viewRecent': 'Son Paylaşılanları Gör',
  'majlis.viewNearby': 'Yakındekileri Gör',
  'majlis.viewGlobal': 'Küreseli Gör',
  'majlis.viewLocal': 'Yereli Gör',
  'majlis.viewNational': 'Ulusal Gör',
  'majlis.viewInternational': 'Uluslararası Gör',
  'majlis.viewWorldwide': 'Dünya Genelini Gör',

  // ===== RISALAH =====
  'risalah.react': 'Tepki Ver',
  'risalah.call': 'Ara',
  'risalah.videoCall': 'Görüntülü Arama',
  'risalah.voiceCall': 'Sesli Arama',
  'risalah.groupInfo': 'Grup Bilgisi',
  'risalah.contactInfo': 'Kişi Bilgisi',
  'risalah.media': 'Medya',
  'risalah.links': 'Bağlantılar',
  'risalah.docs': 'Belgeler',
  'risalah.searchMessages': 'Mesaj ara',
  'risalah.wallpaper': 'Duvar Kağıdı',
  'risalah.encryptionInfo': 'Şifreleme Bilgisi',
  'risalah.disappearing': 'Kaybolan Mesajlar',
  'risalah.groupName': 'Grup Adı',
  'risalah.groupDescription': 'Grup Açıklaması',
  'risalah.addMembers': 'Üye Ekle',
  'risalah.leaveGroup': 'Gruptan Ayrıl',
  'risalah.typing': 'yazıyor',
  'risalah.noMessages': 'Henüz mesaj yok',
  'risalah.yourConversations': 'Sohbetleriniz',
  'risalah.messagesHint': 'Mesajlarınız burada görünecek',
  'risalah.newMessage': 'Yeni Mesaj',
  'risalah.noGroupsYet': 'Henüz grup yok',
  'risalah.createGroupHint': 'Arkadaşlarınızla grup oluşturun',
  'risalah.archived': 'Arşivlenen',
  'risalah.newGroup': 'Yeni Grup',
  'risalah.chats': 'Sohbetler',
  'risalah.groups': 'Gruplar',
  'risalah.unread': 'Okunmamış',
  'risalah.all': 'Tümü',
  'risalah.group': 'Grup',
  'risalah.chat': 'Sohbet',
  'risalah.chatFolders': 'Sohbet Klasörleri',
  'risalah.folderNamePlaceholder': 'Klasör adı...',
  'risalah.noFoldersYet': 'Henüz klasör yok',
  'risalah.createFoldersHint': 'Sohbetlerinizi düzenlemek için klasörler oluşturun',
  'risalah.savedMessages': 'Kaydedilmiş Mesajlar',
  'risalah.noSavedMessages': 'Kaydedilmiş mesaj yok',
  'risalah.savedMessagesHint': 'Mesajları buraya iletin veya aşağıya bir not yazın',
  'risalah.searchSavedMessages': 'Kaydedilmiş mesajları ara...',
  'risalah.typeNote': 'Bir not yazın...',
  'risalah.editFolder': 'Klasörü Düzenle',
  'risalah.deleteFolder': 'Klasörü Sil',
  'risalah.deleteForEveryone': 'Herkes İçin Sil',
  'risalah.searchStickers': 'Çıkartma ara...',
  'risalah.noStickerPacks': 'Çıkartma paketi bulunamadı',
  'risalah.stickerSearchHint': 'Farklı anahtar kelimelerle aramayı deneyin',
  'risalah.noRecentStickers': 'Son çıkartma yok',
  'risalah.useStickersHint': 'Çıkartma kullanın ve burada görünecekler',
  'risalah.browseMorePacks': 'Daha fazla çıkartma paketi göz atın',
  'risalah.noStickersInPack': 'Bu pakette çıkartma yok',
  'risalah.addMorePacks': 'Başlamak için daha fazla çıkartma paketi ekleyin',
  'risalah.forward': 'İlet',
  'risalah.star': 'Yıldızla',
  'risalah.unstar': 'Yıldızı Kaldır',

  // ===== MINBAR =====
  'minbar.shorts': 'Kısa Videolar',
  'minbar.video': 'Video',
  'minbar.bell': 'Bildirim',
  'minbar.personalized': 'Kişiselleştirilmiş',
  'minbar.remix': 'Remix',
  'minbar.home': 'Ana Sayfa',
  'minbar.subscriptions': 'Abonelikler',
  'minbar.continueWatching': 'İzlemeye Devam Et',
  'minbar.noSubscribedVideos': 'Abone olunan video yok',
  'minbar.subscribeToSeeVideos': 'Videolarını burada görmek için kanallara abone olun',
  'minbar.exploreChannels': 'Kanalları Keşfet',
  'minbar.noVideosYet': 'Henüz video yok',
  'minbar.beFirstToUpload': 'İlk uzun videoyu yükleyen siz olun',
  'minbar.saveToWatchLater': 'Sonra İzle listesine kaydet',
  'minbar.notInterested': 'İlgilenmiyorum',
  'minbar.categoryAll': 'Tümü',
  'minbar.categoryIslamic': 'İslami',
  'minbar.categoryEducation': 'Eğitim',
  'minbar.categoryLifestyle': 'Yaşam Tarzı',
  'minbar.categoryTech': 'Teknoloji',
  'minbar.categoryEntertainment': 'Eğlence',
  'minbar.streamTitlePlaceholder': 'Ne yayınlıyorsunuz?',
  'minbar.streamDescPlaceholder': 'İzleyicilere yayınınızın ne hakkında olduğunu söyleyin',
  'minbar.playlistEmpty': 'Bu oynatma listesine eklenen videolar burada görünecek',
  'minbar.skipBack': '10 saniye geri sar',
  'minbar.skipForward': '10 saniye ileri sar',
  'minbar.minimize': 'Küçült',
  'minbar.fullscreen': 'Tam Ekran',
  'minbar.pictureInPicture': 'Resim İçinde Resim',
  'minbar.dislike': 'Beğenme',
  'minbar.all': 'Otomatik',
  'minbar.watchLater': 'Sonra İzle',

  // ===== PROFILE =====
  'profile.call': 'Ara',
  'profile.videoCall': 'Görüntülü Arama',
  'profile.voiceCall': 'Sesli Arama',
  'profile.restrict': 'Kısıtla',
  'profile.unrestrict': 'Kısıtlamayı Kaldır',
  'profile.posts': 'Gönderiler',
  'profile.threads': 'Gönderi Dizileri',
  'profile.reels': 'Reels',
  'profile.liked': 'Beğenilenler',
  'profile.following': 'Takip Edilen',
  'profile.followers': 'Takipçiler',
  'profile.editProfile': 'Profili Düzenle',
  'profile.shareProfile': 'Profili Paylaş',
  'profile.follow': 'Takip Et',
  'profile.followUser': 'Kullanıcıyı takip et',
  'profile.unfollowUser': 'Takibi bırak',
  'profile.sendMessage': 'Mesaj Gönder',
  'profile.noContent': 'İçerik yok',
  'profile.noLikedPosts': 'Beğenilen gönderi yok',
  'profile.userNotFound': 'Kullanıcı bulunamadı',
  'profile.archive': 'Arşiv',
  'profile.pinned': 'Sabitlenmiş',
  'profile.blockedTitle': 'Engellendi',
  'profile.blockedMessage': '@{{username}} engellendi',
  'profile.mutedTitle': 'Sessize Alındı',
  'profile.mutedMessage': '@{{username}} sessize alındı',
  'profile.blockConfirmTitle': 'Engelle?',
  'profile.blockConfirmMessage': '@{{username}} engellensin mi?',
  'profile.block': 'Engelle',
  'profile.muteUser': '@{{username}} sessize al',
  'profile.blockUser': '@{{username}} engelle',
  'profile.options': 'Seçenekler',
  'profile.qrCode': 'QR Kod',
  'profile.reportSentTitle': 'Şikâyet Gönderildi',
  'profile.reportSentMessage': 'Geri bildiriminiz alındı. İnceleyeceğiz.',
  'profile.reportAccountTitle': 'Hesabı Şikâyet Et',
  'profile.reportAccountMessage': 'Neden şikâyet ediyorsunuz?',
  'profile.reportSpam': 'Spam',
  'profile.reportImpersonation': 'Sahte Hesap',
  'profile.reportInappropriate': 'Uygunsuz İçerik',
  'profile.viewHighlight': '{{title}} öne çıkan hikâyeyi görüntüle',
  'profile.viewChannelAccessibility': 'Kanalı görüntüle',
  'profile.viewChannel': 'Kanalı Gör',
  'profile.openLink': '{{title}} bağlantısını aç',
  'profile.viewPinnedThread': 'Sabitlenmiş gönderi dizisini gör',
  'profile.followedByOne': '{{displayName}} tarafından takip ediliyor',
  'profile.followedByMany': '{{displayName}} ve {{otherCount}} kişi daha takip ediyor',
  'profile.viewMutualFollowersAccessibility': 'Ortak takipçileri gör',
  'profile.savedPosts': 'Kaydedilen Gönderiler',

  // ===== ISLAMIC =====
  'islamic.dhikr': 'Zikir Sayacı',
  'islamic.surah': 'Sure',
  'islamic.ayah': 'Ayet',
  'islamic.tafsir': 'Tefsir',
  'islamic.translation': 'Tercüme',
  'islamic.recitation': 'Kıraat',
  'islamic.bookmark': 'Yer İşareti',
  'islamic.share': 'Paylaş',
  'islamic.prayerTimes': 'Namaz Vakitleri',
  'islamic.now': 'ŞİMDİ',
  'islamic.next': 'SONRAKİ',
  'islamic.currentPrayer': 'Mevcut Namaz',
  'islamic.timeRemainingUntil': 'Kalan süre:',
  'islamic.todaysPrayerTimes': 'Bugünün Namaz Vakitleri',
  'islamic.prayerMethod': 'Hesaplama Yöntemi',
  'islamic.qiblaDirection': 'Kıble Yönü',
  'islamic.dailyHadith': 'Günün Hadisi',
  'islamic.nearbyMosques': 'Yakındaki Camiler',
  'islamic.locationCoords': 'Enlem: {{lat}}, Boylam: {{lng}}',
  'islamic.detectingLocation': 'Konum belirleniyor...',
  'islamic.errors.locationPermission': 'Konum izni gerekli',
  'islamic.errors.failedToLoad': 'Yüklenemedi',
  'islamic.errors.noPrayerTimes': 'Namaz vakitleri yok',
  'islamic.errors.couldNotLoad': 'Yüklenemedi',

  // ===== PRAYER NOTIFICATIONS =====
  'prayerNotifications.settings': 'Namaz Bildirimleri Ayarları',
  'prayerNotifications.dndDuringPrayer': 'Namaz sırasında Rahatsız Etme',
  'prayerNotifications.dndDescription': 'Namaz vakitlerinde bildirimleri sessize al',
  'prayerNotifications.adhanAlerts': 'Ezan uyarıları',
  'prayerNotifications.adhanDescription': 'Namaz vakitlerinde ezan bildirimi al',
  'prayerNotifications.adhanStyle': 'Ezan stili',
  'prayerNotifications.makkah': 'Mekke',
  'prayerNotifications.madinah': 'Medine',
  'prayerNotifications.alaqsa': 'Mescid-i Aksa',
  'prayerNotifications.reminderBefore': 'Önceden hatırlat',
  'prayerNotifications.none': 'Yok',
  'prayerNotifications.minutes': '{{count}} dakika',

  // ===== ONBOARDING =====
  'onboarding.interests.title': 'Nelerle ilgileniyorsunuz?',
  'onboarding.interests.subtitle': 'Akışınızı kişiselleştirmek için en az 3 konu seçin',
  'onboarding.interests.selectedCount': '{{count}} seçildi',
  'onboarding.interests.needMore': '({{count}} daha gerekli)',
  'onboarding.interests.fiqh': 'Fıkıh',
  'onboarding.interests.quran': "Kur'an",
  'onboarding.interests.history': 'Tarih',
  'onboarding.interests.family': 'Aile',
  'onboarding.interests.health': 'Sağlık',
  'onboarding.interests.business': 'İş Dünyası',
  'onboarding.interests.tech': 'Teknoloji',
  'onboarding.interests.arts': 'Sanat',
  'onboarding.interests.travel': 'Seyahat',
  'onboarding.interests.education': 'Eğitim',
  'onboarding.interests.social': 'Sosyal',
  'onboarding.interests.sports': 'Spor',
  'onboarding.username.title': 'Kullanıcı adınızı seçin',
  'onboarding.username.subtitle': 'Bu, Mizanly üzerinde sizi tanımlayacak',
  'onboarding.username.placeholder': 'kullanıcı adı',
  'onboarding.username.checking': 'Kontrol ediliyor...',
  'onboarding.username.available': 'kullanılabilir',
  'onboarding.username.taken': 'Bu kullanıcı adı alınmış',
  'onboarding.username.preview': 'Profiliniz: @{{username}}',
  'onboarding.username.validation.invalidChars': 'Sadece küçük harf, rakam, nokta ve alt çizgi kullanılabilir',
  'onboarding.profile.title': 'Profilinizi oluşturun',
  'onboarding.profile.subtitle': 'Topluluğa kendinizden bahsedin',
  'onboarding.profile.addPhoto': 'Fotoğraf ekle',
  'onboarding.profile.avatarHint': 'Bunu daha sonra ayarlardan değiştirebilirsiniz',
  'onboarding.profile.displayName': 'Görünen Ad',
  'onboarding.profile.namePlaceholder': 'Adınız',
  'onboarding.profile.bioLabel': 'Biyografi',
  'onboarding.profile.optional': '(isteğe bağlı)',
  'onboarding.profile.bioPlaceholder': 'Kendinizden bahsedin...',
  'onboarding.profile.skip': 'Şimdilik atla',
  'onboarding.profile.errors.nameRequired': 'Görünen ad zorunludur',
  'onboarding.profile.errors.nameLength': 'Ad 2-50 karakter olmalıdır',
  'onboarding.profile.errors.saveFailed': 'Profil kaydedilemedi. Lütfen tekrar deneyin.',
  'onboarding.suggested.title': 'Takip edilecek kişiler',
  'onboarding.suggested.subtitle': 'Başlamak için bazı hesapları takip edin',
  'onboarding.suggested.follow': 'Takip Et',
  'onboarding.suggested.following': 'Takip Ediliyor',
  'onboarding.suggested.getStarted': 'Başla',
  'onboarding.suggested.skipForNow': 'Şimdilik atla',

  // ===== COMPOSE =====
  'compose.whatsOnYourMind': 'Aklınızda ne var?',
  'compose.addToThread': 'Gönderi dizisine ekle…',
  'compose.failedToPostThread': 'Gönderi dizisi paylaşılamadı.',
  'compose.failedToCreatePost': 'Gönderi oluşturulamadı. Lütfen tekrar deneyin.',
  'compose.discardThread': 'Gönderi dizisi silinsin mi?',
  'compose.unsavedContent': 'Kaydedilmemiş içeriğiniz var.',
  'compose.keepEditing': 'Düzenlemeye devam et',
  'compose.discard': 'Sil',
  'compose.chooseCircle': 'Bir Çevre Seçin',
  'compose.noCirclesYet': 'Henüz bir çevreniz yok.',
  'compose.createCircle': 'Çevre oluştur',
  'compose.poll': 'Anket',
  'compose.askQuestion': 'Bir soru sorun…',
  'compose.addOption': '+ Seçenek ekle',
  'compose.allowMultipleAnswers': 'Birden fazla yanıta izin ver',
  'compose.draftRestored': 'Taslak geri yüklendi',
  'compose.uploadingMedia': 'Medya yükleniyor…',
  'compose.limitReached': 'Limite ulaşıldı',
  'compose.mediaLimit': 'En fazla 10 fotoğraf veya video ekleyebilirsiniz.',
  'compose.saved': 'Kaydedildi',
  'compose.draftSavedToAccount': 'Taslak hesabınıza kaydedildi',
  'compose.failedToSaveDraft': 'Taslak kaydedilemedi',
  'compose.continueThread': 'Gönderi dizisine devam edin…',
  'compose.visibility.everyone': 'Herkes',
  'compose.visibility.followers': 'Takipçiler',
  'compose.visibility.circle': 'Çevre',

  // ===== EDIT PROFILE =====
  'editProfile.changeCover': 'Kapak Değiştir',
  'editProfile.addCoverPhoto': 'Kapak fotoğrafı ekle',
  'editProfile.tapToUpload': 'Yüklemek için dokunun',
  'editProfile.displayName': 'Görünen Ad',
  'editProfile.username': 'Kullanıcı Adı',
  'editProfile.bio': 'Biyografi',
  'editProfile.website': 'Web Sitesi',
  'editProfile.location': 'Konum',
  'editProfile.pronouns': 'Zamirler',
  'editProfile.birthday': 'Doğum Günü',
  'editProfile.privateAccount': 'Gizli Hesap',
  'editProfile.privateAccountHint': 'Sadece onaylanan takipçiler gönderilerinizi görebilir',
  'editProfile.profileLinks': 'Profil Bağlantıları',
  'editProfile.addLink': 'Bağlantı ekle',
  'editProfile.namePlaceholder': 'Adınız',
  'editProfile.bioPlaceholder': 'Kendinizden bahsedin...',
  'editProfile.locationPlaceholder': 'Şehir, Ülke',
  'editProfile.pronounsPlaceholder': 'ör. o/ona',
  'editProfile.birthdayPlaceholder': 'YYYY-AA-GG',
  'editProfile.linkTitlePlaceholder': 'Bağlantı başlığı',
  'editProfile.loadErrorTitle': 'Profil yüklenemedi',
  'editProfile.loadErrorSubtitle': 'Lütfen daha sonra tekrar deneyin',
  'editProfile.urlPlaceholder': 'URL (https://...)',

  // ===== DISCOVER =====
  'discover.title': 'Keşfet',
  'discover.all': 'Tümü',
  'discover.trending': 'Trend',
  'discover.trendingNow': 'Şu Anda Trend',
  'discover.featured': 'Öne Çıkanlar',
  'discover.explore': 'Keşfet',
  'discover.categories.food': 'Yemek',
  'discover.categories.fashion': 'Moda',
  'discover.categories.sports': 'Spor',
  'discover.categories.tech': 'Teknoloji',
  'discover.categories.islamic': 'İslami',
  'discover.categories.art': 'Sanat',
  'discover.nothingYet': 'Henüz bir şey yok',
  'discover.followMoreCreators': 'İçerik görmek için daha fazla içerik üretici takip edin',
  'discover.findPeople': 'Kişi Bul',
  'discover.loadFailed': 'İçerik yüklenemedi',
  'discover.tryAgainLater': 'Lütfen daha sonra tekrar deneyin',
  'discover.reachedEnd': 'Sonuna ulaştınız',

  // ===== COMMUNITY =====
  'community.fatwaQA': 'Fetva Soru-Cevap',
  'community.noQuestionsYet': 'Henüz soru yok',
  'community.askFirstQuestion': 'İlk soruyu soran siz olun',
  'community.mentorship': 'Mentorluk',
  'community.findMentor': 'Bir mentor bul',
  'community.findMentorHint': 'Deneyimli topluluk üyelerini arayın',
  'community.noMentorships': 'Mentorluk yok',
  'community.noMentorshipsHint': 'Bir mentor talep edin veya mentee isteklerini kabul edin',
  'community.localBoards': 'Yerel Panolar',
  'community.noLocalBoards': 'Yerel pano yok',
  'community.createBoardHint': 'Topluluğunuz için ilk panoyu oluşturun',
  'community.searchByCity': 'Şehre göre ara...',
  'community.voicePost': 'Sesli Gönderi',
  'community.waqfEndowments': 'Vakıf Bağışları',
  'community.noWaqfFunds': 'Henüz vakıf fonu yok',
  'community.waqfHint': 'Topluluğu desteklemek için bir vakıf oluşturun',
  'community.watchParties': 'İzleme Partileri',
  'community.noWatchParties': 'İzleme partisi yok',
  'community.watchPartyHint': 'Arkadaşlarınızla birlikte video izlemek için bir parti başlatın',
  'community.startParty': 'Parti Başlat',
  'community.partyNamePlaceholder': 'Parti adı...',
  'community.videoIdPlaceholder': 'Video Kimliği...',
  'community.questionPlaceholder': 'Sorunuzu ayrıntılı olarak sorun...',

  // ===== ACCESSIBILITY =====
  'accessibility.watchLaterHint': 'Sonra izle listenizi görüntüleyin',
  'accessibility.notificationsHint': 'Bildirimlerinizi görüntüleyin',
  'accessibility.yourProfile': 'Profiliniz',
  'accessibility.composeThread': 'Gönderi dizisi oluştur',
  'accessibility.composeThreadHint': 'Yeni bir gönderi dizisi yazın',
  'accessibility.newConversation': 'Yeni sohbet',
  'accessibility.newConversationHint': 'Yeni bir sohbet başlatın',
  'accessibility.openConversation': 'Sohbeti aç',
  'accessibility.archivedConversations': 'Arşivlenen sohbetler',
  'accessibility.archiveConversation': 'Sohbeti arşivle',
  'accessibility.broadcastChannels': 'Yayın kanalları',
  'accessibility.moreOptions': 'Daha fazla seçenek',
  'accessibility.replyToThread': 'Gönderi dizisine yanıtla',
  'accessibility.shareThread': 'Gönderi dizisini paylaş',
  'accessibility.doubleTapLike': 'Beğenmek için çift dokunun',
  'accessibility.showSensitive': 'Hassas içeriği göster',
  'accessibility.commentOnPost': 'Gönderiye yorum yap',
  'accessibility.sharePost': 'Gönderiyi paylaş',
  'accessibility.viewPost': 'Gönderiyi gör',
  'accessibility.viewReel': 'Reeli gör',
  'accessibility.attachMedia': 'Medya ekle',
  'accessibility.gifPicker': 'GIF seçici',
  'accessibility.messageInput': 'Mesaj girişi',
  'accessibility.sendMessage': 'Mesaj gönder',
  'accessibility.recordVoice': 'Sesli mesaj kaydet',
  'accessibility.editGroupName': 'Grup adını düzenle',
  'accessibility.addText': 'Metin ekle',
  'accessibility.toggleTextBg': 'Metin arka planını değiştir',
  'accessibility.streamTitle': 'Canlı yayın başlığı',
  'accessibility.streamDesc': 'Canlı yayın açıklaması',
  'accessibility.questionInput': 'Soru girişi',
  'accessibility.replyInput': 'Yanıt giriş alanı',
  'accessibility.threadContent': 'Gönderi dizisi içeriği',
  'accessibility.threadContinuation': 'Gönderi dizisi devamı',
  'accessibility.postContent': 'Gönderi içeriği',
  'accessibility.saveDraftToCloud': 'Taslağı buluta kaydet',
  'accessibility.cancelEditing': 'Düzenlemeyi iptal et',
  'accessibility.saveComment': 'Yorumu kaydet',
  'accessibility.replyToComment': 'Yoruma yanıtla',
  'accessibility.editComment': 'Yorumu düzenle',
  'accessibility.deleteComment': 'Yorumu sil',
  'accessibility.unlikeComment': 'Yorumu beğenmekten vazgeç',
  'accessibility.likeComment': 'Yorumu beğen',
  'accessibility.cancelReply': 'Yanıtı iptal et',
  'accessibility.commentTextInput': 'Yorum metin girişi',
  'accessibility.sendComment': 'Yorumu gönder',
  'accessibility.goBack': 'Geri dön',
  'accessibility.commentReel': 'Reele yorum yap',
  'accessibility.createStory': 'Hikâye oluştur',
  'accessibility.createStoryHint': 'Yeni bir hikâye oluşturun',
  'accessibility.search': 'Ara',
  'accessibility.searchHint': 'Kişi, hashtag ve içerik arayın',
  'accessibility.notifications': 'Bildirimler',
  'accessibility.uploadReel': 'Reel yükle',
  'accessibility.viewProfile': '@{{username}} profilini gör',
  'accessibility.likeReel': 'Reeli beğen',
  'accessibility.unlikeReel': 'Reel beğenisini geri al',
  'accessibility.shareReel': 'Reeli paylaş',
  'accessibility.removeBookmark': 'Yer işaretini kaldır',
  'accessibility.bookmarkReel': 'Reeli yer işaretine ekle',
  'accessibility.hashtag': '{{name}} hashtagini gör',
  'accessibility.hashtagHint': '{{name}} hashtagiyle gönderileri gör',
  'accessibility.replyToUser': '{{username}} kullanıcısına yanıtla',
  'accessibility.unlikeReply': 'Yanıt beğenisini geri al',
  'accessibility.likeReply': 'Yanıtı beğen',
  'accessibility.deleteReply': 'Yanıtı sil',
};

// Apply path-based translations
function applyPathTranslations(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'object' && value !== null) {
      result[key] = applyPathTranslations(value, path);
    } else if (typeof value === 'string') {
      result[key] = pathTranslations[path] || value;
    } else {
      result[key] = value;
    }
  }
  return result;
}

// First apply dictionary-based translations
const dict = {
  'Save': 'Kaydet', 'Cancel': 'İptal', 'Delete': 'Sil', 'Done': 'Tamam',
  'Next': 'İleri', 'Back': 'Geri', 'Search': 'Ara', 'Share': 'Paylaş',
  'Edit': 'Düzenle', 'Settings': 'Ayarlar', 'Close': 'Kapat', 'Confirm': 'Onayla',
  'Yes': 'Evet', 'No': 'Hayır', 'OK': 'Tamam', 'Continue': 'Devam',
  'Skip': 'Atla', 'Select': 'Seç', 'Add': 'Ekle', 'Remove': 'Kaldır',
  'Create': 'Oluştur', 'Update': 'Güncelle', 'Submit': 'Gönder', 'Send': 'Gönder',
  'Post': 'Paylaş', 'Reply': 'Yanıtla', 'Like': 'Beğen', 'Follow': 'Takip Et',
  'Unfollow': 'Takibi Bırak', 'Block': 'Engelle', 'Unblock': 'Engeli Kaldır',
  'Report': 'Şikâyet Et', 'Hide': 'Gizle', 'Show': 'Göster', 'Enable': 'Etkinleştir',
  'Disable': 'Devre Dışı', 'Allow': 'İzin Ver', 'Deny': 'Reddet',
  'Active': 'Aktif', 'Inactive': 'Pasif', 'Online': 'Çevrimiçi', 'Offline': 'Çevrimdışı',
  'Today': 'Bugün', 'Yesterday': 'Dün', 'Tomorrow': 'Yarın', 'Now': 'Şimdi',
  'Later': 'Sonra', 'Never': 'Asla', 'All': 'Tümü', 'None': 'Hiçbiri',
  'First': 'İlk', 'Last': 'Son', 'Previous': 'Önceki', 'Start': 'Başla',
  'Pause': 'Duraklat', 'Stop': 'Durdur', 'Play': 'Oynat', 'Upload': 'Yükle',
  'Download': 'İndir', 'Refresh': 'Yenile', 'Success': 'Başarılı',
  'Warning': 'Uyarı', 'Help': 'Yardım', 'About': 'Hakkında',
  'Version': 'Sürüm', 'Language': 'Dil', 'Dark': 'Koyu', 'Light': 'Açık',
  'Notifications': 'Bildirimler', 'Location': 'Konum', 'Camera': 'Kamera',
  'Photos': 'Fotoğraflar', 'Calendar': 'Takvim', 'Contacts': 'Kişiler',
  'Following': 'Takip Edilen', 'Followers': 'Takipçiler', 'Bookmark': 'Yer İşareti',
  'Archive': 'Arşiv', 'Mute': 'Sessize Al', 'Pin': 'Sabitle', 'Trending': 'Trend',
  'Public': 'Herkese Açık', 'Private': 'Gizli', 'Subscribe': 'Abone Ol',
  'Subscribed': 'Abone', 'Videos': 'Videolar', 'Channel': 'Kanal',
  'Channels': 'Kanallar', 'Playlists': 'Oynatma Listeleri', 'Library': 'Kütüphane',
  'Live': 'Canlı', 'Quality': 'Kalite', 'Speed': 'Hız',
  'Marketplace': 'Pazar Yeri', 'Products': 'Ürünler', 'Seller': 'Satıcı',
  'Discover': 'Keşfet', 'Explore': 'Keşfet', 'Mentions': 'Bahsetmeler',
  'Verified': 'Doğrulanmış', 'Messages': 'Mesajlar', 'Groups': 'Gruplar',
  'Profile': 'Profil', 'Feed': 'Akış', 'Stories': 'Hikâyeler',
  'Achievements': 'Başarımlar', 'Challenges': 'Meydan Okumalar',
  'Leaderboard': 'Skor Tablosu', 'Level': 'Seviye',
  'Email': 'E-posta', 'Phone': 'Telefon', 'Password': 'Şifre',
  'Username': 'Kullanıcı Adı', 'Video': 'Video',
  'Content': 'İçerik', 'Privacy': 'Gizlilik', 'Account': 'Hesap',
  'Security': 'Güvenlik', 'Pending': 'Beklemede', 'Paid': 'Ödendi',
  'Shipped': 'Kargoda', 'Delivered': 'Teslim Edildi', 'Cancelled': 'İptal Edildi',
  'Comments': 'Yorumlar', 'Events': 'Etkinlikler', 'Promotions': 'Promosyonlar',
  'Tips': 'Bahşişler', 'Membership': 'Üyelik', 'Subscription': 'Abonelik',
  'Donation': 'Bağış', 'Payment': 'Ödeme', 'Region': 'Bölge',
  'Timezone': 'Saat Dilimi', 'Currency': 'Para Birimi', 'Units': 'Birimler',
  'Appearance': 'Görünüm', 'Custom': 'Özel',
};

function translateWithDict(obj) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'object' && value !== null) {
      result[key] = translateWithDict(value);
    } else if (typeof value === 'string') {
      result[key] = dict[value] || value;
    } else {
      result[key] = value;
    }
  }
  return result;
}

// Step 1: Dictionary-based translation
let tr = translateWithDict(en);
// Step 2: Path-based translation (overrides dictionary for specific paths)
tr = applyPathTranslations(tr);

fs.writeFileSync('apps/mobile/src/i18n/tr.json', JSON.stringify(tr, null, 2), 'utf8');

// Count coverage
let total = 0, translated = 0;
function count(enObj, trObj) {
  for (const [key, value] of Object.entries(enObj)) {
    if (typeof value === 'object' && value !== null) {
      count(value, trObj[key] || {});
    } else if (typeof value === 'string') {
      total++;
      if (trObj[key] !== value) translated++;
    }
  }
}
count(en, tr);
console.log(`Total: ${total}, Translated: ${translated}, Remaining: ${total - translated}`);
console.log(`Coverage: ${((translated / total) * 100).toFixed(1)}%`);
