const fs = require('fs');
const en = JSON.parse(fs.readFileSync('apps/mobile/src/i18n/en.json', 'utf8'));

// Path-based translations for ALL remaining untranslated keys
// Format: 'section.key': 'Turkish translation'
const pathTranslations = {
  // ===== TABS =====
  'tabs.profile': 'Profil',
  'tabs.events': 'Etkinlikler',
  'tabs.communities': 'Topluluklar',
  'tabs.create': 'Oluştur',
  'tabs.notifications': 'Bildirimler',
  'tabs.explore': 'Keşfet',
  'tabs.trending': 'Trend',

  // ===== SAF =====
  'saf.feed': 'Akış',
  'saf.stories': 'Hikâyeler',
  'saf.story': 'Hikâye',
  'saf.photo': 'Fotoğraf',
  'saf.video': 'Video',
  'saf.newPost': 'Yeni Gönderi',
  'saf.carousel': 'Galeri',
  'saf.gallery': 'Galeri',
  'saf.text': 'Metin',
  'saf.comments': 'Yorumlar',
  'saf.likes': 'Beğeniler',
  'saf.shares': 'Paylaşımlar',
  'saf.saves': 'Kaydedilenler',
  'saf.views': 'Görüntülenmeler',
  'saf.replyingTo': '@{{username}} kullanıcısına yanıt veriliyor',
  'saf.replyToUser': '@{{username}} kullanıcısına yanıt ver…',
  'saf.addComment': 'Yorum ekle…',
  'saf.startConversation': 'Sohbeti başlatın',
  'saf.firstToShare': 'Düşüncelerinizi ilk paylaşan siz olun',
  'saf.noComments': 'Henüz yorum yok',
  'saf.beFirstToComment': 'İlk yorumu yapan siz olun',
  'saf.questionPlaceholder': 'Sorunuzu yazın...',
  'saf.post': 'Gönderi',
  'saf.deleteCommentTitle': 'Yorum silinsin mi?',
  'saf.deleteCommentMessage': 'Bu yorum kalıcı olarak silinecek.',
  'saf.couldNotLoadContent': 'Bu içerik yüklenemedi',
  'saf.goBack': 'Geri Dön',
  'saf.emptyFeed.title': 'Akışınız boş',
  'saf.emptyFeed.subtitle': 'İçerik görmek için kişileri takip edin',
  'saf.following': 'Takip Edilenler',
  'saf.forYou': 'Senin İçin',

  // ===== BAKRA =====
  'bakra.hashtags': 'Hashtagler',
  'bakra.sounds': 'Sesler',
  'bakra.effects': 'Efektler',
  'bakra.filters': 'Filtreler',
  'bakra.duet': 'Düet',
  'bakra.stitch': 'Birleştir',
  'bakra.trending': 'Trend',
  'bakra.originalAudio': 'Orijinal ses',
  'bakra.unknown': 'Bilinmiyor',
  'bakra.notInterested': 'İlgilenmiyorum',
  'bakra.notInterestedAlert.title': 'Anladık',
  'bakra.notInterestedAlert.message': 'Benzer içerikleri daha az gösterecğiz',
  'bakra.linkCopiedAlert.title': 'Kopyalandı',
  'bakra.linkCopiedAlert.message': 'Bağlantı panoya kopyalandı',
  'bakra.saveToCollection': 'Koleksiyona Kaydet',
  'bakra.reel': 'Reel',
  'bakra.emptyFeed.title': 'Henüz reel yok',
  'bakra.emptyFeed.subtitle': 'İlk reeli oluşturun!',
  'bakra.emptyFeed.actionLabel': 'Reel Oluştur',

  // ===== MAJLIS =====
  'majlis.politics': 'Siyaset',
  'majlis.replies': '{{count}} Yanıt',
  'majlis.thread': 'Gönderi Dizisi',
  'majlis.newThread': 'Yeni Gönderi Dizisi',
  'majlis.joinConversation': 'Sohbete katılın',
  'majlis.beFirstToShare': 'Bakış açınızı ilk paylaşan siz olun',
  'majlis.writeReply': 'Yanıt yazın…',
  'majlis.loadContentError': 'Bu gönderi dizisi yüklenemedi',
  'majlis.deleteReplyTitle': 'Yanıt silinsin mi?',
  'majlis.deleteReplyMessage': 'Bu yanıt kalıcı olarak silinecek.',
  'majlis.caughtUp': 'Hepsini gördünüz',
  'majlis.forYou': 'Senin İçin',
  'majlis.following': 'Takip Edilenler',
  'majlis.trending': 'Trend',
  'majlis.emptyFeed.title': 'Henüz gönderi dizisi yok',
  'majlis.emptyFeed.subtitle': 'İlk gönderi dizisini oluşturun',
  'majlis.emptyFeed.actionLabel': 'Gönderi Dizisi Oluştur',
  'majlis.viewEngagement': 'Etkileşimi Gör',
  'majlis.viewReach': 'Erişimi Gör',
  'majlis.viewImpressions': 'Gösterimleri Gör',
  'majlis.viewProfileVisits': 'Profil Ziyaretlerini Gör',
  'majlis.viewWebsiteClicks': 'Web Sitesi Tıklamalarını Gör',
  'majlis.viewEmailClicks': 'E-posta Tıklamalarını Gör',
  'majlis.viewPhoneCalls': 'Telefon Aramalarını Gör',
  'majlis.viewGetDirections': 'Yol Tariflerini Gör',
  'majlis.viewSaved': 'Kaydedilenleri Gör',
  'majlis.viewLiked': 'Beğenilenleri Gör',
  'majlis.viewCommented': 'Yorum Yapılanları Gör',
  'majlis.viewShared': 'Paylaşılanları Gör',
  'majlis.viewTagged': 'Etiketlenenleri Gör',
  'majlis.viewMentioned': 'Bahsedilenleri Gör',
  'majlis.viewReposted': 'Yeniden Paylaşılanları Gör',
  'majlis.viewQuoted': 'Alıntılananları Gör',
  'majlis.viewArchived': 'Arşivlenenleri Gör',
  'majlis.viewDeleted': 'Silinenleri Gör',
  'majlis.viewHidden': 'Gizlenenleri Gör',
  'majlis.viewReported': 'Şikâyet Edilenleri Gör',
  'majlis.viewBlocked': 'Engellenenleri Gör',
  'majlis.viewMuted': 'Sessizdekileri Gör',
  'majlis.viewRestricted': 'Kısıtlananları Gör',
  'majlis.viewFollowing': 'Takip Edilenleri Gör',
  'majlis.viewFollowers': 'Takipçileri Gör',
  'majlis.viewMutual': 'Ortak Takipçileri Gör',
  'majlis.viewSuggested': 'Önerilenleri Gör',
  'majlis.viewDiscover': 'Keşfeti Gör',
  'majlis.viewTrending': 'Trendleri Gör',
  'majlis.viewPopular': 'Popülerleri Gör',
  'majlis.viewRecent': 'Son Paylaşılanları Gör',
  'majlis.viewNearby': 'Yakındekileri Gör',
  'majlis.viewGlobal': 'Küreseli Gör',
  'majlis.viewLocal': 'Yereli Gör',
  'majlis.viewNational': 'Ulusal Gör',
  'majlis.viewInternational': 'Uluslararası Gör',
  'majlis.viewWorldwide': 'Dünya Genelini Gör',

  // ===== RISALAH =====
  'risalah.react': 'Tepki Ver',
  'risalah.call': 'Ara',
  'risalah.videoCall': 'Görüntülü Arama',
  'risalah.voiceCall': 'Sesli Arama',
  'risalah.groupInfo': 'Grup Bilgisi',
  'risalah.contactInfo': 'Kişi Bilgisi',
  'risalah.media': 'Medya',
  'risalah.links': 'Bağlantılar',
  'risalah.docs': 'Belgeler',
  'risalah.searchMessages': 'Mesaj ara',
  'risalah.wallpaper': 'Duvar Kağıdı',
  'risalah.encryptionInfo': 'Şifreleme Bilgisi',
  'risalah.disappearing': 'Kaybolan Mesajlar',
  'risalah.groupName': 'Grup Adı',
  'risalah.groupDescription': 'Grup Açıklaması',
  'risalah.addMembers': 'Üye Ekle',
  'risalah.leaveGroup': 'Gruptan Ayrıl',
  'risalah.typing': 'yazıyor',
  'risalah.noMessages': 'Henüz mesaj yok',
  'risalah.yourConversations': 'Sohbetleriniz',
  'risalah.messagesHint': 'Mesajlarınız burada görünecek',
  'risalah.newMessage': 'Yeni Mesaj',
  'risalah.noGroupsYet': 'Henüz grup yok',
  'risalah.createGroupHint': 'Arkadaşlarınızla grup oluşturun',
  'risalah.archived': 'Arşivlenen',
  'risalah.newGroup': 'Yeni Grup',
  'risalah.chats': 'Sohbetler',
  'risalah.groups': 'Gruplar',
  'risalah.unread': 'Okunmamış',
  'risalah.all': 'Tümü',
  'risalah.group': 'Grup',
  'risalah.chat': 'Sohbet',
  'risalah.chatFolders': 'Sohbet Klasörleri',
  'risalah.folderNamePlaceholder': 'Klasör adı...',
  'risalah.noFoldersYet': 'Henüz klasör yok',
  'risalah.createFoldersHint': 'Sohbetlerinizi düzenlemek için klasörler oluşturun',
  'risalah.savedMessages': 'Kaydedilmiş Mesajlar',
  'risalah.noSavedMessages': 'Kaydedilmiş mesaj yok',
  'risalah.savedMessagesHint': 'Mesajları buraya iletin veya aşağıya bir not yazın',
  'risalah.searchSavedMessages': 'Kaydedilmiş mesajları ara...',
  'risalah.typeNote': 'Bir not yazın...',
  'risalah.editFolder': 'Klasörü Düzenle',
  'risalah.deleteFolder': 'Klasörü Sil',
  'risalah.deleteForEveryone': 'Herkes İçin Sil',
  'risalah.searchStickers': 'Çıkartma ara...',
  'risalah.noStickerPacks': 'Çıkartma paketi bulunamadı',
  'risalah.stickerSearchHint': 'Farklı anahtar kelimelerle aramayı deneyin',
  'risalah.noRecentStickers': 'Son çıkartma yok',
  'risalah.useStickersHint': 'Çıkartma kullanın ve burada görünecekler',
  'risalah.browseMorePacks': 'Daha fazla çıkartma paketi göz atın',
  'risalah.noStickersInPack': 'Bu pakette çıkartma yok',
  'risalah.addMorePacks': 'Başlamak için daha fazla çıkartma paketi ekleyin',
  'risalah.forward': 'İlet',
  'risalah.star': 'Yıldızla',
  'risalah.unstar': 'Yıldızı Kaldır',

  // ===== MINBAR =====
  'minbar.shorts': 'Kısa Videolar',
  'minbar.video': 'Video',
  'minbar.bell': 'Bildirim',
  'minbar.personalized': 'Kişiselleştirilmiş',
  'minbar.remix': 'Remix',
  'minbar.home': 'Ana Sayfa',
  'minbar.subscriptions': 'Abonelikler',
  'minbar.continueWatching': 'İzlemeye Devam Et',
  'minbar.noSubscribedVideos': 'Abone olunan video yok',
  'minbar.subscribeToSeeVideos': 'Videolarını burada görmek için kanallara abone olun',
  'minbar.exploreChannels': 'Kanalları Keşfet',
  'minbar.noVideosYet': 'Henüz video yok',
  'minbar.beFirstToUpload': 'İlk uzun videoyu yükleyen siz olun',
  'minbar.saveToWatchLater': 'Sonra İzle listesine kaydet',
  'minbar.notInterested': 'İlgilenmiyorum',
  'minbar.categoryAll': 'Tümü',
  'minbar.categoryIslamic': 'İslami',
  'minbar.categoryEducation': 'Eğitim',
  'minbar.categoryLifestyle': 'Yaşam Tarzı',
  'minbar.categoryTech': 'Teknoloji',
  'minbar.categoryEntertainment': 'Eğlence',
  'minbar.streamTitlePlaceholder': 'Ne yayınlıyorsunuz?',
  'minbar.streamDescPlaceholder': 'İzleyicilere yayınınızın ne hakkında olduğunu söyleyin',
  'minbar.playlistEmpty': 'Bu oynatma listesine eklenen videolar burada görünecek',
  'minbar.skipBack': '10 saniye geri sar',
  'minbar.skipForward': '10 saniye ileri sar',
  'minbar.minimize': 'Küçült',
  'minbar.fullscreen': 'Tam Ekran',
  'minbar.pictureInPicture': 'Resim İçinde Resim',
  'minbar.dislike': 'Beğenme',
  'minbar.all': 'Otomatik',
  'minbar.watchLater': 'Sonra İzle',

  // ===== PROFILE =====
  'profile.call': 'Ara',
  'profile.videoCall': 'Görüntülü Arama',
  'profile.voiceCall': 'Sesli Arama',
  'profile.restrict': 'Kısıtla',
  'profile.unrestrict': 'Kısıtlamayı Kaldır',
  'profile.posts': 'Gönderiler',
  'profile.threads': 'Gönderi Dizileri',
  'profile.reels': 'Reels',
  'profile.liked': 'Beğenilenler',
  'profile.following': 'Takip Edilen',
  'profile.followers': 'Takipçiler',
  'profile.editProfile': 'Profili Düzenle',
  'profile.shareProfile': 'Profili Paylaş',
  'profile.follow': 'Takip Et',
  'profile.followUser': 'Kullanıcıyı takip et',
  'profile.unfollowUser': 'Takibi bırak',
  'profile.sendMessage': 'Mesaj Gönder',
  'profile.noContent': 'İçerik yok',
  'profile.noLikedPosts': 'Beğenilen gönderi yok',
  'profile.userNotFound': 'Kullanıcı bulunamadı',
  'profile.archive': 'Arşiv',
  'profile.pinned': 'Sabitlenmiş',
  'profile.blockedTitle': 'Engellendi',
  'profile.blockedMessage': '@{{username}} engellendi',
  'profile.mutedTitle': 'Sessize Alındı',
  'profile.mutedMessage': '@{{username}} sessize alındı',
  'profile.blockConfirmTitle': 'Engelle?',
  'profile.blockConfirmMessage': '@{{username}} engellensin mi?',
  'profile.block': 'Engelle',
  'profile.muteUser': '@{{username}} sessize al',
  'profile.blockUser': '@{{username}} engelle',
  'profile.options': 'Seçenekler',
  'profile.qrCode': 'QR Kod',
  'profile.reportSentTitle': 'Şikâyet Gönderildi',
  'profile.reportSentMessage': 'Geri bildiriminiz alındı. İnceleyeceğiz.',
  'profile.reportAccountTitle': 'Hesabı Şikâyet Et',
  'profile.reportAccountMessage': 'Neden şikâyet ediyorsunuz?',
  'profile.reportSpam': 'Spam',
  'profile.reportImpersonation': 'Sahte Hesap',
  'profile.reportInappropriate': 'Uygunsuz İçerik',
  'profile.viewHighlight': '{{title}} öne çıkan hikâyeyi görüntüle',
  'profile.viewChannelAccessibility': 'Kanalı görüntüle',
  'profile.viewChannel': 'Kanalı Gör',
  'profile.openLink': '{{title}} bağlantısını aç',
  'profile.viewPinnedThread': 'Sabitlenmiş gönderi dizisini gör',
  'profile.followedByOne': '{{displayName}} tarafından takip ediliyor',
  'profile.followedByMany': '{{displayName}} ve {{otherCount}} kişi daha takip ediyor',
  'profile.viewMutualFollowersAccessibility': 'Ortak takipçileri gör',
  'profile.savedPosts': 'Kaydedilen Gönderiler',

  // ===== ISLAMIC =====
  'islamic.dhikr': 'Zikir Sayacı',
  'islamic.surah': 'Sure',
  'islamic.ayah': 'Ayet',
  'islamic.tafsir': 'Tefsir',
  'islamic.translation': 'Tercüme',
  'islamic.recitation': 'Kıraat',
  'islamic.bookmark': 'Yer İşareti',
  'islamic.share': 'Paylaş',
  'islamic.prayerTimes': 'Namaz Vakitleri',
  'islamic.now': 'ŞİMDİ',
  'islamic.next': 'SONRAKİ',
  'islamic.currentPrayer': 'Mevcut Namaz',
  'islamic.timeRemainingUntil': 'Kalan süre:',
  'islamic.todaysPrayerTimes': 'Bugünün Namaz Vakitleri',
  'islamic.prayerMethod': 'Hesaplama Yöntemi',
  'islamic.qiblaDirection': 'Kıble Yönü',
  'islamic.dailyHadith': 'Günün Hadisi',
  'islamic.nearbyMosques': 'Yakındaki Camiler',
  'islamic.locationCoords': 'Enlem: {{lat}}, Boylam: {{lng}}',
  'islamic.detectingLocation': 'Konum belirleniyor...',
  'islamic.errors.locationPermission': 'Konum izni gerekli',
  'islamic.errors.failedToLoad': 'Yüklenemedi',
  'islamic.errors.noPrayerTimes': 'Namaz vakitleri yok',
  'islamic.errors.couldNotLoad': 'Yüklenemedi',

  // ===== PRAYER NOTIFICATIONS =====
  'prayerNotifications.settings': 'Namaz Bildirimleri Ayarları',
  'prayerNotifications.dndDuringPrayer': 'Namaz sırasında Rahatsız Etme',
  'prayerNotifications.dndDescription': 'Namaz vakitlerinde bildirimleri sessize al',
  'prayerNotifications.adhanAlerts': 'Ezan uyarıları',
  'prayerNotifications.adhanDescription': 'Namaz vakitlerinde ezan bildirimi al',
  'prayerNotifications.adhanStyle': 'Ezan stili',
  'prayerNotifications.makkah': 'Mekke',
  'prayerNotifications.madinah': 'Medine',
  'prayerNotifications.alaqsa': 'Mescid-i Aksa',
  'prayerNotifications.reminderBefore': 'Önceden hatırlat',
  'prayerNotifications.none': 'Yok',
  'prayerNotifications.minutes': '{{count}} dakika',

  // ===== ONBOARDING =====
  'onboarding.interests.title': 'Nelerle ilgileniyorsunuz?',
  'onboarding.interests.subtitle': 'Akışınızı kişiselleştirmek için en az 3 konu seçin',
  'onboarding.interests.selectedCount': '{{count}} seçildi',
  'onboarding.interests.needMore': '({{count}} daha gerekli)',
  'onboarding.interests.fiqh': 'Fıkıh',
  'onboarding.interests.quran': "Kur'an",
  'onboarding.interests.history': 'Tarih',
  'onboarding.interests.family': 'Aile',
  'onboarding.interests.health': 'Sağlık',
  'onboarding.interests.business': 'İş Dünyası',
  'onboarding.interests.tech': 'Teknoloji',
  'onboarding.interests.arts': 'Sanat',
  'onboarding.interests.travel': 'Seyahat',
  'onboarding.interests.education': 'Eğitim',
  'onboarding.interests.social': 'Sosyal',
  'onboarding.interests.sports': 'Spor',
  'onboarding.username.title': 'Kullanıcı adınızı seçin',
  'onboarding.username.subtitle': 'Bu, Mizanly üzerinde sizi tanımlayacak',
  'onboarding.username.placeholder': 'kullanıcı adı',
  'onboarding.username.checking': 'Kontrol ediliyor...',
  'onboarding.username.available': 'kullanılabilir',
  'onboarding.username.taken': 'Bu kullanıcı adı alınmış',
  'onboarding.username.preview': 'Profiliniz: @{{username}}',
  'onboarding.username.validation.invalidChars': 'Sadece küçük harf, rakam, nokta ve alt çizgi kullanılabilir',
  'onboarding.profile.title': 'Profilinizi oluşturun',
  'onboarding.profile.subtitle': 'Topluluğa kendinizden bahsedin',
  'onboarding.profile.addPhoto': 'Fotoğraf ekle',
  'onboarding.profile.avatarHint': 'Bunu daha sonra ayarlardan değiştirebilirsiniz',
  'onboarding.profile.displayName': 'Görünen Ad',
  'onboarding.profile.namePlaceholder': 'Adınız',
  'onboarding.profile.bioLabel': 'Biyografi',
  'onboarding.profile.optional': '(isteğe bağlı)',
  'onboarding.profile.bioPlaceholder': 'Kendinizden bahsedin...',
  'onboarding.profile.skip': 'Şimdilik atla',
  'onboarding.profile.errors.nameRequired': 'Görünen ad zorunludur',
  'onboarding.profile.errors.nameLength': 'Ad 2-50 karakter olmalıdır',
  'onboarding.profile.errors.saveFailed': 'Profil kaydedilemedi. Lütfen tekrar deneyin.',
  'onboarding.suggested.title': 'Takip edilecek kişiler',
  'onboarding.suggested.subtitle': 'Başlamak için bazı hesapları takip edin',
  'onboarding.suggested.follow': 'Takip Et',
  'onboarding.suggested.following': 'Takip Ediliyor',
  'onboarding.suggested.getStarted': 'Başla',
  'onboarding.suggested.skipForNow': 'Şimdilik atla',

  // ===== COMPOSE =====
  'compose.whatsOnYourMind': 'Aklınızda ne var?',
  'compose.addToThread': 'Gönderi dizisine ekle…',
  'compose.failedToPostThread': 'Gönderi dizisi paylaşılamadı.',
  'compose.failedToCreatePost': 'Gönderi oluşturulamadı. Lütfen tekrar deneyin.',
  'compose.discardThread': 'Gönderi dizisi silinsin mi?',
  'compose.unsavedContent': 'Kaydedilmemiş içeriğiniz var.',
  'compose.keepEditing': 'Düzenlemeye devam et',
  'compose.discard': 'Sil',
  'compose.chooseCircle': 'Bir Çevre Seçin',
  'compose.noCirclesYet': 'Henüz bir çevreniz yok.',
  'compose.createCircle': 'Çevre oluştur',
  'compose.poll': 'Anket',
  'compose.askQuestion': 'Bir soru sorun…',
  'compose.addOption': '+ Seçenek ekle',
  'compose.allowMultipleAnswers': 'Birden fazla yanıta izin ver',
  'compose.draftRestored': 'Taslak geri yüklendi',
  'compose.uploadingMedia': 'Medya yükleniyor…',
  'compose.limitReached': 'Limite ulaşıldı',
  'compose.mediaLimit': 'En fazla 10 fotoğraf veya video ekleyebilirsiniz.',
  'compose.saved': 'Kaydedildi',
  'compose.draftSavedToAccount': 'Taslak hesabınıza kaydedildi',
  'compose.failedToSaveDraft': 'Taslak kaydedilemedi',
  'compose.continueThread': 'Gönderi dizisine devam edin…',
  'compose.visibility.everyone': 'Herkes',
  'compose.visibility.followers': 'Takipçiler',
  'compose.visibility.circle': 'Çevre',

  // ===== EDIT PROFILE =====
  'editProfile.changeCover': 'Kapak Değiştir',
  'editProfile.addCoverPhoto': 'Kapak fotoğrafı ekle',
  'editProfile.tapToUpload': 'Yüklemek için dokunun',
  'editProfile.displayName': 'Görünen Ad',
  'editProfile.username': 'Kullanıcı Adı',
  'editProfile.bio': 'Biyografi',
  'editProfile.website': 'Web Sitesi',
  'editProfile.location': 'Konum',
  'editProfile.pronouns': 'Zamirler',
  'editProfile.birthday': 'Doğum Günü',
  'editProfile.privateAccount': 'Gizli Hesap',
  'editProfile.privateAccountHint': 'Sadece onaylanan takipçiler gönderilerinizi görebilir',
  'editProfile.profileLinks': 'Profil Bağlantıları',
  'editProfile.addLink': 'Bağlantı ekle',
  'editProfile.namePlaceholder': 'Adınız',
  'editProfile.bioPlaceholder': 'Kendinizden bahsedin...',
  'editProfile.locationPlaceholder': 'Şehir, Ülke',
  'editProfile.pronounsPlaceholder': 'ör. o/ona',
  'editProfile.birthdayPlaceholder': 'YYYY-AA-GG',
  'editProfile.linkTitlePlaceholder': 'Bağlantı başlığı',
  'editProfile.loadErrorTitle': 'Profil yüklenemedi',
  'editProfile.loadErrorSubtitle': 'Lütfen daha sonra tekrar deneyin',
  'editProfile.urlPlaceholder': 'URL (https://...)',

  // ===== DISCOVER =====
  'discover.title': 'Keşfet',
  'discover.all': 'Tümü',
  'discover.trending': 'Trend',
  'discover.trendingNow': 'Şu Anda Trend',
  'discover.featured': 'Öne Çıkanlar',
  'discover.explore': 'Keşfet',
  'discover.categories.food': 'Yemek',
  'discover.categories.fashion': 'Moda',
  'discover.categories.sports': 'Spor',
  'discover.categories.tech': 'Teknoloji',
  'discover.categories.islamic': 'İslami',
  'discover.categories.art': 'Sanat',
  'discover.nothingYet': 'Henüz bir şey yok',
  'discover.followMoreCreators': 'İçerik görmek için daha fazla içerik üretici takip edin',
  'discover.findPeople': 'Kişi Bul',
  'discover.loadFailed': 'İçerik yüklenemedi',
  'discover.tryAgainLater': 'Lütfen daha sonra tekrar deneyin',
  'discover.reachedEnd': 'Sonuna ulaştınız',

  // ===== COMMUNITY =====
  'community.fatwaQA': 'Fetva Soru-Cevap',
  'community.noQuestionsYet': 'Henüz soru yok',
  'community.askFirstQuestion': 'İlk soruyu soran siz olun',
  'community.mentorship': 'Mentorluk',
  'community.findMentor': 'Bir mentor bul',
  'community.findMentorHint': 'Deneyimli topluluk üyelerini arayın',
  'community.noMentorships': 'Mentorluk yok',
  'community.noMentorshipsHint': 'Bir mentor talep edin veya mentee isteklerini kabul edin',
  'community.localBoards': 'Yerel Panolar',
  'community.noLocalBoards': 'Yerel pano yok',
  'community.createBoardHint': 'Topluluğunuz için ilk panoyu oluşturun',
  'community.searchByCity': 'Şehre göre ara...',
  'community.voicePost': 'Sesli Gönderi',
  'community.waqfEndowments': 'Vakıf Bağışları',
  'community.noWaqfFunds': 'Henüz vakıf fonu yok',
  'community.waqfHint': 'Topluluğu desteklemek için bir vakıf oluşturun',
  'community.watchParties': 'İzleme Partileri',
  'community.noWatchParties': 'İzleme partisi yok',
  'community.watchPartyHint': 'Arkadaşlarınızla birlikte video izlemek için bir parti başlatın',
  'community.startParty': 'Parti Başlat',
  'community.partyNamePlaceholder': 'Parti adı...',
  'community.videoIdPlaceholder': 'Video Kimliği...',
  'community.questionPlaceholder': 'Sorunuzu ayrıntılı olarak sorun...',

  // ===== ACCESSIBILITY =====
  'accessibility.watchLaterHint': 'Sonra izle listenizi görüntüleyin',
  'accessibility.notificationsHint': 'Bildirimlerinizi görüntüleyin',
  'accessibility.yourProfile': 'Profiliniz',
  'accessibility.composeThread': 'Gönderi dizisi oluştur',
  'accessibility.composeThreadHint': 'Yeni bir gönderi dizisi yazın',
  'accessibility.newConversation': 'Yeni sohbet',
  'accessibility.newConversationHint': 'Yeni bir sohbet başlatın',
  'accessibility.openConversation': 'Sohbeti aç',
  'accessibility.archivedConversations': 'Arşivlenen sohbetler',
  'accessibility.archiveConversation': 'Sohbeti arşivle',
  'accessibility.broadcastChannels': 'Yayın kanalları',
  'accessibility.moreOptions': 'Daha fazla seçenek',
  'accessibility.replyToThread': 'Gönderi dizisine yanıtla',
  'accessibility.shareThread': 'Gönderi dizisini paylaş',
  'accessibility.doubleTapLike': 'Beğenmek için çift dokunun',
  'accessibility.showSensitive': 'Hassas içeriği göster',
  'accessibility.commentOnPost': 'Gönderiye yorum yap',
  'accessibility.sharePost': 'Gönderiyi paylaş',
  'accessibility.viewPost': 'Gönderiyi gör',
  'accessibility.viewReel': 'Reeli gör',
  'accessibility.attachMedia': 'Medya ekle',
  'accessibility.gifPicker': 'GIF seçici',
  'accessibility.messageInput': 'Mesaj girişi',
  'accessibility.sendMessage': 'Mesaj gönder',
  'accessibility.recordVoice': 'Sesli mesaj kaydet',
  'accessibility.editGroupName': 'Grup adını düzenle',
  'accessibility.addText': 'Metin ekle',
  'accessibility.toggleTextBg': 'Metin arka planını değiştir',
  'accessibility.streamTitle': 'Canlı yayın başlığı',
  'accessibility.streamDesc': 'Canlı yayın açıklaması',
  'accessibility.questionInput': 'Soru girişi',
  'accessibility.replyInput': 'Yanıt giriş alanı',
  'accessibility.threadContent': 'Gönderi dizisi içeriği',
  'accessibility.threadContinuation': 'Gönderi dizisi devamı',
  'accessibility.postContent': 'Gönderi içeriği',
  'accessibility.saveDraftToCloud': 'Taslağı buluta kaydet',
  'accessibility.cancelEditing': 'Düzenlemeyi iptal et',
  'accessibility.saveComment': 'Yorumu kaydet',
  'accessibility.replyToComment': 'Yoruma yanıtla',
  'accessibility.editComment': 'Yorumu düzenle',
  'accessibility.deleteComment': 'Yorumu sil',
  'accessibility.unlikeComment': 'Yorumu beğenmekten vazgeç',
  'accessibility.likeComment': 'Yorumu beğen',
  'accessibility.cancelReply': 'Yanıtı iptal et',
  'accessibility.commentTextInput': 'Yorum metin girişi',
  'accessibility.sendComment': 'Yorumu gönder',
  'accessibility.goBack': 'Geri dön',
  'accessibility.commentReel': 'Reele yorum yap',
  'accessibility.createStory': 'Hikâye oluştur',
  'accessibility.createStoryHint': 'Yeni bir hikâye oluşturun',
  'accessibility.search': 'Ara',
  'accessibility.searchHint': 'Kişi, hashtag ve içerik arayın',
  'accessibility.notifications': 'Bildirimler',
  'accessibility.uploadReel': 'Reel yükle',
  'accessibility.viewProfile': '@{{username}} profilini gör',
  'accessibility.likeReel': 'Reeli beğen',
  'accessibility.unlikeReel': 'Reel beğenisini geri al',
  'accessibility.shareReel': 'Reeli paylaş',
  'accessibility.removeBookmark': 'Yer işaretini kaldır',
  'accessibility.bookmarkReel': 'Reeli yer işaretine ekle',
  'accessibility.hashtag': '{{name}} hashtagini gör',
  'accessibility.hashtagHint': '{{name}} hashtagiyle gönderileri gör',
  'accessibility.replyToUser': '{{username}} kullanıcısına yanıtla',
  'accessibility.unlikeReply': 'Yanıt beğenisini geri al',
  'accessibility.likeReply': 'Yanıtı beğen',
  'accessibility.deleteReply': 'Yanıtı sil',

  // ===== SCREENS =====
  'screens.followers.title': 'Takipçiler',
  'screens.followers.viewProfile': "{{name}} profilini gör",
  'screens.followers.emptyState': 'Henüz takipçi yok',
  'screens.followers.emptySubtitle': 'Topluluğunuzu büyütmek için profilinizi paylaşın',
  'screens.followers.count_one': '{{count}} takipçi',
  'screens.followers.count_other': '{{count}} takipçi',
  'screens.following.emptyState': 'Henüz kimseyi takip etmiyor',
  'screens.following.emptySubtitle': 'Sizi ilham veren kişileri keşfedin ve takip edin',
  'screens.following.viewProfile': "{{name}} profilini gör",
  'screens.hashtag-explore.emptyState': 'Hashtag bulunamadı',
  'screens.hashtag-explore.emptySubtitle': 'Farklı anahtar kelimelerle deneyin',

  // ===== GAMIFICATION =====
  'gamification.streaks.title': 'Seriler',
  'gamification.streaks.posting': 'Paylaşım Serisi',
  'gamification.streaks.engagement': 'Etkileşim Serisi',
  'gamification.streaks.quran': "Kur'an Serisi",
  'gamification.streaks.dhikr': 'Zikir Serisi',
  'gamification.streaks.learning': 'Öğrenme Serisi',
  'gamification.streaks.days': '{{count}} gün',
  'gamification.streaks.longest': 'En uzun: {{count}} gün',
  'gamification.streaks.keepGoing': 'Devam edin!',
  'gamification.streaks.broken': 'Seri kırıldı — bugün yeniden başlayın',
  'gamification.streaks.startHint': "Mizanly'yi her gün kullanarak seri başlatın",
  'gamification.xp.title': 'Seviye ve XP',
  'gamification.xp.level': 'Seviye {{level}}',
  'gamification.xp.totalXP': '{{xp}} XP',
  'gamification.xp.nextLevel': 'Sonraki seviyeye {{xp}} XP',
  'gamification.xp.history': 'XP Geçmişi',
  'gamification.xp.earned': '+{{amount}} XP',
  'gamification.xp.startEarning': "Mizanly'yi kullanarak XP kazanmaya başlayın",
  'gamification.achievements.title': 'Başarımlar',
  'gamification.achievements.unlocked': 'Açıldı',
  'gamification.achievements.locked': 'Kilitli',
  'gamification.achievements.unlockedAt': '{{date}} tarihinde açıldı',
  'gamification.achievements.common': 'Yaygın',
  'gamification.achievements.rare': 'Nadir',
  'gamification.achievements.epic': 'Epik',
  'gamification.achievements.legendary': 'Efsanevi',
  'gamification.achievements.categoryContent': 'İçerik',
  'gamification.achievements.categorySocial': 'Sosyal',
  'gamification.achievements.categoryIslamic': 'İslami',
  'gamification.achievements.categoryMilestone': 'Kilometre Taşı',
  'gamification.achievements.categorySpecial': 'Özel',
  'gamification.achievements.startUsing': "Başarımları açmak için Mizanly'yi kullanmaya başlayın",
  'gamification.achievements.noneInCategory': 'Bu kategoride başarım yok',
  'gamification.leaderboard.title': 'Skor Tablosu',
  'gamification.leaderboard.xp': 'En Yüksek XP',
  'gamification.leaderboard.streaks': 'En Uzun Seriler',
  'gamification.leaderboard.helpers': 'En Çok Yardım Edenler',
  'gamification.leaderboard.rank': '#{{rank}}',
  'gamification.challenges.title': 'Meydan Okumalar',
  'gamification.challenges.discover': 'Meydan Okumaları Keşfet',
  'gamification.challenges.create': 'Meydan Okuma Oluştur',
  'gamification.challenges.join': 'Katıl',
  'gamification.challenges.joined': 'Katıldınız!',
  'gamification.challenges.progress': '{{current}}/{{target}}',
  'gamification.challenges.completed': 'Tamamlandı!',
  'gamification.challenges.participants': '{{count}} katılımcı',
  'gamification.challenges.daysLeft': '{{count}} gün kaldı',
  'gamification.challenges.ended': 'Meydan okuma sona erdi',
  'gamification.challenges.myChallenges': 'Meydan Okumalarım',
  'gamification.settingsSection': 'Oyunlaştırma',
  'gamification.settingsStreaks': 'Seriler',
  'gamification.settingsAchievements': 'Başarımlar',
  'gamification.settingsLeaderboard': 'Skor Tablosu',
  'gamification.settingsChallenges': 'Meydan Okumalar',
  'gamification.settingsXPHistory': 'XP Geçmişi',
  'gamification.settingsProfile': 'Profil Özelleştirme',

  // ===== NOTIFICATIONS =====
  'notifications.title': 'Bildirimler',
  'notifications.all': 'Tümü',
  'notifications.mentions': 'Bahsetmeler',
  'notifications.verified': 'Doğrulanmış',
  'notifications.today': 'Bugün',
  'notifications.yesterday': 'Dün',
  'notifications.thisWeek': 'Bu Hafta',
  'notifications.earlier': 'Daha Önce',
  'notifications.likedYourPost': 'gönderinizi beğendi',
  'notifications.commentedOnPost': 'gönderinize yorum yaptı',
  'notifications.startedFollowing': 'sizi takip etmeye başladı',
  'notifications.requestedToFollow': 'sizi takip etmek istiyor',
  'notifications.acceptedFollowRequest': 'takip isteğinizi kabul etti',
  'notifications.mentionedYou': 'sizi etiketledi',
  'notifications.repliedToComment': 'yorumunuza yanıt verdi',
  'notifications.repostedThread': 'gönderi dizinizi yeniden paylaştı',
  'notifications.quotedThread': 'gönderi dizinizden alıntı yaptı',
  'notifications.repliedToThread': 'gönderi dizinize yanıt verdi',
  'notifications.invitedToCircle': 'sizi çevreye davet etti',
  'notifications.joinedCircle': 'çevrenize katıldı',
  'notifications.sentMessage': 'size mesaj gönderdi',
  'notifications.postedInChannel': 'kanalda paylaşım yaptı',
  'notifications.wentLive': 'canlı yayına başladı',
  'notifications.interactedWithYou': 'sizinle etkileşime geçti',
  'notifications.someone': 'Birisi',
  'notifications.others': 'diğer kişi',
  'notifications.accept': 'Kabul Et',
  'notifications.decline': 'Reddet',
  'notifications.accepted': 'Kabul Edildi',
  'notifications.declined': 'Reddedildi',
  'notifications.markAllRead': 'Tümünü Okundu İşaretle',
  'notifications.markAllReadAccessibility': 'Tüm bildirimleri okundu olarak işaretle',
  'notifications.noNotifications': 'Bildirim yok',
  'notifications.noNotificationsSubtitle': 'Bildirimleriniz burada görünecek',
  'notifications.loadFailed': 'Bildirimler yüklenemedi',
  'notifications.checkConnection': 'Bağlantınızı kontrol edin',
  'notifications.comments': 'Yorumlar',
  'notifications.calls': 'Aramalar',
  'notifications.events': 'Etkinlikler',
  'notifications.security': 'Güvenlik',
  'notifications.promotions': 'Promosyonlar',

  // ===== SETTINGS =====
  'settings.title': 'Ayarlar',
  'settings.account': 'Hesap',
  'settings.privacy': 'Gizlilik',
  'settings.security': 'Güvenlik',
  'settings.appearance': 'Görünüm',
  'settings.language': 'Dil',
  'settings.region': 'Bölge',
  'settings.timezone': 'Saat Dilimi',
  'settings.currency': 'Para Birimi',
  'settings.units': 'Birimler',
  'settings.accessibility': 'Erişilebilirlik',
  'settings.dataUsage': 'Veri Kullanımı',
  'settings.storage': 'Depolama',
  'settings.cache': 'Önbellek',
  'settings.permissions': 'İzinler',
  'settings.about': 'Hakkında',
  'settings.help': 'Yardım',
  'settings.feedback': 'Geri Bildirim',
  'settings.rate': 'Puanla',
  'settings.share': 'Paylaş',
  'settings.invite': 'Davet Et',
  'settings.logout': 'Çıkış Yap',
  'settings.deleteAccount': 'Hesabı Sil',
  'settings.deactivateAccount': 'Hesabı Devre Dışı Bırak',
  'settings.reactivateAccount': 'Hesabı Yeniden Etkinleştir',
  'settings.downloadData': 'Verileri İndir',
  'settings.clearData': 'Verileri Temizle',
  'settings.reset': 'Sıfırla',
  'settings.restore': 'Geri Yükle',
  'settings.manageSubscriptions': 'Abonelikleri Yönet',
  'settings.paymentMethods': 'Ödeme Yöntemleri',
  'settings.taxDocuments': 'Vergi Belgeleri',
  'settings.termsOfService': 'Kullanım Şartları',
  'settings.privacyPolicy': 'Gizlilik Politikası',
  'settings.cookiePolicy': 'Çerez Politikası',
  'settings.communityGuidelines': 'Topluluk Kuralları',
  'settings.copyrightPolicy': 'Telif Hakkı Politikası',
  'settings.trademarkPolicy': 'Marka Politikası',
  'settings.patentPolicy': 'Patent Politikası',
  'settings.licenseAgreement': 'Lisans Sözleşmesi',
  'settings.contentPreferences': 'İçerik Tercihleri',
  'settings.drafts': 'Taslaklar',
  'settings.archive': 'Arşiv',
  'settings.watchHistory': 'İzleme Geçmişi',
  'settings.privateAccount': 'Gizli Hesap',
  'settings.followRequests': 'Takip İstekleri',
  'settings.blockedKeywords': 'Engellenen Anahtar Kelimeler',
  'settings.blockedAccounts': 'Engellenen Hesaplar',
  'settings.mutedAccounts': 'Sessize Alınan Hesaplar',
  'settings.circles': 'Çevreler',
  'settings.likes': 'Beğeniler',
  'settings.comments': 'Yorumlar',
  'settings.newFollowers': 'Yeni Takipçiler',
  'settings.mentions': 'Bahsetmeler',
  'settings.messages': 'Mesajlar',
  'settings.filterSensitiveContent': 'Hassas İçeriği Filtrele',
  'settings.reduceMotion': 'Hareketi Azalt',
  'settings.analytics': 'Analitik',
  'settings.broadcastChannels': 'Yayın Kanalları',
  'settings.myReports': 'Şikâyetlerim',
  'settings.saved': 'Kaydedilenler',
  'settings.signOut': 'Çıkış Yap',
  'settings.version': 'Sürüm',
  'settings.licenses': 'Lisanslar',
  'settings.confirmSignOut': 'Çıkış yapmak istediğinizden emin misiniz?',
  'settings.deactivate': 'Devre Dışı Bırak',
  'settings.deactivateMessage': 'Hesabınız devre dışı bırakılacak. Tekrar giriş yaparak yeniden etkinleştirebilirsiniz.',
  'settings.delete': 'Sil',
  'settings.deleteMessage': 'Hesabınız ve tüm verileriniz kalıcı olarak silinecek.',
  'settings.deleteConfirmTitle': 'Emin misiniz?',
  'settings.deleteConfirmMessage': 'Bu işlem geri alınamaz.',
  'settings.confirmDelete': 'Evet, Hesabı Sil',
  'settings.versionLabel': 'Mizanly v1.0.0',
  'settings.sections.content': 'İçerik',
  'settings.sections.profile': 'Profil',
  'settings.sections.blockedMuted': 'Engellenenler ve Sessizler',
  'settings.sections.closeFriends': 'Yakın Arkadaşlar',
  'settings.sections.creator': 'İçerik Üretici',
  'settings.sections.wellbeing': 'İyi Oluş',
  'settings.sections.ai': 'Yapay Zekâ',
  'settings.hints.themeDarkMode': 'Tema ve karanlık mod',
  'settings.hints.savedPosts': 'Kaydedilen gönderiler',
  'settings.hints.shareProfile': 'Profilinizi paylaşın',
  'settings.hints.privateAccount': 'Sadece onaylanan takipçiler görebilir',
  'settings.hints.followRequests': 'Bekleyen takip istekleri',
  'settings.hints.blockedKeywords': 'İçerikten gizlenen kelimeler',
  'settings.hints.circles': 'Yakın arkadaş çevreleri',
  'settings.hints.filterSensitiveContent': 'Hassas içeriği otomatik gizle',
  'settings.hints.reduceMotion': 'Animasyonları azalt',
  'settings.hints.account': 'Hesap bilgileri ve güvenlik',

  // ===== MONETIZATION =====
  'monetization.tips': 'Bahşişler',
  'monetization.membership': 'Üyelik',
  'monetization.subscription': 'Abonelik',
  'monetization.donation': 'Bağış',
  'monetization.payment': 'Ödeme',
  'monetization.revenue': 'Gelir',
  'monetization.earnings': 'Kazançlar',
  'monetization.payout': 'Ödeme',
  'monetization.balance': 'Bakiye',
  'monetization.withdraw': 'Çekim',
  'monetization.transfer': 'Transfer',
  'monetization.invoice': 'Fatura',
  'monetization.receipt': 'Makbuz',
  'monetization.refund': 'İade',
  'monetization.tax': 'Vergi',
  'monetization.fee': 'Ücret',
  'monetization.commission': 'Komisyon',
  'monetization.discount': 'İndirim',
  'monetization.coupon': 'Kupon',
  'monetization.promo': 'Promosyon',

  // ===== AI =====
  'ai.title': 'Yapay Zekâ Asistanı',
  'ai.avatar.title': 'Yapay Zekâ Avatarı',

  // ===== SEARCH =====
  'search.people': 'Kişiler',
  'search.hashtags': 'Hashtagler',
  'search.posts': 'Gönderiler',
  'search.threads': 'Gönderi Dizileri',
  'search.reels': 'Reels',
  'search.videos': 'Videolar',
  'search.channels': 'Kanallar',
  'search.placeholder': 'Ara...',
  'search.followers': 'takipçi',
  'search.following': 'takip edilen',
  'search.views': 'görüntülenme',
  'search.subscribers': 'abone',
  'search.videosCount': 'video',
  'search.trending': 'Trend',
  'search.clearAll': 'Tümünü Temizle',
  'search.noResultsFor': '"{{query}}" için {{type}} sonucu bulunamadı',
  'search.tryDifferent': 'Farklı bir arama deneyin',
  'search.searchFailed': 'Arama başarısız',
  'search.checkConnection': 'Bağlantınızı kontrol edin',
  'search.recentSearches': 'Son Aramalar',
  'search.noRecentSearches': 'Son arama yok',
  'search.noCaption': 'Açıklama yok',
  'search.searchForPeopleAndTopics': 'Kişi ve konu arayın',

  // ===== PARENTAL CONTROLS =====
  'parentalControls.title': 'Ebeveyn Kontrolleri',
  'parentalControls.settingsLabel': 'Ebeveyn Kontrolleri',
  'parentalControls.settingsHint': 'Çocuk hesaplarını ve kısıtlamaları yönetin',
  'parentalControls.enterPin': 'PIN Girin',
  'parentalControls.enterPinSubtitle': '4 haneli ebeveyn PIN kodunuzu girin',
  'parentalControls.setPin': 'PIN Belirleyin',
  'parentalControls.createPin': 'Ebeveyn erişimi için 4 haneli PIN oluşturun',
  'parentalControls.confirmPin': 'PIN Onayı',

  // ===== SERIES =====
  'series.discoverTitle': 'Seriler',
  'series.episodes': 'bölüm',
  'series.followers': 'takipçi',
  'series.follow': 'Takip Et',
  'series.following': 'Takip Ediliyor',
  'series.empty': 'Seri bulunamadı',
  'series.emptySub': 'Daha sonra yeni içerik için tekrar kontrol edin',
  'series.noEpisodes': 'Henüz bölüm yok',
  'series.episodesHint': 'Bölümler yayınlandığında burada görünecek',

  // ===== ORDERS =====
  'orders.title': 'Siparişlerim',
  'orders.empty': 'Henüz sipariş yok',
  'orders.emptySub': 'Siparişleriniz burada görünecek',
  'orders.pending': 'Beklemede',
  'orders.paid': 'Ödendi',
  'orders.shipped': 'Kargoda',
  'orders.delivered': 'Teslim Edildi',
  'orders.cancelled': 'İptal Edildi',

  // ===== MARKETPLACE =====
  'marketplace.title': 'Pazar Yeri',
  'marketplace.searchPlaceholder': 'Ürün ara...',
  'marketplace.empty': 'Ürün bulunamadı',
  'marketplace.emptySub': 'Farklı bir arama veya kategori deneyin',
  'marketplace.muslimOwned': 'Müslüman İşletme',
  'marketplace.halalCertified': 'Helal Sertifikalı',
  'marketplace.reviews': '{{count}} değerlendirme',
  'marketplace.buyNow': 'Şimdi Al',
  'marketplace.seller': 'Satıcı',
  'marketplace.notFound': 'Ürün bulunamadı',
  'marketplace.categoryAll': 'Tümü',
  'marketplace.categoryFood': 'Yemek',
  'marketplace.categoryClothing': 'Giyim',
  'marketplace.categoryBooks': 'Kitaplar',
  'marketplace.categoryArt': 'Sanat',
  'marketplace.categoryElectronics': 'Elektronik',
  'marketplace.categoryServices': 'Hizmetler',

  // ===== QIBLA =====
  'qibla.title': 'Kıble Yönü',
  'qibla.bearing': '{{degrees}}° {{direction}}',
  'qibla.distanceToKaaba': "Kâbe'ye {{km}} km",
  'qibla.aligned': 'Kıbleye dönüksünüz',
  'qibla.calibrate': 'Kalibre etmek için telefonunuzu 8 şeklinde hareket ettirin',

  // ===== QURAN PLAN =====
  'quranPlan.choosePlan': 'Planınızı Seçin',
  'quranPlan.30day': '30 Gün',
  'quranPlan.60day': '60 Gün',
  'quranPlan.90day': '90 Gün',
  'quranPlan.pagesPerDay': '{{count}} sayfa/gün',

  // ===== HAJJ =====
  'hajj.stepTitle': 'Adım {{step}}: {{name}}',
  'hajj.progress': '%{{percent}} Tamamlandı',
  'hajj.duas': 'Dualar ve Yakarışlar',
  'hajj.checklist': 'Kontrol Listesi',
  'hajj.markComplete': 'Adımı Tamamla',

  // ===== CHARITY =====
  'charity.title': 'Sadaka',
  'charity.donate': 'Bağış Yap',
  'charity.donateNow': 'Şimdi Bağış Yap',

  // ===== TAFSIR =====
  'tafsir.title': 'Tefsir',
  'tafsir.viewTafsir': 'Tefsiri Gör',
  'tafsir.source': 'Kaynak',
  'tafsir.filterSources': 'Kaynakları Filtrele',
  'tafsir.noTafsir': 'Bu ayet için tefsir mevcut değil',

  // ===== CLEAR MODE =====
  'clearMode.show': 'Kontrolleri göstermek için dokunun',
  'clearMode.hide': 'Kontrolleri gizlemek için dokunun',

  // ===== MINI PLAYER =====
  'miniPlayer.playing': 'Şu anda çalıyor',
  'miniPlayer.swipeToDismiss': 'Kapatmak için aşağı kaydırın',

  // ===== HIJRI =====
  'hijri.noEvents': 'Bu ay etkinlik yok',

  // ===== EID CARDS =====
  'eidCards.preview': 'İçeriğiniz burada',
  'eidCards.pickOccasion': 'Vesile Seçin',

  // ===== CONTACT SYNC =====
  'contactSync.title': 'Arkadaşları Bul',
  'contactSync.scanning': 'Kişiler taranıyor...',
  'contactSync.found': "Mizanly'de {{count}} arkadaş bulundu",
  'contactSync.noResults': "Mizanly'de arkadaş bulunamadı",

  // ===== BIOMETRIC =====
  'biometric.title': 'Uygulama Kilidi',
  'biometric.settingsLabel': 'Uygulama Kilidi',
  'biometric.faceId': 'Face ID',
  'biometric.fingerprint': 'Parmak İzi',
  'biometric.testAuth': 'Kimlik Doğrulamayı Test Et',
  'biometric.biometricNotAvailable': 'Bu cihazda biyometrik kimlik doğrulama mevcut değil',

  // ===== CROSS POST =====
  'crossPost.title': 'Çapraz Paylaşım',
  'crossPost.captionOverride': 'Açıklama (isteğe bağlı)',
  'crossPost.captionPlaceholder': 'Farklı bir açıklama yazın...',
  'crossPost.post': 'Çapraz Paylaş',
  'crossPost.posting': 'Çapraz paylaşılıyor...',
  'crossPost.success': 'Başarıyla çapraz paylaşıldı!',
  'crossPost.noSpaces': 'En az bir alan seçin',
  'crossPost.saf': 'Saf (Akış)',
  'crossPost.majlis': 'Meclis (Gönderi Dizileri)',
  'crossPost.bakra': 'Bakra (Reels)',
  'crossPost.minbar': 'Minber (Videolar)',

  // ===== QUIET MODE =====
  'quietMode.title': 'Sessiz Mod',
  'quietMode.settingsLabel': 'Sessiz Mod',
  'quietMode.settingsHint': 'Bildirimleri duraklat ve otomatik yanıt ayarla',
  'quietMode.schedule': 'Zamanlama',
  'quietMode.endTime': 'Bitiş Saati',
  'quietMode.autoReplyPlaceholder': 'Mola veriyorum. Daha sonra yanıt vereceğim.',

  // ===== SCREEN TIME =====
  'screenTime.title': 'Ekran Süresi',
  'screenTime.settingsLabel': 'Ekran Süresi',
  'screenTime.settingsHint': 'Günlük kullanımınızı takip edin',
  'screenTime.thisWeek': 'Bu Hafta',
  'screenTime.avgDaily': 'Günlük Ortalama',

  // ===== PIP =====
  'pip.enter': 'Resim İçinde Resim',
  'pip.exit': "PiP'den Çık",
  'pip.notSupported': 'Bu cihazda PiP desteklenmiyor',
  'pip.activeHint': 'Video resim içinde resim modunda oynatılıyor',

  // ===== AMBIENT =====
  'ambient.title': 'Ortam Modu',
  'ambient.toggle': 'Ortam Modu',
  'ambient.on': 'Ortam modu açık',
  'ambient.off': 'Ortam modu kapalı',

  // ===== UNDO SEND =====
  'undoSend.undo': 'Geri Al',

  // ===== MUTE CONVERSATION =====
  'muteConversation.muted': 'Sohbet sessize alındı',
  'muteConversation.unmuted': 'Sohbet sesi açıldı',
  'muteConversation.hint': 'Bu sohbet için bildirim almayacaksınız',

  // ===== HIDE REPLY =====
  'hideReply.unhide': 'Yanıtı göster',
  'hideReply.viewHidden': 'Gizli yanıtları gör',
  'hideReply.noHidden': 'Gizli yanıt yok',

  // ===== DM NOTES =====
  'dmNotes.title': 'DM Notu',
  'dmNotes.expiry': 'Süre dolumu',
  'dmNotes.expiryOptions.1h': '1 saat',
  'dmNotes.expiryOptions.4h': '4 saat',
  'dmNotes.expiryOptions.12h': '12 saat',
  'dmNotes.expiryOptions.24h': '24 saat',
  'dmNotes.expiryOptions.48h': '48 saat',
  'dmNotes.expiryOptions.72h': '72 saat',

  // ===== WIDGETS =====
  'widgets.setupHint': 'Ana ekranınızdan widget ekleyin',
  'widgets.minutesRemaining': '{{minutes}} dk',

  // ===== AUTOPLAY =====
  'autoPlaySettings.wifi': 'Sadece WiFi',
  'autoPlaySettings.hint': 'Videoların ve reellerin ne zaman otomatik oynatılacağını kontrol edin',

  // ===== NASHEED =====
  'nasheed.settingsLabel': 'İlahi Modu',

  // ===== DOWNLOADS =====
  'downloads.title': 'İndirilenler',
  'downloads.storageUsed': '{{used}} / {{total}} kullanıldı',
  'downloads.complete': 'Tamamlandı',
  'downloads.failed': 'Başarısız',
  'downloads.viewOriginal': 'Orijinali Gör',
  'downloads.empty': 'Henüz indirme yok',

  // ===== SHARE RECEIVE =====
  'shareReceive.title': "Mizanly'ye Paylaş",
  'shareReceive.selectSpace': 'Bir Alan Seçin',
  'shareReceive.saf': 'Saf — Fotoğraf ve Akış',
  'shareReceive.bakra': 'Bakra — Kısa Video',
  'shareReceive.addCaption': 'Açıklama ekleyin...',
  'shareReceive.urlPreview': 'Bağlantı Önizleme',
  'shareReceive.noContent': 'Paylaşılacak içerik yok',

  // ===== CREATE REEL =====
  'createReel.title': 'Reel Oluştur',
  'createReel.customThumbnail': 'Özel',
  'createReel.normalizeAudio': 'Ses normalleştirme',
  'createReel.normalizeAudioDesc': 'Tutarlı ses seviyeleri',
  'createReel.selectVideo': 'Video seçin',
  'createReel.videoRequirements': 'Maks. 60 saniye, dikey format',
  'createReel.selectThumbnail': 'Küçük resim seçin',
  'createReel.caption': 'Açıklama',
  'createReel.captionPlaceholder': 'Reeliniz hakkında bir şeyler yazın...',
  'createReel.hashtag': 'Hashtag',
  'createReel.mention': 'Etiketle',
  'createReel.music': 'Müzik',
  'createReel.duet': 'Düet',
  'createReel.tags': 'Etiketler',
  'createReel.permissionRequired': 'İzin gerekli',
  'createReel.permissionMessage': 'Reel oluşturmak için medya kütüphanesi erişimi gerekli',
  'createReel.uploadFailed': 'Yükleme başarısız',
  'createReel.noVideo': 'Video yok',
  'createReel.selectVideoFirst': 'Önce bir video seçin',
  'createReel.captionTooLong': 'Açıklama çok uzun',
  'createReel.maxCharacters': 'Maksimum {{max}} karakter',
  'createReel.discardTitle': 'Silmek istiyor musunuz?',
  'createReel.discardMessage': 'Kaydedilmemiş değişiklikleriniz kaybolacak.',
  'createReel.keepEditing': 'Düzenlemeye devam et',
  'createReel.discard': 'Sil',

  // ===== CREATE VIDEO =====
  'createVideo.customThumbnail': 'Özel',
  'createVideo.normalizeAudio': 'Ses normalleştirme',
  'createVideo.normalizeAudioDesc': 'Tutarlı ses seviyeleri',

  // ===== CHANNEL =====
  'channel.notFoundSubtitle': 'Bu kanal kaldırılmış veya mevcut değil',
  'channel.noVideosSubtitle': 'Bu kanal henüz video yüklememiş',
  'channel.noPlaylistsYet': 'Henüz oynatma listesi yok',
  'channel.noPlaylistsSubtitle': 'Bu kanal henüz oynatma listesi oluşturmamış',
  'channel.joined': 'Katıldı',

  // ===== CHANNEL TRAILER =====
  'channelTrailer.currentTrailer': 'Mevcut Fragman',
  'channelTrailer.noTrailer': 'Fragman ayarlanmadı',
  'channelTrailer.trailerHint': 'Abone olmayanlar kanalınızda bu videoyu görecek',
};

// Apply path-based translations
function applyPathTranslations(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'object' && value !== null) {
      result[key] = applyPathTranslations(value, path);
    } else if (typeof value === 'string') {
      result[key] = pathTranslations[path] || value;
    } else {
      result[key] = value;
    }
  }
  return result;
}

// First apply dictionary-based translations
const dict = {
  'Save': 'Kaydet', 'Cancel': 'İptal', 'Delete': 'Sil', 'Done': 'Tamam',
  'Next': 'İleri', 'Back': 'Geri', 'Search': 'Ara', 'Share': 'Paylaş',
  'Edit': 'Düzenle', 'Settings': 'Ayarlar', 'Close': 'Kapat', 'Confirm': 'Onayla',
  'Yes': 'Evet', 'No': 'Hayır', 'OK': 'Tamam', 'Continue': 'Devam',
  'Skip': 'Atla', 'Select': 'Seç', 'Add': 'Ekle', 'Remove': 'Kaldır',
  'Create': 'Oluştur', 'Update': 'Güncelle', 'Submit': 'Gönder', 'Send': 'Gönder',
  'Post': 'Paylaş', 'Reply': 'Yanıtla', 'Like': 'Beğen', 'Follow': 'Takip Et',
  'Unfollow': 'Takibi Bırak', 'Block': 'Engelle', 'Unblock': 'Engeli Kaldır',
  'Report': 'Şikâyet Et', 'Hide': 'Gizle', 'Show': 'Göster', 'Enable': 'Etkinleştir',
  'Disable': 'Devre Dışı', 'Allow': 'İzin Ver', 'Deny': 'Reddet',
  'Active': 'Aktif', 'Inactive': 'Pasif', 'Online': 'Çevrimiçi', 'Offline': 'Çevrimdışı',
  'Today': 'Bugün', 'Yesterday': 'Dün', 'Tomorrow': 'Yarın', 'Now': 'Şimdi',
  'Later': 'Sonra', 'Never': 'Asla', 'All': 'Tümü', 'None': 'Hiçbiri',
  'First': 'İlk', 'Last': 'Son', 'Previous': 'Önceki', 'Start': 'Başla',
  'Pause': 'Duraklat', 'Stop': 'Durdur', 'Play': 'Oynat', 'Upload': 'Yükle',
  'Download': 'İndir', 'Refresh': 'Yenile', 'Success': 'Başarılı',
  'Warning': 'Uyarı', 'Help': 'Yardım', 'About': 'Hakkında',
  'Version': 'Sürüm', 'Language': 'Dil', 'Dark': 'Koyu', 'Light': 'Açık',
  'Notifications': 'Bildirimler', 'Location': 'Konum', 'Camera': 'Kamera',
  'Photos': 'Fotoğraflar', 'Calendar': 'Takvim', 'Contacts': 'Kişiler',
  'Following': 'Takip Edilen', 'Followers': 'Takipçiler', 'Bookmark': 'Yer İşareti',
  'Archive': 'Arşiv', 'Mute': 'Sessize Al', 'Pin': 'Sabitle', 'Trending': 'Trend',
  'Public': 'Herkese Açık', 'Private': 'Gizli', 'Subscribe': 'Abone Ol',
  'Subscribed': 'Abone', 'Videos': 'Videolar', 'Channel': 'Kanal',
  'Channels': 'Kanallar', 'Playlists': 'Oynatma Listeleri', 'Library': 'Kütüphane',
  'Live': 'Canlı', 'Quality': 'Kalite', 'Speed': 'Hız',
  'Marketplace': 'Pazar Yeri', 'Products': 'Ürünler', 'Seller': 'Satıcı',
  'Discover': 'Keşfet', 'Explore': 'Keşfet', 'Mentions': 'Bahsetmeler',
  'Verified': 'Doğrulanmış', 'Messages': 'Mesajlar', 'Groups': 'Gruplar',
  'Profile': 'Profil', 'Feed': 'Akış', 'Stories': 'Hikâyeler',
  'Achievements': 'Başarımlar', 'Challenges': 'Meydan Okumalar',
  'Leaderboard': 'Skor Tablosu', 'Level': 'Seviye',
  'Email': 'E-posta', 'Phone': 'Telefon', 'Password': 'Şifre',
  'Username': 'Kullanıcı Adı', 'Video': 'Video',
  'Content': 'İçerik', 'Privacy': 'Gizlilik', 'Account': 'Hesap',
  'Security': 'Güvenlik', 'Pending': 'Beklemede', 'Paid': 'Ödendi',
  'Shipped': 'Kargoda', 'Delivered': 'Teslim Edildi', 'Cancelled': 'İptal Edildi',
  'Comments': 'Yorumlar', 'Events': 'Etkinlikler', 'Promotions': 'Promosyonlar',
  'Tips': 'Bahşişler', 'Membership': 'Üyelik', 'Subscription': 'Abonelik',
  'Donation': 'Bağış', 'Payment': 'Ödeme', 'Region': 'Bölge',
  'Timezone': 'Saat Dilimi', 'Currency': 'Para Birimi', 'Units': 'Birimler',
  'Appearance': 'Görünüm', 'Custom': 'Özel',
};

function translateWithDict(obj) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'object' && value !== null) {
      result[key] = translateWithDict(value);
    } else if (typeof value === 'string') {
      result[key] = dict[value] || value;
    } else {
      result[key] = value;
    }
  }
  return result;
}

// Step 1: Dictionary-based translation
let tr = translateWithDict(en);
// Step 2: Path-based translation (overrides dictionary for specific paths)
tr = applyPathTranslations(tr);

fs.writeFileSync('apps/mobile/src/i18n/tr.json', JSON.stringify(tr, null, 2), 'utf8');

// Count coverage
let total = 0, translated = 0;
function count(enObj, trObj) {
  for (const [key, value] of Object.entries(enObj)) {
    if (typeof value === 'object' && value !== null) {
      count(value, trObj[key] || {});
    } else if (typeof value === 'string') {
      total++;
      if (trObj[key] !== value) translated++;
    }
  }
}
count(en, tr);
console.log(`Total: ${total}, Translated: ${translated}, Remaining: ${total - translated}`);
console.log(`Coverage: ${((translated / total) * 100).toFixed(1)}%`);
