import { useState, useEffect, useCallback, useRef } from 'react';
import { AppState, Platform } from 'react-native';
import {
  Room,
  RoomEvent,
  Track,
  LocalAudioTrack,
  LocalParticipant,
  RemoteParticipant,
  DisconnectReason,
} from 'livekit-client';
import { AudioSession, RNE2EEManager, RNKeyProvider } from '@livekit/react-native';
import { KrispNoiseFilter, isKrispNoiseFilterSupported } from '@livekit/react-native-krisp-noise-filter';
import { livekitApi } from '@/services/livekit';
import {
  generateCallUUID,
  reportOutgoingCall,
  reportCallConnected,
  endCall as endCallKit,
} from '@/services/callkit';

// Base64 decode that works in React Native (no atob)
export function base64ToBytes(base64: string): Uint8Array {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const clean = base64.replace(/[=\s]/g, '');
  const bytes: number[] = [];
  for (let i = 0; i < clean.length; i += 4) {
    const a = chars.indexOf(clean[i]);
    const b = chars.indexOf(clean[i + 1]);
    const c = i + 2 < clean.length ? chars.indexOf(clean[i + 2]) : 0;
    const d = i + 3 < clean.length ? chars.indexOf(clean[i + 3]) : 0;
    bytes.push((a << 2) | (b >> 4));
    if (i + 2 < clean.length) bytes.push(((b & 15) << 4) | (c >> 2));
    if (i + 3 < clean.length) bytes.push(((c & 3) << 6) | d);
  }
  return new Uint8Array(bytes);
}

// ── Types ──

export type CallType = 'VOICE' | 'VIDEO' | 'BROADCAST';
export type CallStatus =
  | 'idle'
  | 'creating'
  | 'ringing'
  | 'connecting'
  | 'connected'
  | 'reconnecting'
  | 'ended'
  | 'failed';

export interface CallParticipant {
  identity: string;
  isSpeaking: boolean;
  isMuted: boolean;
  isCameraOn: boolean;
  isScreenSharing: boolean;
  connectionQuality: string;
  participant: RemoteParticipant;
}

export interface DataChannelMessage {
  topic: string;
  payload: Record<string, unknown>;
  senderIdentity: string;
}

interface UseLiveKitCallOptions {
  isIncoming?: boolean;
  roomName?: string;
  sessionId?: string;
  /** Call type for incoming calls (passed from push notification) */
  callType?: CallType;
}

interface UseLiveKitCallReturn {
  status: CallStatus;
  sessionId: string | null; // [N1] Exposed for caller-side poll
  room: Room | null;
  localParticipant: LocalParticipant | null;
  remoteParticipants: CallParticipant[];
  duration: number;
  error: string | null;
  connectionQuality: string;
  isE2EEEnabled: boolean;
  e2eeVerificationEmojis: string[];
  isMuted: boolean;
  isCameraOn: boolean;
  isSpeakerOn: boolean;
  isScreenSharing: boolean;
  startCall: (params: {
    targetUserId?: string;
    participantIds?: string[];
    callType: CallType;
    conversationId?: string;
  }) => Promise<void>;
  joinCall: () => Promise<void>;
  endCall: () => Promise<void>;
  declineCall: () => Promise<void>;
  toggleMute: () => Promise<void>;
  toggleCamera: () => Promise<void>;
  flipCamera: () => Promise<void>;
  toggleSpeaker: () => Promise<void>;
  toggleScreenShare: () => Promise<void>;
  sendDataMessage: (topic: string, payload: Record<string, unknown>) => void;
  onDataMessage: (handler: (msg: DataChannelMessage) => void) => () => void;
}

// ── SAS Emoji Verification ──
//
// [F2/F4 TRUST MODEL DOCUMENTATION]
// The encryption key is generated by the Go server (crypto/rand, 32 bytes) and distributed
// to both parties over HTTPS. This is SERVER-MEDIATED ENCRYPTION, not true end-to-end
// encryption. The server generates and knows the key.
//
// What the emoji verification proves:
//   - Both clients received the SAME key from the server (protects against CDN/proxy
//     substitution, network middlebox attacks, and server bugs that send different keys)
//
// What it does NOT prove:
//   - Protection against a compromised server (which could send different keys to each party)
//   - Protection against an attacker who controls the server infrastructure
//
// For true E2EE, clients would need to perform ECDH key exchange (like Signal's X3DH).
// That is a future architectural change tracked separately.

export const SAS_EMOJIS = [
  '\u{1F436}', '\u{1F431}', '\u{1F43B}', '\u{1F43C}', '\u{1F42F}',
  '\u{1F981}', '\u{1F434}', '\u{1F42E}', '\u{1F437}', '\u{1F430}',
  '\u{1F98A}', '\u{1F989}', '\u{1F426}', '\u{1F427}', '\u{1F41F}',
  '\u{1F419}', '\u{1F40C}', '\u{1F41D}', '\u{1F98B}', '\u{1F333}',
  '\u{1F335}', '\u{1F340}', '\u{1F341}', '\u{1F344}', '\u{1F30D}',
  '\u{1F319}', '\u{2600}',  '\u{2B50}',  '\u{1F308}', '\u{2602}',
  '\u{2744}',  '\u{1F525}',
];

export function deriveVerificationEmojis(sharedKeyBase64: string): string[] {
  const keyBytes = base64ToBytes(sharedKeyBase64);
  const emojis: string[] = [];
  for (let i = 0; i < 7; i++) {
    const byteIdx = i * 2;
    const value = byteIdx + 1 < keyBytes.length
      ? (keyBytes[byteIdx] << 8 | keyBytes[byteIdx + 1])
      : keyBytes[byteIdx % keyBytes.length];
    emojis.push(SAS_EMOJIS[value % SAS_EMOJIS.length]);
  }
  return emojis;
}

// ── Cleanup helper ──

function cleanupRoom(room: Room | null, keyProvider: RNKeyProvider | null) {
  if (room) {
    try { room.disconnect(); } catch { /* already disconnected */ }
    room.removeAllListeners(); // [F34] remove AFTER disconnect so Disconnected event fires
  }
  if (keyProvider) {
    keyProvider.dispose();
  }
}

// [F38 fix] Import from separate zero-dependency module to avoid circular imports
// between callkit.ts ↔ useLiveKitCall.ts and native module resolution issues in tests.
import { registerActiveRoomCleanup, clearActiveRoomCleanup } from '@/services/activeRoomRegistry';

// ── Hook ──

export function useLiveKitCall(options: UseLiveKitCallOptions = {}): UseLiveKitCallReturn {
  const {
    isIncoming = false,
    roomName: incomingRoomName,
    sessionId: incomingSessionId,
    callType: incomingCallType,
  } = options;

  const [status, setStatus] = useState<CallStatus>('idle');
  const [error, setError] = useState<string | null>(null);
  const [isMuted, setIsMuted] = useState(false);
  const [isCameraOn, setIsCameraOn] = useState(false);
  const [isSpeakerOn, setIsSpeakerOn] = useState(false);
  const [isScreenSharing, setIsScreenSharing] = useState(false);
  const [isE2EEEnabled, setIsE2EEEnabled] = useState(false);
  const [e2eeVerificationEmojis, setE2eeVerificationEmojis] = useState<string[]>([]);
  const [remoteParticipants, setRemoteParticipants] = useState<CallParticipant[]>([]);
  const [connectionQuality, setConnectionQuality] = useState<string>('unknown');
  const [duration, setDuration] = useState(0);
  const [roomState, setRoomState] = useState<Room | null>(null);

  const roomRef = useRef<Room | null>(null);
  const keyProviderRef = useRef<RNKeyProvider | null>(null);
  const roomNameRef = useRef<string | null>(null);
  const sessionIdRef = useRef<string | null>(null); // [N1] Track session ID for caller-side poll
  const durationTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const dataMessageHandlersRef = useRef<Set<(msg: DataChannelMessage) => void>>(new Set());
  const mountedRef = useRef(true);
  const startingRef = useRef(false);
  const callUUIDRef = useRef<string | null>(null);
  // [F3] Track camera-was-on state in a ref (not closure-captured state) for background handler
  const cameraWasOnRef = useRef(false);

  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  // Duration timer
  useEffect(() => {
    if (status === 'connected') {
      durationTimerRef.current = setInterval(() => {
        if (mountedRef.current) setDuration(d => d + 1);
      }, 1000);
    } else {
      if (durationTimerRef.current) {
        clearInterval(durationTimerRef.current);
        durationTimerRef.current = null;
      }
    }
    return () => {
      if (durationTimerRef.current) clearInterval(durationTimerRef.current);
    };
  }, [status]);

  const syncRemoteParticipants = useCallback(() => {
    const room = roomRef.current;
    if (!room) { setRemoteParticipants([]); return; }
    const participants: CallParticipant[] = [];
    room.remoteParticipants.forEach((p) => {
      participants.push({
        identity: p.identity,
        isSpeaking: p.isSpeaking,
        isMuted: !p.isMicrophoneEnabled,
        isCameraOn: p.isCameraEnabled,
        isScreenSharing: p.isScreenShareEnabled,
        connectionQuality: p.connectionQuality,
        participant: p,
      });
    });
    if (mountedRef.current) setRemoteParticipants(participants);
  }, []);

  const configureAudioSession = useCallback(async (isVideo: boolean) => {
    if (Platform.OS === 'ios') {
      await AudioSession.setAppleAudioConfiguration({
        audioCategory: 'playAndRecord',
        audioCategoryOptions: ['allowBluetooth', 'allowBluetoothA2DP', 'defaultToSpeaker'],
        audioMode: isVideo ? 'videoChat' : 'voiceChat',
      });
    }
    await AudioSession.startAudioSession();
  }, []);

  // Connect to room
  const connectToRoom = useCallback(async (
    token: string,
    e2eeKey: string | undefined,
    e2eeSalt: string | undefined,
    callType: CallType,
  ) => {
    const isVideo = callType === 'VIDEO' || callType === 'BROADCAST';
    await configureAudioSession(isVideo);

    // Setup E2EE
    let e2eeManager: RNE2EEManager | undefined;
    // [F5 fix] Hoist keyBytes so we can zero it after setup completes (outside the try block)
    let keyBytes: Uint8Array | null = null;
    if (e2eeKey) {
      // [F1 fix] Use per-session salt from server, NOT a hardcoded constant.
      // Each session generates a unique 16-byte salt (crypto/rand on Go server).
      // This provides domain separation: even if keys were reused across sessions
      // (they aren't — each session gets a fresh 32-byte key), the ratcheted
      // frame keys would differ because the salt is different.
      // ratchetSalt expects a string. The server sends 16 random bytes as base64.
      // We pass the base64 string directly as the salt — it's unique per session and
      // deterministic (both parties get the same base64 from the server).
      // DO NOT decode to bytes then re-encode as UTF-8: random bytes are not valid UTF-8
      // and TextDecoder would produce U+FFFD replacements, destroying uniqueness.
      if (!e2eeSalt) {
        throw new Error('E2EE salt missing from server response — cannot establish encryption');
      }
      const saltString = e2eeSalt;

      keyBytes = base64ToBytes(e2eeKey);
      try {
        const keyProvider = new RNKeyProvider({
          sharedKey: true,
          ratchetSalt: saltString,
          ratchetWindowSize: 16,
          failureTolerance: 10,
        });
        await keyProvider.setSharedKey(keyBytes, 0);
        e2eeManager = new RNE2EEManager(keyProvider, true);
        keyProviderRef.current = keyProvider;
      } catch (err) {
        // [F5 fix] Zero key material even on failure path
        keyBytes.fill(0);
        // [F3 fix] Encryption setup failed — abort the call entirely.
        // A call that the user expects to be encrypted MUST NOT continue unencrypted.
        // The caller will see "Encryption setup failed" and the call won't connect.
        if (mountedRef.current) {
          setIsE2EEEnabled(false);
          setError('Encryption setup failed — call aborted for your safety');
          setStatus('failed');
        }
        throw new Error('E2EE setup failed — refusing to connect unencrypted');
      }
    }

    const room = new Room({
      adaptiveStream: true,
      dynacast: true,
      disconnectOnPageLeave: false,
      ...(e2eeManager ? { encryption: { e2eeManager } } : {}),
    });
    roomRef.current = room;
    if (mountedRef.current) setRoomState(room);

    // [F38 fix] Register global cleanup so CallKit's handleEndCall can disconnect
    // the Room from outside React (lock screen / notification center end).
    registerActiveRoomCleanup(() => {
      cleanupRoom(roomRef.current, keyProviderRef.current);
      roomRef.current = null;
      keyProviderRef.current = null;
      AudioSession.stopAudioSession();
      if (mountedRef.current) {
        setRoomState(null);
        setStatus('ended');
        setRemoteParticipants([]);
      }
    });

    // Event listeners
    room.on(RoomEvent.Connected, () => {
      if (mountedRef.current) setStatus('connected');
      if (callUUIDRef.current) reportCallConnected(callUUIDRef.current);
      syncRemoteParticipants();
    });
    room.on(RoomEvent.Reconnecting, () => { if (mountedRef.current) setStatus('reconnecting'); });
    room.on(RoomEvent.Reconnected, () => { if (mountedRef.current) setStatus('connected'); });
    room.on(RoomEvent.Disconnected, (reason?: DisconnectReason) => {
      if (mountedRef.current) {
        setStatus('ended');
        if (reason === DisconnectReason.SERVER_SHUTDOWN) setError('Call ended by server');
      }
    });
    room.on(RoomEvent.ParticipantConnected, () => syncRemoteParticipants());
    room.on(RoomEvent.ParticipantDisconnected, () => syncRemoteParticipants());
    room.on(RoomEvent.TrackSubscribed, () => syncRemoteParticipants());
    room.on(RoomEvent.TrackUnsubscribed, () => syncRemoteParticipants());
    room.on(RoomEvent.ActiveSpeakersChanged, () => syncRemoteParticipants());
    room.on(RoomEvent.TrackMuted, () => syncRemoteParticipants());
    room.on(RoomEvent.TrackUnmuted, () => syncRemoteParticipants());
    room.on(RoomEvent.ConnectionQualityChanged, (_q, participant) => {
      if (participant instanceof LocalParticipant && mountedRef.current) {
        setConnectionQuality(participant.connectionQuality);
      }
      syncRemoteParticipants();
    });
    room.on(RoomEvent.DataReceived, (payload, participant, _kind, topic) => {
      if (!topic || !participant) return;
      try {
        const decoded = new TextDecoder().decode(payload);
        const parsed = JSON.parse(decoded) as Record<string, unknown>;
        dataMessageHandlersRef.current.forEach(h => h({
          topic, payload: parsed, senderIdentity: participant.identity,
        }));
      } catch (err) {
        // [F25] Log malformed data messages in dev
        if (__DEV__) console.warn('[LiveKit] Malformed data message:', err);
      }
    });

    // Connect
    if (mountedRef.current) setStatus('connecting');
    // [F42 fix] Fail loud if the env var is missing — don't silently connect to a
    // potentially wrong/nonexistent host. The fallback 'wss://mizanly.livekit.cloud'
    // could be a different environment or not exist at all.
    const livekitHost = process.env.EXPO_PUBLIC_LIVEKIT_WS_URL;
    if (!livekitHost) {
      throw new Error('EXPO_PUBLIC_LIVEKIT_WS_URL is not configured — cannot connect to LiveKit');
    }

    try {
      await room.connect(livekitHost, token);
    } catch (connectErr) {
      // [F2] Clean up room on connection failure — don't leak listeners
      cleanupRoom(room, keyProviderRef.current);
      roomRef.current = null;
      keyProviderRef.current = null;
      if (mountedRef.current) setRoomState(null);
      throw connectErr; // Re-throw so startCall/joinCall catches it
    }

    // [F4 fix] Verification emojis — proves both clients received the same key from server.
    // NOTE: This verifies server consistency (both got same key), NOT protection against a
    // compromised server (which could send different keys). See F2 trust model documentation.
    if (e2eeKey && e2eeManager && mountedRef.current) {
      setIsE2EEEnabled(true);
      setE2eeVerificationEmojis(deriveVerificationEmojis(e2eeKey));
    }

    // [F5 fix] Zero key material from JS heap after it's been passed to the native E2EE manager.
    // The native keyProvider now holds the key in C++ memory (via JSI).
    // We can't guarantee V8's GC behavior, but explicit zeroing reduces the window
    // where key bytes are readable in a memory dump.
    if (keyBytes) {
      keyBytes.fill(0);
      keyBytes = null;
    }

    // Enable mic — if permission denied, start with mic off instead of failing the call
    try {
      await room.localParticipant.setMicrophoneEnabled(true);
      if (mountedRef.current) setIsMuted(false);
    } catch {
      if (mountedRef.current) setIsMuted(true);
      if (__DEV__) console.warn('[LiveKit] Mic enable failed — starting muted');
    }

    // Krisp noise filter (LiveKit Cloud only)
    if (isKrispNoiseFilterSupported()) {
      try {
        const micPub = room.localParticipant.getTrackPublication(Track.Source.Microphone);
        const micTrack = micPub?.track;
        if (micTrack && micTrack instanceof LocalAudioTrack) {
          await micTrack.setProcessor(KrispNoiseFilter());
        }
      } catch {
        // Krisp unavailable — proceed without noise suppression
      }
    }

    // Enable camera for video calls — if permission denied, start with camera off
    if (isVideo) {
      try {
        await room.localParticipant.setCameraEnabled(true);
        if (mountedRef.current) {
          setIsCameraOn(true);
          cameraWasOnRef.current = true; // [F3]
        }
      } catch {
        if (mountedRef.current) setIsCameraOn(false);
        if (__DEV__) console.warn('[LiveKit] Camera enable failed — starting with camera off');
      }
    }
  }, [configureAudioSession, syncRemoteParticipants]);

  // ── Start call (caller) ──
  const startCall = useCallback(async (params: {
    targetUserId?: string;
    participantIds?: string[];
    callType: CallType;
    conversationId?: string;
  }) => {
    if (startingRef.current || status !== 'idle') return;
    startingRef.current = true;
    setStatus('creating');
    setError(null);

    try {
      const response = await livekitApi.createRoom({
        targetUserId: params.targetUserId,
        participantIds: params.participantIds,
        callType: params.callType,
        conversationId: params.conversationId,
      });

      roomNameRef.current = response.data.livekitRoomName;
      sessionIdRef.current = response.data.id; // [N1]
      if (mountedRef.current) setStatus('ringing');

      // [F10] Set CallKit UUID BEFORE connectToRoom so the Connected handler has it
      const uuid = generateCallUUID();
      callUUIDRef.current = uuid;
      reportOutgoingCall({
        callUUID: uuid,
        roomName: response.data.livekitRoomName,
        sessionId: response.data.id,
        callType: params.callType === 'BROADCAST' ? 'VOICE' : params.callType as 'VOICE' | 'VIDEO',
        calleeName: 'Call',
        calleeHandle: params.targetUserId || 'group',
      });

      await connectToRoom(response.token, response.e2eeKey, response.e2eeSalt, params.callType);
      // [F1] Reset startingRef on SUCCESS (was only reset on error before)
      startingRef.current = false;
    } catch (err) {
      startingRef.current = false;
      // Clean up CallKit state on failure
      if (callUUIDRef.current) {
        endCallKit(callUUIDRef.current);
        callUUIDRef.current = null;
      }
      if (mountedRef.current) {
        setStatus('failed');
        setError(err instanceof Error ? err.message : 'Failed to start call');
      }
    }
  }, [status, connectToRoom]);

  // ── Join call (callee) ──
  const joinCall = useCallback(async () => {
    if (!incomingRoomName || !incomingSessionId) {
      setError('Missing room name or session ID');
      return;
    }
    setStatus('connecting');
    setError(null);

    try {
      const response = await livekitApi.getToken(incomingRoomName, incomingSessionId);
      roomNameRef.current = incomingRoomName;

      // [F10] Set CallKit UUID for incoming calls too
      const uuid = generateCallUUID();
      callUUIDRef.current = uuid;

      // [F4] Use callType from push params (passed via options), NOT from an extra API call
      const callType = incomingCallType || 'VOICE';

      await connectToRoom(response.token, response.e2eeKey, response.e2eeSalt, callType);
      startingRef.current = false;
    } catch (err) {
      if (callUUIDRef.current) {
        endCallKit(callUUIDRef.current);
        callUUIDRef.current = null;
      }
      if (mountedRef.current) {
        setStatus('failed');
        setError(err instanceof Error ? err.message : 'Failed to join call');
      }
    }
  }, [incomingRoomName, incomingSessionId, incomingCallType, connectToRoom]);

  // ── End call ──
  const endCall = useCallback(async () => {
    const room = roomRef.current;
    const roomName = roomNameRef.current;

    // End native call UI
    if (callUUIDRef.current) {
      endCallKit(callUUIDRef.current);
      callUUIDRef.current = null;
    }

    // [F15 fix] Disconnect locally FIRST, then notify server.
    // Previous order (server first, then disconnect) caused:
    //   - For callers: deleteRoom destroys the LiveKit room → all clients forcefully
    //     disconnected by server → local disconnect runs on dead room
    //   - For callees: leaveRoom marks as left → disconnect fires → participant_left
    //     webhook double-marks
    //
    // New order: disconnect → server notification (fire-and-forget).
    // The participant_left webhook handles server-side state as primary path.
    // The explicit server call is a backup that also handles room deletion (callers).
    cleanupRoom(room, keyProviderRef.current);
    roomRef.current = null;
    keyProviderRef.current = null;
    startingRef.current = false;
    cameraWasOnRef.current = false;
    clearActiveRoomCleanup(); // [F38] Cleanup already done — clear the global registry

    // [F7/F8 fix] Callers end the room for everyone (deleteRoom).
    // Callees leave gracefully (leaveRoom). Fire-and-forget — don't block on the response.
    if (roomName) {
      const apiCall = isIncoming
        ? livekitApi.leaveRoom(roomName)
        : livekitApi.deleteRoom(roomName);
      apiCall.catch(() => { /* room may already be closed */ });
      roomNameRef.current = null;
    }

    await AudioSession.stopAudioSession();

    if (mountedRef.current) {
      setRoomState(null);
      setStatus('ended');
      setIsE2EEEnabled(false);
      setE2eeVerificationEmojis([]);
      setRemoteParticipants([]);
      setDuration(0);
    }
  }, [isIncoming]);

  // [F7 fix] Decline call — callee leaves without destroying the room for other participants.
  // Uses /leave (marks this user as left) instead of DELETE (which nukes the entire room).
  // In a group call, declining no longer kills the call for everyone.
  const declineCall = useCallback(async () => {
    const roomName = roomNameRef.current || incomingRoomName;
    if (callUUIDRef.current) {
      endCallKit(callUUIDRef.current);
      callUUIDRef.current = null;
    }
    if (roomName) {
      try { await livekitApi.leaveRoom(roomName); } catch { /* best-effort */ }
    }
    if (mountedRef.current) setStatus('ended');
  }, [incomingRoomName]);

  // Toggle mute — uses ref to avoid stale closure on rapid taps
  const isMutedRef = useRef(isMuted);
  isMutedRef.current = isMuted;
  const toggleMute = useCallback(async () => {
    const room = roomRef.current;
    if (!room) return;
    const newMuted = !isMutedRef.current;
    await room.localParticipant.setMicrophoneEnabled(!newMuted);
    if (mountedRef.current) setIsMuted(newMuted);
  }, []);

  // Toggle camera — uses ref to avoid stale closure on rapid taps
  const isCameraOnRef = useRef(isCameraOn);
  isCameraOnRef.current = isCameraOn;
  const toggleCamera = useCallback(async () => {
    const room = roomRef.current;
    if (!room) return;
    const newEnabled = !isCameraOnRef.current;
    await room.localParticipant.setCameraEnabled(newEnabled);
    if (mountedRef.current) {
      setIsCameraOn(newEnabled);
      cameraWasOnRef.current = newEnabled; // [F3] sync ref
    }
  }, []);

  // Flip camera
  const facingModeRef = useRef<'user' | 'environment'>('user');
  const flipCamera = useCallback(async () => {
    const room = roomRef.current;
    if (!room) return;
    const pub = room.localParticipant.getTrackPublication(Track.Source.Camera);
    if (!pub?.track) return;
    facingModeRef.current = facingModeRef.current === 'user' ? 'environment' : 'user';
    const trackAny = pub.track as unknown as Record<string, unknown>;
    if ('restartTrack' in pub.track && typeof trackAny.restartTrack === 'function') {
      await (trackAny.restartTrack as (opts: { facingMode: string }) => Promise<void>)({ facingMode: facingModeRef.current });
    } else {
      await room.localParticipant.setCameraEnabled(false);
      await room.localParticipant.setCameraEnabled(true, { facingMode: facingModeRef.current });
    }
  }, []);

  // Toggle speaker — uses ref to avoid stale closure on rapid taps
  const isSpeakerOnRef = useRef(isSpeakerOn);
  isSpeakerOnRef.current = isSpeakerOn;
  const toggleSpeaker = useCallback(async () => {
    const newSpeaker = !isSpeakerOnRef.current;
    if (Platform.OS === 'ios') {
      await AudioSession.selectAudioOutput(newSpeaker ? 'force_speaker' : 'default');
    } else {
      await AudioSession.selectAudioOutput(newSpeaker ? 'speaker' : 'earpiece');
    }
    if (mountedRef.current) setIsSpeakerOn(newSpeaker);
  }, []);

  // Toggle screen share — uses ref to avoid stale closure on rapid taps
  const isScreenSharingRef = useRef(isScreenSharing);
  isScreenSharingRef.current = isScreenSharing;
  const toggleScreenShare = useCallback(async () => {
    const room = roomRef.current;
    if (!room) return;
    const newSharing = !isScreenSharingRef.current;
    await room.localParticipant.setScreenShareEnabled(newSharing);
    if (mountedRef.current) setIsScreenSharing(newSharing);
  }, []);

  // Send data channel message
  const sendDataMessage = useCallback((topic: string, payload: Record<string, unknown>) => {
    const room = roomRef.current;
    if (!room) return;
    const encoded = new TextEncoder().encode(JSON.stringify(payload));
    room.localParticipant.publishData(encoded, { topic, reliable: true });
  }, []);

  // Register data message handler
  const onDataMessage = useCallback((handler: (msg: DataChannelMessage) => void) => {
    dataMessageHandlersRef.current.add(handler);
    return () => { dataMessageHandlersRef.current.delete(handler); };
  }, []);

  // [F3] Background handler uses ref (not stale closure state) for camera
  useEffect(() => {
    const subscription = AppState.addEventListener('change', (nextState) => {
      const room = roomRef.current;
      if (!room || status !== 'connected') return;

      if (nextState === 'background') {
        if (cameraWasOnRef.current) {
          // [F17] Mute the track instead of disabling to avoid black-frame flash
          const cameraPub = room.localParticipant.getTrackPublication(Track.Source.Camera);
          if (cameraPub) cameraPub.mute();
        }
      } else if (nextState === 'active') {
        if (cameraWasOnRef.current) {
          const cameraPub = room.localParticipant.getTrackPublication(Track.Source.Camera);
          if (cameraPub) cameraPub.unmute();
        }
      }
    });
    return () => subscription.remove();
  }, [status]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      cleanupRoom(roomRef.current, keyProviderRef.current);
      roomRef.current = null;
      keyProviderRef.current = null;
      clearActiveRoomCleanup(); // [F38]
      AudioSession.stopAudioSession();
      if (durationTimerRef.current) clearInterval(durationTimerRef.current);
    };
  }, []);

  return {
    status,
    sessionId: sessionIdRef.current || incomingSessionId || null,
    room: roomState,
    localParticipant: roomState?.localParticipant ?? null,
    remoteParticipants,
    duration,
    error,
    connectionQuality,
    isE2EEEnabled,
    e2eeVerificationEmojis,
    isMuted,
    isCameraOn,
    isSpeakerOn,
    isScreenSharing,
    startCall,
    joinCall,
    endCall,
    declineCall,
    toggleMute,
    toggleCamera,
    flipCamera,
    toggleSpeaker,
    toggleScreenShare,
    sendDataMessage,
    onDataMessage,
  };
}
